### ISSUE TITLE
Flutter Web support

### ISSUE THREAD

**Issue by CoderSpinoza** [kakao/kakao_flutter_sdk#10]
### Checklist

There are several steps necessary to enable web support for Kakao Flutter SDK.

- [x] Distinguish KA header for javascript environment
- [x] Authorize with `window.open()` (default method)
- [ ] Provide a way to authorize with `location.href`
- [ ] Allow CORS for Kakao API Server
- [ ] Release with web support

> `Login via KakaoTalk` will be currently unavailable for web since it requires access token polling and other more complex mechanisms.

**Comment by wurikiji** [comment]
Hi, how is it going? Are you still working on web support or not?
