### ISSUE TITLE
 'package:kakao_flutter_sdk/src/local/local_api.dart'등 일부 파일에 오류가 발생하였습니다.

### ISSUE THREAD

**Issue by ssoljin** [kakao/kakao_flutter_sdk#100]
안녕하세요, kakao_flutter_sdk  0.7.1, Flutter (Channel stable, 2.0.2, on macOS 11.4 20F71 darwin-arm, locale ko-KR)를 사용중입니다.

빌드중에 'package:kakao_flutter_sdk/src/local/local_api.dart'에서  다음과 같은 오류가 뜹니다.

kakao_flutter_sdk-0.7.1/lib/src/search/search_api.dart:31:33: Error: Expected '}' before this.
          {Order? sort, int? content.page, int? size}) async {
                                                    ^

비슷한 오류를 가진 'package:kakao_flutter_sdk/src/search/search_api.dart'해당 부분에서 content.page를 page 로 수정하였더니 작동합니다.

버전 관련 문제일까요?

감사합니다.

**Comment by mbkim95** [comment]
안녕하세요~

제보주신 이슈를 확인해보려했지만 재현이 되지 않아서 파악하지 못했네요ㅠ

혹시 오류가 발생하는 코드 첨부 가능하신가요?
