### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.

### ISSUE THREAD

**Issue by bringup2016** [kakao/kakao_flutter_sdk#101]
kotlin version    ext.kotlin_version = '1.3.40'
gradle version        classpath 'com.android.tools.build:gradle:7.0.0

Flutter 2.2.2
Dart 2.13.3 에서 다음과 같은 오류가 발생합니다.

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':kakao_flutter_sdk' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31

**Comment by mbkim95** [comment]
안녕하세요~

gradle 버전과 kotlin 버전의 호환이 되지 않아서 발생한 것으로 보이는데요, 현재 kakao_flutter_sdk 는 코틀린 1.3.31 버전을 사용하고 있습니다.

External Libraries -> Flutter Plugins -> kakao_flutter_sdk-0.7.1 -> android -> build.gradle에서 `ext.kotlin_version`을 1.3.40으로 수정하셔야 정상 동작할 것으로 보입니다.
```
group 'com.kakao.sdk.flutter'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.3.40'
    ...
}
```

해당 이슈에 대한 내용은 다음 버전에 수정해서 배포하도록 하겠습니다.

감사합니다

**Comment by mbkim95** [comment]
@bringup2016 제보주신 내용 수정된 kakao_flutter_sdk 0.8.1 배포되었습니다.

**Comment by bringup2016** [comment]
정말 감사합니다. 배포 확인했습니다.
