### ISSUE TITLE
me 호출시에 에러가 납니다. (카카오로그인을 하지 않고 호출하였습니다.)

### ISSUE THREAD

**Issue by stud214** [kakao/kakao_flutter_sdk#102]
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
#0      _$KakaoApiExceptionFromJson (package:kakao_flutter_sdk/src/common/kakao_api_exception.g.dart:14:22)
#1      new KakaoApiException.fromJson (package:kakao_flutter_sdk/src/common/kakao_api_exception.dart:28:7)
#2      ApiFactory.transformApiError (package:kakao_flutter_sdk/src/common/api_factory.dart:80:30)
#3      RequiredScopesInterceptor.onError (package:kakao_flutter_sdk/src/auth/required_scopes_interceptor.dart:22:28)
#4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:557:28)
#5      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:795:22)
#6      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:555:22)
#7      new Future.<anonymous closure> (dart:async/future.dart:174:37)
#8      _rootRun (dart:async/zone.dart:1346:4<…>

![스크린샷 2021-09-03 오후 6 13 37](https://user-images.githubusercontent.com/69521874/131982104-c191d7ef-0722-428e-867b-731e24f05b2e.png)

확인 부탁드립니다.

**Comment by mbkim95** [comment]
안녕하세요

me 호출은 카카오 로그인을 진행해야 정상적으로 동작합니다.

로그인 후에 호출하도록 수정 부탁드려요

**Comment by stud214** [comment]
안녕하세요 이미 me호출은 확인 하였습니다.
카카오  me 호출시에 예외를 캐치 할 수 없어서 문의 드렸습니다.
디버깅 해보니 예외를 생성하다 crash가 발생하는 것 같아서요.
감사합니다.

**Comment by mbkim95** [comment]
말씀하신 예외라는게 어떤 예외를 말씀하시는건가요?

**Comment by stud214** [comment]
예를 들어 로그인하지 않고 me 호출시에 제가 드린 스크린샷처럼 토큰이 존재하지 않는다고 나오는데 이응답을 가지고 sdk에서 exception을 생성하다 크래쉬가 나는 듯 해서 문의 드렸어요 
감사합니다.

**Comment by mbkim95** [comment]
아 내용 이해했습니다.

말씀주신 부분은 확인 후 수정해서 다음 버전에 반영하도록 하겠습니다.

제보 감사합니다

**Comment by stud214** [comment]
다음 버전이 혹시 언제 나올까요? 플루터 버전이 이번에 처음이라 안정적으로 적용하고 싶어서 문의 드립니다.
감사합니다.

**Comment by mbkim95** [comment]
제보주신 에러는 수정했고, 이번주 중으로 배포할 계획입니다. 감사합니다.

**Comment by mbkim95** [comment]
@stud214 제보주신 내용 수정해서 kakao_flutter_sdk 0.8.1 배포되었습니다
