### ISSUE TITLE
accessToken 만료시 UserApi.instance.me 호출이 정상적으로 안되는 현상

### ISSUE THREAD

**Issue by vkimone** [kakao/kakao_flutter_sdk#103]
Flutter : 2.2.3
kakao flutter sdk : 0.7.1
Kakaotalk App : Not installed

기존에 로그인 했으면 자동으로 로그인(사용자 프로필 사진 표시) 하는 프로세스를 개발중에 있습니다.
일반적인 로그인 및 엑세스 토큰이 유효했을때 자동으로 로그인하는 과정은 특별한 이슈는 없지만 엑세스 토큰이 만료 되었을 상황에서 UserApi.instance.me() 를 호출하면  아래와 같은 로그만 나올뿐 더이상 진행이 되지 않습니다. (crash 가 발생하지는 않음)
로그인은 UserApi.instance.loginWithKakaoAccount 를 이용하여 카톡앱이 설치되어있지 않은 환경에서 테스트 중입니다. 

> I/flutter (19001): retry /v2/user/me after refreshing access token.

그리고 위 메시지 이후에 다시 앱을 재실행하면 정상적으로 자동로그인 처리가 되는걸 보면 엑세스 토큰이 위 과정에서 재발급 된걸로 보입니다.

가이드문서 내용으로는 엑세스 토큰 만료시 특별한 처리를 하지 않더라도 sdk 내부에서 갱신해서 처리하기 때문에 수동으로 갱신할 필요가 없다고 나온거 같은데 아닌가요?

질문을 정리하면 엑세스 토큰 만료시 UserApi.instance.me()와 같이 로그인이 필요한 서비스를 호출할때 그 이전에 수동으로 토큰 갱신 과정이 필요한가? 그렇다면  이와 관련된 내용은 어디시 찾아볼 수 있을까요?

그리고 엑세스 토큰 유효시간을 개발쪽에서 임의로 짧게 수정할 수 있나요.  현재는 12시간인걸로 아는데 위 테스트를 진행할려면 12시간씩 기다려야해서 좀더 효율적인 방법이 없나 문의드려봅니다.

**Comment by mbkim95** [comment]
안녕하세요

질문 주신 액세스 토큰 만료시 sdk 내부에서 토큰 자동 갱신의 경우 이해하신대로 자동 갱신되는게 맞으나, 확인 결과 관련된 코드에 문제가 있어 자동 갱신이 되지 않고 있었습니다. 토큰 자동 갱신 기능은 현재 버그가 수정되었고, 다음 버전 배포에 포함될 예정입니다. 이슈 제보 감사합니다

그리고 테스트를 위해 엑세스 토큰 유효시간을 변경할 수 있는지에 대해 문의주셨는데, 아쉽지만 토큰 시간을 수정할 수 없어서 번거로우시더라도 엑세스 토큰이 만료된 후에 테스트를 진행하시는 방법 밖에 없습니다.ㅠㅠ

**Comment by mbkim95** [comment]
@vkimone 제보주신 내용 수정된 kakao_flutter_sdk 0.8.1 배포되었습니다.

**Comment by vkimone** [comment]
### [Environment]
Flutter : 2.5.0
kakao flutter sdk : 0.8.1
Kakaotalk App : Not installed



###  [Actual Result]

- 최신버전인 0.8.1 로 업데이트해서 엑세스토큰 만료 이후 아래와 같이 사용자 정보를 받아오는 함수를 호출하였는데 `ApiErrorCause.INVALID_TOKEN` 예외가 발생함.

- 앱을 다시 재시작하면 자동로그인이 정상적으로 되는걸 보면 엑세스 토큰은 위 과정에서 정상적으로 갱신되는 것으로 보임. (0.7.1 버전에서도 동일했음)


````
 _getUserInfo() async {
    try {
      User user = await UserApi.instance.me();
     
    } on KakaoApiException catch (e) {
      if (e.code == ApiErrorCause.INVALID_TOKEN) {
        
          // ApiErrorCause.INVALID_TOKEN 예외발생함

      }
      
    } catch (e) {
      print('other api or client-side errors : ${e.toString()}');
    }
  }
````

### [Expected Result]
엑세스 토큰이 만료 되었을 상황에서 `UserApi.instance.me()` 호출 했을 경우 sdk 내부에서 자동으로 엑세스 토큰이 갱신되고 User 객체가 반환되어야 함

### [Question] 
기존에 사용자가 이미 로그인한 상태에서 엑세스 토큰이 만료되었을 때 자동로그인을 구현하려고 하면 어떤식으로 구현하면 될까요?
토큰 유효성을 검사해서 토큰 만료전에 강제로 갱신해서 처리하면 되긴하지만 엑세스 토큰 갱신이 sdk 내부에서 자동으로 이루어진다고 해서 따로 토큰갱신 부분은 구현하지 않았던거였는데 뭔가 제가 놓친 부분이 없는가 궁금합니다. 

감사합니다.

**Comment by mbkim95** [comment]
SDK 내부적으로 엑세스 토큰 갱신 처리는 다음과 같은 로직으로 동작하고 있습니다.

### SDK 내부 로직
1. 엑세스 토큰 만료, 리프레시 토큰 유효
-> 리프레시 토큰으로 엑세스 토큰 갱신 후, API 재호출

2. 엑세스 토큰 만료, 리프레시 토큰 만료
-> 리프레시 토큰으로 엑세스 토큰 갱신 시도
-> 리프레시 토큰이 만료되었으므로 에러
-> SDK 내부에 저장된 엑세스 토큰, 리프레시 토큰 삭제

따라서 자동 로그인은 크게 2가지 방법으로 구현할 수 있는데요

### 자동 로그인 구현
#### 토큰 저장 유무로 파악하는 방법
1. `TokenManager.instance.getToken()`을 호출해 SDK 내부에 토큰이 저장되어있는지 확인 (서버 통신 X)
2. 토큰이 `null` 이라면 로그인 페이지로 이동
3. 토큰이 `null`이 아니라면 로그인 이후 동작하는 페이지로 이동

#### 앱 시작시 API를 호출해서 토큰을 갱신해주는 방법
1. `UserApi.instance.accessTokenInfo()`를 호출해 현재 발급된 토큰 정보 확인 (서버 통신 O)
2. 에러가 발생하면 로그인 페이지로 이동
3. 에러가 발생하지 않았다면 엑세스 토큰이 유효하거나, 새로 갱신된 경우이기 때문에 로그인 이후 동작하는 페이지로 이동

자동 로그인이라고 말씀하신 것이 리프레시 토큰이 유효하고, 엑세스 토큰이 만료된 상황일 때, 유저가 별도의 로그인을 시도하지 않아도 앱이 로그인 된 상태를 유지하는 것이라고 이해했는데요, 혹시 제가 잘못 이해한건가요?

만약 자동로그인이 제가 말한 것과 동일한 의미인데도 정상적으로 동작하지 않고 있다면 구현하신 코드를 확인해볼 수 있을까요?
프로젝트 파일을 mbkim95@naver.com 으로 보내주시면 보내주신 프로젝트 파일로 테스트해보겠습니다.

**Comment by vkimone** [comment]
sdk 내부에서 자동으로 갱신된다고해서 특별히 다른 호출은 하지 않았었는데   먼저 `UserApi.instance.accessTokenInfo()` 를 반드시 호출해야 엑세스 토큰이 갱신이 되는군요. 가이드 문서에는 해당 내용이 추가되면 좋을 것 같습니다. 
테스트 결과 문제없이 토큰 갱신되어서 처리됩니다.
감사합니다.

**Comment by mbkim95** [comment]
엑세스 토큰이 만료되고 리프레시 토큰이 유효한 상황에는 어떤 API를 호출하는지와 상관 없이 엑세스 토큰이 갱신되는 것이 맞기 때문에 가이드에는 해당 내용이 추가되기는 어려울 것 같아요.

위의 답변에서 `UserApi.instance.accessTokenInfo()` 로 가이드 드렸던 이유는 가장 가벼운 API이기 때문에 자동 로그인 기능을 구현할 때 사용하기 가장 적합하기 때문이었습니다. 이 점 참고 부탁드려요.

정확히 어떤 이슈 때문에 자동 로그인 구현이 안되었는지 제대로 파악하지 못한 상황이라서,  구현하시다 다시 이슈가 발생한다면 언제든지 제보 부탁드리겠습니다.

감사합니다!
