### ISSUE TITLE
NoSuchMethodError: The method '*' was called on null.

### ISSUE THREAD

**Issue by jeiea** [kakao/kakao_flutter_sdk#106]
# 재현 방법

```
final authCode = await AuthCodeClient.instance.requestWithTalk(scopes: scopes);
final token = await AuthApi.instance.issueAccessToken(authCode);
await TokenManager.instance.setToken(token);
final secondToken = await TokenManager.instance.getToken();
await TokenManager.instance.setToken(secondToken);
```

# 기대 동작

카카오톡으로 정상적인 로그인을 진행했을 때 문제가 없어야 합니다.

# 실제 동작

```
NoSuchMethodError: The method '*' was called on null.
Receiver: null
Tried calling: *(1000)
#0   package:kakao_flutter_sdk/src/auth/token_manager.dart 70:18   DefaultTokenManager.setToken
```

# 추가 정보

[여기](https://github.com/kakao/kakao_flutter_sdk/blob/6c3f9edf52d32ebb2e52aee2a081790db17b044d/lib/src/auth/token_manager.dart#L70)에서 `rtExpiresAt`의 값이 null일 때가 있었습니다.

**Comment by mbkim95** [comment]
안녕하세요

현재 사용 중인 kakao_flutter_sdk 버전과 발생 디바이스의 os 버전이 어떻게 되나요?

**Comment by jeiea** [comment]
추가로 정보를 요구하시는 걸로 보아 재현이 잘 안 되는 듯 하니 나중에 저장소를 하나 만들어보겠습니다. 저 코드는 실제 코드는 아니고 임의로 작성한 거라 해당 정보를 제공해도 재현하기 어려울 수 있을 것 같네요.

**Comment by mbkim95** [comment]
현재 최신 버전(0.8.1)에서는 `TokenManager.setToken()`, `TokenManager.getToken()`의 파라미터, 리턴 타입이 달라서 작성하신 코드로는 버그를 재현할 수 없는 상황입니다ㅠㅠ 

추가로 0.7.0 버전부터 `UserApi.loginWithKakaoTalk()`, `UserApi.loginWithKakaoAccount()`를 제공하고 있어서 해당 메소드를 사용하면 좀 더 쉽게 로그인을 구현하실 수 았습니다. 이 점 참고 부탁드려요

**Comment by jeiea** [comment]
[kakao 브랜치](https://github.com/jeiea/flutter_example/tree/kakao)에 예제 만들었습니다. 제가 사이에 `AuthApi.instance.refreshAccessToken`을 호출하는 부분을 빠뜨렸습니다.
UserApi의 새 메소드는 이전 방식을 아예 대체하는 걸까요?

**Comment by mbkim95** [comment]
공유주신 코드 확인해서 이슈 재현되는거 확인했습니다. 제보주신 이슈는 수정 후 조만간 배포될 예정이고, 추가로 `AuthApi.refreshAccessToken()`의 스펙이 조금 수정될 예정입니다. 해당 메소드를 호출하면 kakao_flutter_sdk 내부에서 재발급된 토큰을 저장하고 (refreshAccessToken 호출 후에 사용자가 따로 토큰을 저장하지 않아도 됨), 메소드의 리턴 타입이 `OAuthToken` 으로 변경됩니다.

그리고 문의주신 UserApi의 메소드에 대해서는 기존의 인증 코드를 받아 토큰을 발급받고, 토큰을 저장하는 과정을 추상화하여 사용자가 좀 더 쉽게 로그인을 구현할 수 있도록 만든 메소드들이라서 기존 방식에서 문제없이 대체 가능합니다. 자세한 사용 방법은 [해당 문서](https://github.com/kakao/kakao_flutter_sdk#kakao-login) 참고바랍니다

**Comment by mbkim95** [comment]
제보 주신 이슈 수정된 0.8.2 버전 배포되었습니다.

이슈 제보 감사합니다~
