### ISSUE TITLE
No uri was passed to AuthCodeCustomTabsActivity.

### ISSUE THREAD

**Issue by probepark** [kakao/kakao_flutter_sdk#108]
Hi

I have met this problem.
I don't know what to do.. 
How to fix it?

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{net.sjang.sail/com.kakao.sdk.flutter.AuthCodeCustomTabsActivity}: java.lang.IllegalArgumentException: No uri was passed to AuthCodeCustomTabsActivity. This might be a bug in Kakao Flutter SDK.
```

**Comment by mbkim95** [comment]
Hello

What version of kakao_flutter_sdk are you using?

And What is your app id? App id is the value that can be found in [Kakao Developers](https://developers.kakao.com/).

If you attach the login code that you implemented, It can help me to find issue. Please attach your codes.

**Comment by probepark** [comment]
I'am using kakao_flutter_sdk: ^0.8.1.
and appId is 2501

```dart
  Future<String> _getAuthCode() async {
    final installed = await isKakaoTalkInstalled();
    if (installed) {
      try {
        return await AuthCodeClient.instance.requestWithTalk();
      } on PlatformException catch (e) {
        if (e.code == "NotSupportError") {
          return await AuthCodeClient.instance.request();
        } else {
          rethrow;
        }
      }
    } else {
      return await AuthCodeClient.instance.request();
    }
  }
```

login method
```dart
     final authCode = await _getAuthCode();

      final response = await AuthApi.instance.issueAccessToken(authCode);
      TokenManager.instance.setToken(response);

      final token = await TokenManager.instance.getToken();
      Logger.log('kakao token: ${token.accessToken}');
```

**Comment by mbkim95** [comment]
I failed to reproduce the issue. Does the issue happen on all Android devices?

And in order to accurately identify the cause of the issue, please write down the device where the issue occurred and the exact date and time when the issue occurred.

**Comment by probepark** [comment]
It occurred problem these devices.

PIXEL 2 XL(Android 7) - 2021. 10. 5. 오전 8:06:59
Galaxy Note4(Android 7) - 2021. 10. 1. 오후 11:40:49
Galaxy Note9(Android 6) - 2021. 10. 2. 오후 8:09:04
