### ISSUE TITLE
apk파일로 테스트하는방법이 있나요?

### ISSUE THREAD

**Issue by kindkmj** [kakao/kakao_flutter_sdk#111]
play store에 등록된것과 기기를 연결해서 하는건 정상적으로 테스트가 가능한데
apk파일을 추출해서 테스트하게되면 키가 다르다고 뜨는데..

apk파일로는 카카오 인증 테스트가 힘들까요?

**Comment by mbkim95** [comment]
안녕하세요

오류에 대해서 조금 더 자세한 설명 부탁드려요.

사용한 kakao_flutter_sdk 버전, 오류 디바이스 정보 (os 버전, 모델명), 오류 로그 첨부 부탁드립니다.

**Comment by kindkmj** [comment]
flutter version 
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (6달 전) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

kakao sdk version
kakao_flutter_sdk: ^0.8.1

오류 디바이스 정보 갤럭시 노트10+ os 최신버전

오류 로그 
{“error”:“misconfigured”,“error_description”:“invalid android_key_hash or ios_bundle_id or web_site_url”}
입니다.

developers 의 앱 id :  626116
입니다.

기기에 직접 연결해서 디버깅할때와 google play store에서 다운받아서는 정상적으로 잘 동작하나
apk파일을 추출해서 실행하면 해당 오류가 발생합니다.
디버깅 키와 release 키 google 키 모두 입력하였습니다.
릴리즈 키는 잘 몰라서 
release 키 등록은  Build -> Generate Signed Bundle / APK
2. Android App Bundle 또는 APK 선택
3. Create New
4. Key store path 설정 -> Password와 Password Confirm 입력

5. 공백 기입 ( 전부 기록할 필요는 없습니다. ) -> OK
6. Next
https://dev-donghwan.tistory.com/79
해당 블로그를 참고해서 만들어서 등록했습니다..

제가 무언가 잘못한게 있다면 말씀 부탁드립니다.. 
감사합니다.

**Comment by mbkim95** [comment]
서버 로그를 확인해봤는데요, 키 해시가 4NQMh************** 로 요청이 들어오고 있네요.

KH7HM*****************
UGZ7Y*****************
nV5uH*****************
nZYZZ*****************

현재 등록된 키 해시는 위의 4가지라서 오류가 발생하고 있습니다.

첨부해주신 링크도 확인해봤는데요, 추측하기로 플러터 프로젝트에서 android 디렉토리를 Android Studio로 열어서 빌드하신 것 같아요

플러터 루트 프로젝트에서 APK를 만들어서 다시 확인 부탁드려요.

Build -> Flutter -> Build APK 를 선택하시면 됩니다.

**Comment by kindkmj** [comment]
@mbkim95 
답변해주셔서 감사드립니다.
apk파일 추출할때는 flutter 루트 프로젝트 터미널에서
flutter build apk --release --no-sound-null-safety
라는 키워드로 apk파일을 만들어서 사용했습니다.
루트프로젝트에서 릴리즈 키를 발급받아야 한다는 말씀이실까요?

**Comment by mbkim95** [comment]
아 블로그 링크 첨부해주신 것처럼 Build -> Generate Signed Bundle / APK 를 눌러서 APK를 만드셨다는 얘기로 이해했네요

flutter build apk --release --no-sound-null-safety 명령어로 만드셨다면 제가 말씀드린 방법과 동일한 방법으로 만든게 맞네요

APK를 생성한 환경의 키 해시가 제대로 등록이 안되어있는 것 같은데요, 키 해시 값 4NQMh************** 를 다시 한번 확인 부탁드려요

**Comment by kindkmj** [comment]
해당 키는 어디서 나온건지 도통 알기가 쉽지않네요... ㅜㅜ 
일단 말씀해주신 키를 찾는방법으로 계속 테스트해보겠습니다....

**Comment by mbkim95** [comment]
아 링크의 방법으로 APK를 만드신게 아니라 키를 추출하신거군요. 제가 혼동했었네요ㅎㅎ

키 해시라는 것은 인증서 지문 값을 해시한 고유값으로, 로컬 PC에서 앱을 빌드했다면 해당 PC의 키 해시 값을 구해서 입력하시면 되고, 구글 플레이 스토어에 앱을 업로드 하셨다면 키 해시를 다시 등록해야합니다. 
따라서 기기마다 키를 발급해서 넣는 것은 아니구요, APK를 생성한 PC에서 키 해시를 구해서 해당 값을 디벨로퍼스 사이트에 등록하시면 됩니다.

키 해시를 구하는 방법은 [가이드](https://developers.kakao.com/docs/latest/ko/getting-started/sdk-android#add-key-hash)를 참고하시면 될 것 같습니다.

**Comment by kindkmj** [comment]
로컬피시에서 키를 발급받아 등록한게 아마 nV5uH***************** 이거 같습니다.
import com.kakao.sdk.common.util.Utility

var keyHash = Utility.getKeyHash(this)
이걸사용해서 키를 얻고싶은데 flutter에서는 어떻게 사용이 가능할까요?

**Comment by mbkim95** [comment]
안드로이드 디바이스에서 `KakaoContext.origin` 값이 키 해시 값이라서 해당 값을 등록하시면 돼요

**Comment by kindkmj** [comment]
@mbkim95 
감사합니다. 키가 드디어 나오네요... ㅠㅠ

**Comment by yangsoo12** [comment]
`keytool -printcert -jarfile <filename>.apk` 에서 나오는 sha1 해시를 base64로 변환하시면 됩니다.
[How do I get an apk file from an Android device? - stackoverflow](https://stackoverflow.com/a/18003462)
[How can I convert from hex to base64? - superuser](https://superuser.com/a/416630)
