### ISSUE TITLE
카카오 화면 잠금 설정 시 로그인

### ISSUE THREAD

**Issue by Lee-jaejin** [kakao/kakao_flutter_sdk#116]
안녕하세요.

카카오앱에 화면 잠금이 설정되어 있는 경우 카카오앱을 통한 로그인 연결이 되지 않는것으로 보여 문의드립니다.

해당하는 경우에 따로 설정해야 하는 값이 있는지, 아직 지원이 되지 않는 것인지 답변 부탁드리겠습니다.

감사합니다.

버전: 0.8.~

**Comment by mbkim95** [comment]
안녕하세요

카카오톡이 잠금 설정이 되어있어도 별도의 설정 없이 로그인이 가능하고 Android, iOS 디바이스에서 정상 동작하는 것도 재확인했습니다.

구현상의 문제 혹은 카카오 로그인을 위한 설정이 누락된 것이 있는 것으로 추측되어서 작성하신 코드 및 로그인을 위한 설정 등을 확인부탁드려요

**Comment by Lee-jaejin** [comment]
답변 감사드립니다. 이슈 닫겠습니다.
