### ISSUE TITLE
Confusion in readme about use of KakaoAuthException

### ISSUE THREAD

**Issue by LeGoffMael** [kakao/kakao_flutter_sdk#117]
In the readme you mentioned multiple times to use `KakaoAuthException` when the access token is expired like this:
```dart
...
on KakaoAuthException catch (e) {
    if (e.code == ApiErrorCause.INVALID_TOKEN) { // access token has expired and cannot be refrsehd. access tokens are already cleared here
      Navigator.of(context).pushReplacementNamed('/login'); // redirect to login page
    }
  }
...
```

However there is no `code` param in `KakaoAuthException`.

So i am confuse about the correct behavior to check.
Should it be 1:

```dart
on KakaoAuthException catch (e) {
    if (e.error == AuthErrorCause.INVALID_GRANT)
        ...
}
```
or 2:
```dart
on KakaoApiException catch (e) {
      if (e.code == ApiErrorCause.INVALID_TOKEN)
        ...
}
```

When i am using `Sentry` the error i receive is 
```
KakaoAuthException: {error: invalid_grant, error_description: expired_or_invalid_refresh_token}
```
so i guess we should use 1: `AuthErrorCause.INVALID_GRANT`.

Please let me know if i misunderstood the readme or please update the documentation with the correct exception code to check.

**Comment by mbkim95** [comment]
Hello

What you said is typo. So I'll update the documentation.

It will be applied to documentation when the next version is released.

thanks for your report

**Comment by mbkim95** [comment]
Hello

It is a typo. The first one what you said is correct.

So I'll update the documentation. It will be applied to documentation when the next version is released.

Thanks for your report!

**Comment by mbkim95** [comment]
@LeGoffMael 
I'm sorry for reversing my words.

If you use latest version(now 0.9.0), The error is KakaoClientException when access token and refresh token are both expired. And if access token is expired but refresh token is available, the sdk will reissue token automatically. So in this case, The error is not occured.

Please note this.

**Comment by LeGoffMael** [comment]
> @LeGoffMael I'm sorry for reversing my words.
> 
> If you use latest version(now 0.9.0), The error is KakaoClientException when access token and refresh token are both expired. And if access token is expired but refresh token is available, the sdk will reissue token automatically. So in this case, The error is not occured.
> 
> Please note this.

Thank you for your explanation. It is good that it will be reissue automatically.
Can you please update the readme about this behavior ?

**Comment by mbkim95** [comment]
Please note [this commit](https://github.com/kakao/kakao_flutter_sdk/blob/1c229b478c3aa66b3ccdbb697f216b11b6351410/README.md)

It will be applied to documentation when the next version is released.

Thank you
