### ISSUE TITLE
android 카카오톡 채널 채팅 

### ISSUE THREAD

**Issue by CHOI-YOOBIN** [kakao/kakao_flutter_sdk#119]
카카오톡 채널 채팅을 사용하기 위해서 아래 코드를 이용했습니다.
`final _url = await TalkApi(Dio()).channelChatUrl(_channelId);`

iOS에서는 정상적으로 작동하지만, android에서는 접근 불가능한 주소라고 뜨는데 sdk 문제인지 채널 설정 문제인지 모르겠습니다.
![스크린샷 2021-12-06 10 34 47](https://user-images.githubusercontent.com/59527787/144773644-a1ecb86c-6194-49b8-ae50-985f4e38a1dd.png)

**Comment by mbkim95** [comment]
안녕하세요

앱 id가 어떻게 되시나요?

그리고 구현하신 코드를 조금 더 첨부 부탁드려요

**Comment by CHOI-YOOBIN** [comment]
@mbkim95 
앱 id: 420236

<pre><code>
  // 카카오톡 문의.
  Future<void> openKakaoChannel({required bool isBillyoChannel}) async {
    const _channel = '_zGKwxb';
    await TalkApi(Dio()).channelChatUrl(_channel).then((url) async {
      await openUrl(url: url.toString());
    });
  }

  // url 열기.
  Future<void> openUrl({required String url}) async {
    // ios.
    // url launch.
    if (Platform.isIOS) {
      if (await canLaunch(url)) {
        await launch(url);
      } else {
        logger.e('url launch error $url');
      }
    }

    // android.
    // intent.
    else {
      try {
        final _intent = AndroidIntent(
          action: 'action_view',
          data: Uri.encodeFull(url),
        );
        await _intent.launch();
      } catch (e) {
        logger.e('androidIntent error $url');
      }
    }
  }
<code><pre>

**Comment by mbkim95** [comment]
안드로이드에서 url 인코딩되는 과정에서 발생한 이슈인 것으로 추측되고 있는데요, ios, android 웹뷰에서 접근하는 url 첨부가 가능할까요?

**Comment by CHOI-YOOBIN** [comment]
아래 url 은 `TalkApi(Dio()).channelChatUrl(_channel)` 결과 url 입니다!

안드로이드: https://pf.kakao.com/_zGKwxb/chat?app_key=fed26b5b303a0dcc513364dc113149e1&kakao_agent=sdk%2F0.9.0+sdk_type%2Fflutter+os%2Fandroid-30+lang%2Fen-US+origin%2FlORLN2yjGRe5cMLgQHmObcuBm6Y%3D+device%2FANDROID-SDK-BUILT-FOR-X86+android_pkg%2Fcom.billyo.billyo_app+app_ver%2F2.5.1&api_ver=1.0

ios: https://pf.kakao.com/_zGKwxb/chat?app_key=fed26b5b303a0dcc513364dc113149e1&kakao_agent=sdk%2F0.9.0+sdk_type%2Fflutter+os%2Fios-15.0+lang%2Fen+res%2F390.0x844.0+device%2FiPhone+origin%2Fcom.billyo.billyoApp+app_ver%2F2.5.1&api_ver=1.0

**Comment by mbkim95** [comment]
위에 첨부해주신 코드를 보면 안드로이드의 경우에는 intent에 담기위해서 한번 더 인코딩되는 것으로 보이고 있어요. 현재 의심 중인 부분이 해당 부분이라서 해당 url를 첨부해주시면 감사하겠습니다!

**Comment by CHOI-YOOBIN** [comment]
> 위에 첨부해주신 코드를 보면 안드로이드의 경우에는 intent에 담기위해서 한번 더 인코딩되는 것으로 보이고 있어요. 현재 의심 중인 부분이 해당 부분이라서 해당 url도 첨부해주시면 감사하겠습니다!
> 
> 그리고 첨부하신 url에 앱 키가 노출되어 있어서 앱 키를 마스킹처리해 두었습니다.

**Comment by mbkim95** [comment]
@CHOI-YOOBIN 아 그리고 미처 말씀을 못드렸는데, `TalkApi`는 싱글턴이므로 `TalkApi(Dio())` 으로 사용하고 계신 부분은 `TalkApi.instance` 로 수정해서 사용부탁드립니다.

**Comment by CHOI-YOOBIN** [comment]
안드로이드 기기에서 

ios url: https://pf.kakao.com/_zGKwxb/chat?app_key=**********&kakao_agent=sdk%2F0.9.0+sdk_type%2Fflutter+os%2Fios-15.0+lang%2Fen+res%2F390.0x844.0+device%2FiPhone+origin%2Fcom.billyo.billyoApp+app_ver%2F2.5.1&api_ver=1.0

로 열면 정상적으로 열리네요

**Comment by mbkim95** [comment]
channelChatUrl API 호출 후에 생성되는 url을 보시면 kakao_agent가 있는데요, 해당 파라미터는 요청을 검증하기 위해 사용되고 있습니다. 서버 로그 및 첨부주신 url을 확인해보면 kakao_agent 값이 인코딩되면서 저희쪽 서버에서 인식할 수가 없게되어 이슈가 발생한 것 같습니다.

안드로이드를 기준으로 처음 첨부해주신 url의 kakao_agent 값은 아래와 같습니다.

kakao_agent=sdk%2F0.9.0+sdk_type%2Fflutter+os%2Fandroid-30+lang%2Fen-US+origin%2FlORLN2yjGRe5cMLgQHmObcuBm6Y%3D+device%2FANDROID-SDK-BUILT-FOR-X86+android_pkg%2Fcom.billyo.billyo_app+app_ver%2F2.5.1

이 값을 디코딩해보면 아래와 같이 변환됩니다.

kakao_agent=sdk/0.9.0 sdk_type/flutter os/android-30 lang/en-US origin/lORLN2yjGRe5cMLgQHmObcuBm6Y= device/ANDROID-SDK-BUILT-FOR-X86 android_pkg/com.billyo.billyo_app app_ver/2.5.1

다시 공유주신 url에서 kakao_agent 값은 아래와 같습니다.

kakao_agent=sdk%252F0.9.0+sdk_type%252Fflutter+os%252Fandroid-30+lang%252Fen-US+origin%252FlORLN2yjGRe5cMLgQHmObcuBm6Y%253D+device%252FANDROID-SDK-BUILT-FOR-X86+android_pkg%252Fcom.billyo.billyo_app+app_ver%252F2.5.1

이 값을 디코딩해보면 

kakao_agent=sdk%2F0.9.0 sdk_type%2Fflutter os%2Fandroid-30 lang%2Fen-US origin%2FlORLN2yjGRe5cMLgQHmObcuBm6Y%3D device%2FANDROID-SDK-BUILT-FOR-X86 android_pkg%2Fcom.billyo.billyo_app app_ver%2F2.5.1

두 디코딩 결과를 확인해보시면 sdk/0.9.0 sdk_type/flutter os .... 으로 나와야할 값이 sdk%2F0.9.0 sdk_type%2Fflutter os ... 으로 나온 것을 볼 수 있습니다. 따라서 API를 호출해서 나온 url을 그대로 사용하면 이슈가 해결될 것으로 보입니다.

참고로 channelChatUrl 메소드의 리턴 타입은 Uri 이므로 String으로 변환했다가 Intent에 담기위해 다시 Uri로 변환하는 로직은 제거되어도 될 것 같아요.

**Comment by CHOI-YOOBIN** [comment]
잘작동합니다! 너무 자세히 알려주셔서 감사합니다

**Comment by mbkim95** [comment]
@CHOI-YOOBIN  해결되서 다행이네요ㅎㅎ 

처음에 uri 첨부해주신 답글은 수정 기록을 통해서 앱 키를 볼 수 있어서 혹시 몰라 삭제해둘게요. 참고부탁드려요~
