### ISSUE TITLE
flutter에서도 사용자의 친구목록을 불러올 수 있나요?

### ISSUE THREAD

**Issue by PlXLD** [kakao/kakao_flutter_sdk#120]
flutter에서도 소셜api를 이용하여 카카오톡 친구목록 정보를 받아 사용할수있나요?

**Comment by mbkim95** [comment]
안녕하세요

`TalkApi#friends` 를 사용해 친구 목록을 받아올 수 있지만, 카카오톡 친구 목록을 모두 가져오기 위해서는 별도의 권한이 필요합니다.

자세한 내용은 [가이드](https://developers.kakao.com/docs/latest/ko/kakaotalk-social/common#policy) 참고 부탁드립니다.

**Comment by PlXLD** [comment]
sdk를 사용해서 카카오 로그인은 구현완료되어 파이어베이스 연동확인까지 완료하였습니다, 

로그아웃기능을 앞에 페이지를 보고 만들었는데 로그아웃하면 초기화면으로 돌아가지만, 이미 한번 로그인 했던 폰에서는 재 로그인을 했을때 처음처럼 권한을 물어본다던지 하지않고 자동으로 로그인이되었습니다(파이어베이스에 있는 데이터를 지우고 앱도지우고 다시 빌드했을때에도) 권한 설정을 바꿨는데 권한 물어보는 화면이 안떠서 그런데 로그인한 것을 아예 리셋하는방법이 있을까요.

**Comment by mbkim95** [comment]
unlink API 호출 후에 다시 로그인하시면 됩니다~

**Comment by PlXLD** [comment]
로그아웃 버튼에 연결되어있는 함수입니다.
logoutUser() async {
    try {
      await const FlutterSecureStorage().deleteAll();

      Navigator.pushReplacement(context,
          MaterialPageRoute(builder: (context) => const LoginPage())).then((_) {
        if(mounted) {
          setState(() {
            currentUser = null;
          });
        }
      });
    } catch (e) {
      print(e.toString());
    }
  }

이 상태에서 userapi.instance.unlink() 를 추가시켜줘야하는것인가욤?

**Comment by mbkim95** [comment]
https://developers.kakao.com/docs/latest/ko/kakaologin/common

logout()과 unlink()는 목적이 다르기 때문에 해당 문서 참고하셔서 상황에 맞게 구현하시면 될 것 같습니다.

연결 끊기 -> unlink
로그아웃 -> logout

입니다.

**Comment by PlXLD** [comment]
try {
      await const FlutterSecureStorage().deleteAll();
      await DefaultTokenManager().clear();
      try {
        var code = await UserApi.instance.logout();

        print(code.toString());
      } catch (e) {
        print(e);
      }

위 코드로 로그아웃 하였는데 로그아웃은되는데 다시 로그인하면 검은화면에서 안넘어가고,
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1900 pos 12: 'element._lifecycleState == _ElementLifecycle.active': is not true.

Duplicate GlobalKey detected in widget tree.
두 오류가 발생하는데 로그아웃 코드가 잘못된 것인가요? 재빌드하면 다시 자동으로 로그인됩니다.

**Comment by mbkim95** [comment]
@PlXLD 
답변이 늦어서 죄송합니다

에러 로그를 봤을 때, kakao_flutter_sdk의 이슈가 아니라 위젯의 상태관리가 제대로 되지 않아서 발생한 것으로 보입니다.

에러가 발생한 위젯에 키가 제대로 설정되어있는지, GlobalKey가 static으로 되어있는지 등 구현하신 코드를 확인해보셔야할 것 같아요.

앱 구현 상의 이슈로 보여서 제가 도움드리기는 어려울 것 같네요ㅠㅠ

**Comment by PlXLD** [comment]
해결했습니다! 감사합니다 
그 승인전에 데스트버전에서 친구목록불러오는것은 멤버로 등록한친구만뜨는건가요? 아니면 멤버로 등록된사람의 친구목록만 볼수있는건가요?

**Comment by mbkim95** [comment]
승인이라고 말씀주신 것은 'API 사용 권한 신청에 대한 승인' 을 의미하는건가요?

만약 이 의미가 맞다면, 승인 전까지는 친구 데이터로 해당 앱에 등록된 팀원들이 내려옵니다. (팀원들의 친구 목록은 볼 수 없습니다)

**Comment by PlXLD** [comment]
BlocBuilder<FriendsBloc, FriendsState>(
          builder: (context, state) {
            if (state is FriendsPermissionRequired) {
              return Padding(
                padding: EdgeInsets.all(15),
                child: Column(
                  children: <Widget>[
                    Text("Following scopes are required: ${state.scopes}"),
                    RaisedButton(
                      onPressed: () => BlocProvider.of<FriendsBloc>(context)
                          .add(RequestAgreement(state.scopes)),
                      textColor: Colors.white,
                      color: Colors.blue,
                      child: Text("Request scopes"),
                    )
                  ],
                ),
              );
            }
매번 감사합니다. 위에는 예제에있던 코드입니다
이중에서 BlocProvider.of<FriendsBloc>(context).add(RequestAgreement(state.scopes)), 이부분의
RequestAgreement를 화면이 넘어오면서 물어보고싶어서 밖으로 빼려니까 인자state.scopes부분이 해결이안되어서 그러는데
만약 밖에서쓰려면 인자를 뭘로 변경해야하나요?

**Comment by mbkim95** [comment]
샘플앱의 코드를 정확히 이해하기 위해서는 BLoC 패턴에 대해 학습이 필요합니다.

BLoC 패턴을 알고 계신다면 샘플 코드 참고해서 구현하시면 될 것으로 보이고, BLoC 패턴을 모르신다면 `UserApi#loginWithNewScopes` 를 사용해 구현하시면 됩니다.
