### ISSUE TITLE
로그인 중 앱 종료가 됩니다.

### ISSUE THREAD

**Issue by won-lever** [kakao/kakao_flutter_sdk#122]
kakao_flutter_sdk/Utility.swift:36: Fatal error: Unexpectedly found nil while unwrapping an Optional value

source 
```
    print('카카오 로그인 ');
    try {
      final installed = await kakao.isKakaoTalkInstalled();
      print('카카오 설치 확인 $installed');

      installed
          ? await kakao.UserApi.instance.loginWithKakaoTalk()
          : await kakao.UserApi.instance.loginWithKakaoAccount();
    } catch (e) {
      print('카카오 로그인 실패(sdk열기 실패)   $e');
    }
```

log
flutter: 카카오 로그인
-canOpenURL: failed for URL: "kakaokompassauth://authorize" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
flutter: 카카오 설치 확인 false
kakao_flutter_sdk/Utility.swift:36: Fatal error: Unexpectedly found nil while unwrapping an Optional value
kakao_flutter_sdk/Utility.swift:36: Fatal error: Unexpectedly found nil while unwrapping an Optional value
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x0000000186761cf4 libswiftCore.dylib`_swift_runtime_on_report

url scheme 
KakaoContext.clientId 같은 것도 다 설정을 해줬는데 뭐가 문제 일까요

컴퓨터는 m1 맥미니
빌드 기기는 iphone 13 pro max 입니다

**Comment by mbkim95** [comment]
안녕하세요

iOS 환경에서 CFBundleShortVersionString는 앱 버전을 의미하는데, 무슨 이유인지는 모르겠지만 앱 버전 정보가 없는 것 같습니다.

XCode에서 Runner -> General -> Identity에 Version 설정을 해주시면 문제가 해결될 것으로 보여요
