### ISSUE TITLE
README 수정 요청

### ISSUE THREAD

**Issue by sundaynamaste** [kakao/kakao_flutter_sdk#126]
README에 수정해야 할 사항들이 있어 요청드립니다.

1. AccessTokenResponse token = await AuthApi.instance.issueAccessToken(authCode);
위와 같이 되어 있는데, 실제 코드 상으로는 아래와 같이 되어야 합니다.
OAuthToken token = await AuthApi.instance.issueAccessToken(authCode); 

2. TokenManager.instance.setToken(token);
The getter 'instance' isn't defined for the type 'TokenManage' 의 에러가 뜹니다.
abstract class 라 그런 것 같은데, 수정이 필요합니다.

sdk 만들어주셔서 감사하고, readme 를 좀 더 쉽게 써주시면 더욱 감사하겠습니다.

**Comment by mbkim95** [comment]
안녕하세요

제보주신 부분들이 README.md에서 누락됐었네요ㅠㅠ

제보주신 내용은 수정해두겠습니다.

1. ~`AccessTokenResponse token = await AuthApi.instance.issueAccessToken(authCode);`~
    -> `OAuthToken token = await AuthApi.instance.issueAccessToken(authCode);`
2. ~`TokenManager.instance.setToken(token);`~
    -> `TokenManagerProvider.instance.manager.setToken(token);`

참고로 로그인을 구현하실 때 아래와 같이 직접 구현하실 수도 있지만, 해당 코드들이 내부적으로 구현되어있는 `UserApi.instance.loginWithKakaoTalk();` 또는 `UserApi.instance.loginWithKakaoAccount();` 을 사용하시기를 권장드립니다.

감사합니다!

```dart
try {
    String authCode = await AuthCodeClient.instance.request(); // via browser
    // String authCode = await AuthCodeClient.instance.requestWithTalk() // or with KakaoTalk
    OAuthToken token = await AuthApi.instance.issueAccessToken(authCode);
    TokenManagerProvider.instance.manager.setToken(token); // Store access token in TokenManager for future API requests.
  } catch (e) {
    // some error happened during the course of user login... deal with it.
  }
```
