### ISSUE TITLE
kakao sdk 1.0.0 버전 이후 ios import 이슈

### ISSUE THREAD

**Issue by JoengUk** [kakao/kakao_flutter_sdk#130]
안녕하세요.
kakao_flutter_sdk를 유용하게 사용하고 있는 개발자입니다.

저만 그런걸지도 모르지만
현재 KakaoFlutterSdkPlugin.m 파일에서 두번째 줄 #import <kakao_flutter_sdk_common/kakao_flutter_sdk_common-Swift.h>로 빌드 시
'kakao_flutter_sdk_common/kakao_flutter_sdk_common-Swift.h' file not found 오류를 발생하며 빌드 실패가 발생 중입니다.
#import <kakao_flutter_sdk_common-Swift.h> << 해당 코드로 변경 시 문제없이 빌드와 기능 동작하고 있는 상태며 확인 후 변경 부탁드립니다!

감사합니다.

**Comment by mbkim95** [comment]
안녕하세요

말씀주신 이슈에 대해서는 처음 제보받았기도 하고, 재현되지 않아서 조금 더 확인해보고 대응이 필요하다고 판단되면 수정하도록 하겠습니다.

감사합니다!

**Comment by myriky** [comment]
같은 이슈 발생하고 있습니다.

![스크린샷 2022-03-18 오전 10 29 56](https://user-images.githubusercontent.com/581861/158920174-bac29f17-8937-43ef-9fe2-9438ad71b16c.png)

```
kakao_flutter_sdk_user: ^1.0.0
```

```
$flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-arm, locale ko-KR)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.65.2)
```

**Comment by myriky** [comment]
Podfile에 user_frameworks! 를 선언하니 잘 동작합니다. 특정 플러그인 관련하여 해당 구문 주석처리 해서 사용하는 프로젝트들에서 발생하는 문제로 보이네요. 해당 부분 가이드 함께 주시면 좋을 것 같습니다 :)
```
target 'Runner' do
  use_frameworks!
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

https://github.com/flutter/flutter/issues/9694

**Comment by mbkim95** [comment]
@myriky 
이슈가 재현되지 않아서 관련해서 이것저것 시도해보고 있었는데 원인 분석까지 해주셔서 감사합니다ㅠㅠ

가이드 건의주신 부분에 대해서는 내부적으로 검토해보도록 하겠습니다

감사합니다!
