### ISSUE TITLE
kakao navi 목적지 공유 IOS에서 동작을 하지 않습니다.

### ISSUE THREAD

**Issue by Saebyeol98** [kakao/kakao_flutter_sdk#131]
AOS 의 경우는 정상적으로 동작을 하는데 
IOS쪽 Bundle ID 등록도 마쳤습니다.
처음엔 url schemes 에 kakaonavi-sdk 가 빠져있어서 열수 없다고 나오길래 
문서에는 누락된 부분이여서 제가 직접 추가하니 동작을 하는건 확인했습니다.

다만 이제 카카오네비를 호출할 때 name, x, y 값을 인식하지 못하는건지 그냥 카카오네비만 열리고

길찾기 안내가 되지 않습니다. 확인 부탁드립니다.

**Comment by mbkim95** [comment]
안녕하세요

앱 ID와 구현하신 코드 첨부 가능하실까요?

**Comment by Saebyeol98** [comment]
네 안녕하세요 앱 ID는 ID 715213 입니다.
구현부분은 플러터 sdk 가이드라인에 맞춰서 작성했었습니다.

locX가 이제 가이드에서 제공한대로 경도
locY가 이제 가이드에서 제공한대로 위도

를 담아서 호출했고요 item.deviceName에는 목적지 이름이 들어가도록 구현했습니다.

Android OS에서는 정상동작을 하나 IOS에선 카카오네비가 호출이 되고
카카오 네비 앱 안에서 빙글빙글 애니메이션이 몇번돌다가 아무런 반응이 없습니다.

 bool result = await NaviApi.instance.isKakaoNaviInstalled();
                                                            if (result) {
                                                              debugPrint('카카오 네비가 설치되어 있습니다.');
                                                              // 카카오내비 앱으로 목적지 공유하기, WGS84 좌표계 사용
                                                              await NaviApi.instance.shareDestination(
                                                                destination: Location(
                                                                  name: item.deviceName!,
                                                                  x: locX,
                                                                  y: locY,
                                                                ),
                                                                // destination: Location(
                                                                //   name: '카카오 판교오피스',
                                                                //   x: '127.108240',
                                                                //   y: '36.402311',
                                                                // ),
                                                                option: NaviOption(coordType: CoordType.wgs84),
                                                              );
                                                            } else {
                                                              debugPrint('카카오 네비가 설치되어 있지 않습니다. ❌');
                                                              launchBrowserTab(Uri.parse(NaviApi.webNaviInstall));
                                                            }

**Comment by mbkim95** [comment]
첨부해주신 코드와 실제로 사용하신 좌표값으로 직접 구현을 해봤는데 제 환경에서는 문제 없이 동작하네요ㅠㅠ

혹시 사용하신 카카오내비 앱 버전과 ios 버전은 어떻게 되나요?

**Comment by Saebyeol98** [comment]
IOS 는 아이폰 13 pro 15.3.1입니다 카카오내비 앱 내부에서 확인해본 결과 현재 버전 4.0.0 / 최신 3.58.0 으로 나오고 있습니다.

**Comment by mbkim95** [comment]
서버 로그를 확인해봤을 때도 문제되는 부분이 없어보여서 원인 파악이 안되고 있는 상황이네요ㅠㅠ

iOS 카카오내비 최신 버전은 4.0.1로 확인되는데 업데이트 후에 재시도 해보는건 어떨까요?

그리고 이슈 재현 영상 첨부해주시면 해결하는데 조금 더 도움이 될 것 같습니다. 가능하시다면 첨부 부탁드려요

추가로 궁금한 점이 있는데, iOS 환경에서는 어느 장소로 해도 동일하게 이슈가 발생하나요? (ex 카카오 판교 오피스 등)

**Comment by Saebyeol98** [comment]
분명 저번주만해도 4.0.0 이였는데.. 카카오내비 업데이트가 있는줄은 몰랐네요 4.0.1 로 업데이트 하니 제대로 동작하네요 
빠른 답변과 도움을 주셔서 감사합니다! 이슈가 해결되었습니다.
