### ISSUE TITLE
iOS NaviApi 오류

### ISSUE THREAD

**Issue by hismethod** [kakao/kakao_flutter_sdk#134]
안녕하세요. 카카오내비 길안내, 목적지 공유기능 사용중 에러가 발생되어 이슈를 남깁니다.

환경:
iOS버전: 15.3.1
kakao_flutter_sdk: 1.1.0
카카오네비버전 : 4.1.0

내용:
아래코드 실행시 카카오네비로 redirect 된 후 에러 Dialog 출력
기능은 동작하지 않습니다.
참고로 같은코드로 안드로이드는 잘 동작합니다.

다이얼로그 에러메시지: 연결 오류입니다. 서비스 제공측에 문의하시기 바랍니다. (A0010)

```dart
if (isKakaoNaviInstalled) {
  await NaviApi.instance.shareDestination(
    destination: Location(
      name: Uri.decodeComponent(destinationName),
      x: destinationLon.toString(),
      y: destinationLat.toString(),
    ),
    option: NaviOption(coordType: CoordType.wgs84),
  );
}
```

**Comment by mbkim95** [comment]
안녕하세요

앱 ID가 어떻게 되나요? (앱 ID는 [카카오 디벨로퍼스 사이트](https://developers.kakao.com)에서 확인할 수 있는 5~6자리 숫자 값 입니다)

**Comment by hismethod** [comment]
네 앱 아이디는 711648입니다.

**Comment by mbkim95** [comment]
서버 로그를 확인해봤을 때 이번 달에 API를 호출한 기록이 아예 없네요.

혹시 앱 ID가 711648이라고 말씀주신 앱의 이름이 'SOOP: 숲' 이 맞나요?

그리고 가능하시다면 이슈 재현 영상도 첨부해주시면 좋을 것 같습니다.

**Comment by hismethod** [comment]
앗! :@ 이건 제가 실수했네요
네이티브키를 잘못 기입했습니다.. 올바로 기입하니깐 잘 되네요.
그럼 거꾸로, 안드로이드가 되는것은 다른 문제일 수 있겠네요.
일단, 오픈했던 문제는 올바른 네이티브키를 넣으니 잘 작동합니다.
