### ISSUE TITLE
flutter 3.0 업그레이드 이후 에러 발생

### ISSUE THREAD

**Issue by HQHAN** [kakao/kakao_flutter_sdk#136]
아래와 같이 빌드 에러 발생합니다.

kakao_flutter_sdk_common-1.1.0/android/src/main/kotlin/com/kakao/sdk/flutter/KakaoFlutterSdkPlugin.kt: (41, 43): Type mismatch: inferred type is Activity? but Activity was expected

**Comment by mbkim95** [comment]
안녕하세요

현재 kakao_flutter_sdk는 플러터 3.0 대응이 되어있지 않은 상황입니다.

불편을 끼쳐드려 죄송합니다ㅠㅠ

빠른 시일 내에 대응해서 배포하도록 하겠습니다.

감사합니다.

**Comment by mbkim95** [comment]
@HQHAN 

해당 이슈 수정된 1.1.1 버전 배포되었습니다.

제보해주셔서 감사합니다.
