### ISSUE TITLE
AndroidManifest.xml 네이티브 앱 키 추가시 앱 아이콘 없어짐 이슈

### ISSUE THREAD

**Issue by jaemin72** [kakao/kakao_flutter_sdk#138]
<intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                 
                <data android:scheme="kakao${YOUR_NATIVE_APP_KEY}" android:host="oauth"/>
            </intent-filter>

네이티브 앱 키 추가시 휴대폰 앱 아이콘이 사라지고 앱 실행 불가합니다. (빌드는 가능합니다)
원인을 알 수 있을까요?
flutter version 3.0.0입니다.

**Comment by jaemin72** [comment]
<intent-filter android:label="flutter_web_auth">
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              
              <data android:scheme="kakao${YOUR_NATIVE_APP_KEY}" android:host="oauth"/>
          </intent-filter>

**Comment by mbkim95** [comment]
안녕하세요

설정하신 AndroidManifest.xml 파일 공유 부탁드립니다. (앱 키는 ${KAKAO_APP_KEY} 와 같이 수정해서 첨부해주세요)

그리고 앱 실행시 어떤 에러 메시지가 출력되나요?
