### ISSUE TITLE
Kakao Login iOS 토큰 오류

### ISSUE THREAD

**Issue by youngdongSong** [kakao/kakao_flutter_sdk#141]
iOS 에서 await AuthApi.instance.hasToken() 함수 호출 시 아래와 같은 에러가 나타납니다.
안드로이드는 정상 작동합니다.
iOS 에서도 잘 동작하였는데 갑자기 해당 오류가 나타나면서 안되기 시작했습니다.

`[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Invalid or corrupted pad block
#0      PKCS7Padding.padCount (package:pointycastle/paddings/pkcs7.dart:42:7)
#1      PaddedBlockCipherImpl.doFinal (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:112:30)
#2      PaddedBlockCipherImpl.process (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:74:25)
#3      AES.decrypt (package:encrypt/src/algorithms/aes.dart:63:22)
#4      Encrypter.decryptBytes (package:encrypt/src/encrypter.dart:25:17)
#5      Encrypter.decrypt (package:encrypt/src/encrypter.dart:31:17)
#6      AESCipher.decrypt (package:kakao_flutter_sdk_common/src/aes_cipher.dart:68:23)
#7      DefaultTokenManager.getToken (package:kakao_flutter_sdk_auth/src/token_manager.dart:102:54)`

아래는 flutter doctor 내용입니다.
`/Users/jines-yeonguso/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale ko-KR)
    • Flutter version 3.0.2 at /Users/jines-yeonguso/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (13 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/jines-yeonguso/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.2)
    • VS Code at /Users/jines-yeonguso/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • 송영동의 iPhone (mobile) • 00008110-000219C601E1801E • ios            • iOS 15.5 19F77
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0`

**Comment by mbkim95** [comment]
안녕하세요

이슈에 대해서 파악하고 있는데 재현이 되지 않고, 코드 상으로도 문제되는 부분을 찾지 못해서 원인을 파악하지 못한 상황입니다.

혹시 이슈 발생한 계정 이메일과 앱 id를 알려주실 수 있을까요?

추가로 iOS 환경에서 잘 동작하다가 갑자기 안됐다고 하셨는데, 에러가 발생하기 전에 별도의 작업을 하지는 않았는지도 궁금합니다. 
ex) 라이브러리 버전 업, 코드 수정 등등

**Comment by youngdongSong** [comment]
안녕하세요
 
APP ID : 355954
 
계정 이메일은 카카오 developers 에 등록된 계정을 말씀하시는 건가요?
developers 계정 : ***@***.***
 
그게 아니라면 카카오 로그인 화면이 넘어가기도 전에 해당 오류가 나타나 동작이 안되서 따로 계정 이메일을 알려드릴 수 없을 것 같습니다.
 
잘 동작하던 버전의 kakao 라이브러리 버전과 같으며 코드 수정을 하였지만 kakao 로그인과 연관이 전혀 없는 부분입니다. (같은 소스로 빌드한  안드로이드는 정상 동작합니다.)
불과 며칠 전만해도 잘 동작하였습니다.
 
-----Original Message-----

**Comment by mbkim95** [comment]
암호화된 토큰을 복호화하는 과정에서 간헐적으로 에러가 발생하는 것으로 보이는데, 정확한 원인은 파악하기가 어려울 것 같습니다. 

대신에 앱 동작 중에 에러가 발생하는 것보다는 재 로그인을 통해 토큰을 재발급받는 것이 사용성에 있어서 더 낫다고 판단해서 토큰 복호화에 실패한 경우 이전에 저장된 토큰을 삭제하도록 수정했고 다음 버전 배포에 포함될 예정입니다.

대응이 많이 늦어졌지만 참고 부탁드리겠습니다.

**Comment by mbkim95** [comment]
@youngdongSong  안녕하세요. 이메일로 댓글 달아주신 것으로 보이는데 첨부해주신 이메일이 마스킹처리되어 보이지 않네요ㅠㅠ

이전에 제가 댓글을 달았을 때는 특정 토큰 값이 복호화할 때 문제가 되는 것인지 확인해보려고 로그인을 시도한 계정 정보를 요청을 드렸었습니다. (로그인 계정을 알면 토큰 값 추적이 가능하기 때문에 확인된 토큰 값으로 재현해보려 했습니다)
하지만 내부적으로 확인해본 결과 특정 토큰 값이 문제가 되는 것이 아닌 것을 확인했기 때문에 현재로서는 추가로 이메일을 알려주셔도 이슈 해결에 크게 도움이 되지는 않을 것 같아요

이 외에는 특별하게 짐작가는 부분도 없고, 여러 번 에러를 재현해보려 했지만 에러가 재현되지 않아서 정확한 원인은 파악하지 못했습니다.
원인을 파악해서 버그를 수정하는 것이 가장 좋겠지만 딱히 해결법이 보이지 않는 상황입니다. 이러한 상황에서 앱 동작 중에 에러가 발생하는 것보다는 재 로그인을 통해 토큰을 재발급받는 것이 사용성에 있어서 더 낫다고 판단해서 1.3.0 베타 버전부터는 복호화에 실패한 경우 예외를 던지는 것이 아니라 sdk에 저장된 토큰을 제거하도록 수정되었습니다. 

제보주신 이슈를 직접적으로 해결하지 못하고 우회해서 처리하게 된 점 양해 부탁드리고 가급적이면 1.3.0-beta.4 버전 사용하시기를 권장드리겠습니다.

이슈 제보 주셔서 감사합니다.
