### ISSUE TITLE
1.2.0 build 시 UniqueKey() 에러 발생

### ISSUE THREAD

**Issue by YoonKyeongho** [kakao/kakao_flutter_sdk#142]
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (2 months ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

안녕하세요. 위 환경에서 빌드시 아래와 같은 에러가 발생합니다.

../../../.pub-cache/hosted/pub.dartlang.org/kakao_flutter_sdk_auth-1.2.0/lib/src/auth_code.dart:205:44: Error: Method not found: 'UniqueKey'.
        .encode(sha512.convert(utf8.encode(UniqueKey().toString())).bytes);

확인부탁드립니다.

**Comment by mbkim95** [comment]
안녕하세요

이슈가 재현되어 확인해본 결과 Flutter3.0 부터 `UniqueKey`을 사용하기 위해 import 하는 패키지 경로가 달라졌기 때문인 것으로 보입니다.

1.2.0 버전을 배포하기 전에 Flutter3.0 기준에서 warning이 뜨던 코드들을 정리하는 작업을 했었는데요, 그 때 Flutter 2.x.x 버전에서 `UniqueKey`를 사용하기 위해 import 하는 패키지를 제거해서 이슈가 발생했네요ㅠㅠ

해당 이슈 수정해서 이번주 중으로 1.2.1 버전 배포하도록 하겠습니다.

제보주셔서 감사합니다

**Comment by YoonKyeongho** [comment]
확인 감사합니다.

**Comment by juhojang** [comment]
안녕하세요. 저도 똑같이 에러가 나서 확인한 결과,
 UniqueKey() 메소드는 'package:flutter/material.dart'안에 들어있는 메소드입니다. 
그러므로 kakao_flutter_sdk_auth-1.2.0/lib/src/auth_code.dart에 import 'package:flutter/material.dart';를 추가하면 정상작동합니다!

**Comment by mbkim95** [comment]
해당 이슈 수정된 1.2.1 버전 배포되었습니다.

다시 한번 제보주셔서 감사합니다!
