### ISSUE TITLE
Symbol not found: _$s14KakaoSDKCommon11SessionTypeO3ApiyA2CmFWC 에러

### ISSUE THREAD

**Issue by Gyusik-Choi** [kakao/kakao_flutter_sdk#143]
Xcode 에서 빌드 성공 후에 해당 에러가 발생하여 앱을 실행시킬 수 없습니다.

안드로이드 스튜디오와 Xcode 에서 Pods 의 Kakao SDK 관련 항목들을 삭제한 후에 pod install 을 하고 Xcode 에서 빌드하는 과정을 반복하다 보면 해결이 된 경우가 있긴 합니다만 정확한 문제 발생 원인과 해결 방법을 모르겠습니다. flutter doctor 를 실행해도 이슈가 없습니다.

아래는 에러 로그 입니다.

dyld[2985]: Symbol not found: _$s14KakaoSDKCommon11SessionTypeO3ApiyA2CmFWC
  Referenced from: /Users/jinhak/Library/Developer/CoreSimulator/Devices/073A9D3A-94E7-4D1C-B050-0C71091DC665/data/Containers/Bundle/Application/22038DB8-D8DC-4F20-8A73-10AA144FB63B/Runner.app/Frameworks/KakaoSDKFriend.framework/KakaoSDKFriend
  Expected in: /Users/jinhak/Library/Developer/CoreSimulator/Devices/073A9D3A-94E7-4D1C-B050-0C71091DC665/data/Containers/Bundle/Application/22038DB8-D8DC-4F20-8A73-10AA144FB63B/Runner.app/Frameworks/KakaoSDKCommon.framework/KakaoSDKCommon
Symbol not found: _$s14KakaoSDKCommon11SessionTypeO3ApiyA2CmFWC
  Referenced from: /Users/jinhak/Library/Developer/CoreSimulator/Devices/073A9D3A-94E7-4D1C-B050-0C71091DC665/data/Containers/Bundle/Application/22038DB8-D8DC-4F20-8A73-10AA144FB63B/Runner.app/Frameworks/KakaoSDKFriend.framework/KakaoSDKFriend
  Expected in: /Users/jinhak/Library/Developer/CoreSimulator/Devices/073A9D3A-94E7-4D1C-B050-0C71091DC665/data/Containers/Bundle/Application/22038DB8-D8DC-4F20-8A73-10AA144FB63B/Runner.app/Frameworks/KakaoSDKCommon.framework/KakaoSDKCommon
(lldb)

**Comment by liemeon** [comment]
Podfile 설정 확인

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end

**Comment by mbkim95** [comment]
안녕하세요

답변이 조금 늦었네요ㅠㅠ

첨부해주신 에러 로그를 보았을 때는 iOS 버전의 카카오 SDK를 같이 추가하신걸로 보이는데요, kakao_flutter_sdk를 사용하실 때는 iOS용 카카오 SDK를 추가하실 필요가 없습니다.

해당 SDK를 제거하신 후 빌드하시면 에러가 발생하지 않을 것으로 보여요
