### ISSUE TITLE
ShareClient.instance.shareDefault 오류

### ISSUE THREAD

**Issue by cyb9701** [kakao/kakao_flutter_sdk#144]
카카오톡 공유하기 기능을 이용하기 위해서 TextTemplate 을 먼저 지정을 해주었습니다.
그리고 button 설정을 위해서 buttons 안에 새로운 버튼을 추가를 해주었습니다.

기본으로 설정하는 link의 주소와 버튼의 link 주소가 다르지만 버튼을 클릭을 해도 컨텐츠 클릭 시 이동할 링크가 실행되는 오류가 있습니다.
확인 부탁드립니다.

```
final TextTemplate defaultText = TextTemplate(
      text: _text,
      link: Link(
        webUrl: Uri.parse('https://link.billyo.co.kr/target?id=open'),
        mobileWebUrl: Uri.parse('https://link.billyo.co.kr/target?id=open'),
      ),
      buttons: [
        Button(
          title: '위치보기',
          link: Link(
            webUrl: Uri.parse('https://map.kakao.com'),
            mobileWebUrl: Uri.parse('https://map.kakao.com'),
          ),
        ),
      ],
    );
```

**Comment by mbkim95** [comment]
안녕하세요

제보주신 내용은 오류가 아니고 플랫폼별로  동작하는 방식이 다르기 때문에 발생하는 현상입니다. 

관련해서 [가이드](https://developers.kakao.com/docs/latest/ko/message/message-template#link) 참고 부탁드리겠습니다.
