### ISSUE TITLE
kakaonavi sdk 연동 오류 (Android에서만 발생)

### ISSUE THREAD

**Issue by bfnc-hsh** [kakao/kakao_flutter_sdk#147]
kakao developer ID : 781034
테스트기기 : SM A516N
sdk 버전 : kakao_flutter_sdk_navi: ^1.2.2

[✓] Flutter (Channel stable, 3.3.0, on macOS 12.6 21G115 darwin-arm, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

'카카오내비 인증에 실패하였습니다.' 
메세지와 함께 안드로이드에서 카카오내비가 실행 되지 않습니다.
추가 scheme를 추가하는건 아닌거 같은데 KakaoSdk log를 켜도 별도 정보가 없는거같아서
문제를 해결하지 못하고 있습니다.
아이폰에서는 정상동작합니다.

확인해주시면 감사하겠습니다.
수고하세요.

**Comment by mbkim95** [comment]
안녕하세요

만약 카카오내비 앱이 최신 버전이 아니라면 최신 버전으로 업데이트 후에 다시 시도 부탁드리겠습니다.

에러가 재현되지 않아서 정확한 원인을 파악하지 못하고 있는데요, 구현하신 코드와 에러 발생한 영상 첨부해주시면 원인 파악에 도움이 될 것 같습니다.

**Comment by bfnc-hsh** [comment]
카카오내비는 플레이스토어에서 새로 설치해서 계속 테스트하고 있었습니다.
버전은 4.6.3이네요.

영상링크입니다.
**https://youtube.com/shorts/pwEp8pSd7DE?feature=share**

아래는 카카오 내비 실행 하게 하는 코드입니다.
`if (await NaviApi.instance.isKakaoNaviInstalled()) {
      // 카카오내비 앱으로 목적지 공유하기 - WGS84 - 경유지 추가
      Future.delayed(const Duration(milliseconds: 300), () {
        var arrival = points.last;
        NaviApi.instance.navigate(
          option: NaviOption(
            coordType: CoordType.wgs84,
            rpOption: RpOption.shortest,
            vehicleType: VehicleType.twoWheel,
          ),
          destination: Location(
            name: arrival.name,
            x: arrival.x.toString(),
            y: arrival.y.toString(),
          ),
        );
      });
    } else {
      // 카카오내비 설치 페이지로 이동
      launchBrowserTab(Uri.parse(NaviApi.webNaviInstall));
    }`

**Comment by mbkim95** [comment]
카카오내비 쪽과 연락해서 확인을 해봤는데요, 카카오내비에 보내지는 url 확인이 필요할 것 같다고 하네요
url에는 앱 키와 같은 정보가 같이 포함되기 때문에 [카카오 데브톡](https://devtalk.kakao.com)에서 tony.mb 계정에게 개인 메시지로 보내주시면 감사하겠습니다

조금 번거로우시겠지만 아래와 같이 설정하신 후 출력되는 로그 값을 전달 부탁드립니다.

1. 프로젝트의 android를 Android Studio로 열기
<img width="720" alt="스크린샷 2022-09-21 오후 12 23 27" src="https://user-images.githubusercontent.com/44355413/191407734-98c54840-43c6-425a-bdba-24713def79c3.png">

2. KakaoFlutterSdkPlugin.kt 파일 열기
<img width="477" alt="image" src="https://user-images.githubusercontent.com/44355413/191408004-87f71f06-8a80-46a5-812a-45dc4ac46ede.png">

3. 128번 라인에 `println("SdkLog: $uri")` 코드 추가
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/44355413/191408487-42d008c5-058b-4191-ad55-4d981919978f.png">

4. 로그 확인
<img width="1841" alt="스크린샷 2022-09-21 오후 12 37 57" src="https://user-images.githubusercontent.com/44355413/191409230-5c1f73f2-ea59-4960-8cf8-e420ddf37d23.png">

**Comment by bfnc-hsh** [comment]
로그값 전달드립니다.
감사합니다 :)

```
SdkLog: kakaonavi-sdk://navigate?param=%7B%22destination%22%3A%7B%22name%22%3A%22(04779)%20(%EC%84%9C%EC%9A%B8%20%EC%84%B1%EB%8F%99%EA%B5%AC%20%EC%84%B1%EC%88%98%EC%9D%BC%EB%A1%9C%201)%20%20(%EC%83%81%EC%84%B8%EC%A3%BC%EC%86%8C)%20%22%2C%22x%22%3A%22127.052227%22%2C%22y%22%3A%2237.509554%22%7D%2C%22option%22%3A%7B%22coord_type%22%3A%22wgs84%22%2C%22vehicle_type%22%3A%227%22%2C%22rpoption%22%3A%223%22%7D%2C%22via_list%22%3A%5B%5D%7D&apiver=1.0&appkey=6c2c4574b902c03e1c718a4cd2abf6ae&extras=%7B%22KA%22%3A%22sdk%2F1.2.2%20sdk_type%2Fflutter%20os%2Fandroid-31%20lang%2Fko-KR%20origin%2FhmVjXcHKHCT2xgLpGunWsIr4Zkw%3D%20device%2FSM-A516N%20android_pkg%2Fcom.mixd.ar%20app_ver%2F1.0.0%22%2C%22appPkg%22%3A%22com.mixd.ar%22%2C%22keyHash%22%3A%22hmVjXcHKHCT2xgLpGunWsIr4Zkw%3D%22%7D
```

**Comment by mbkim95** [comment]
@bfnc-hsh 앱 키 등의 민감 정보가 포함되어있어서 코멘트주신 내용은 삭제한점 양해 부탁드립니다.

**Comment by mbkim95** [comment]
@bfnc-hsh 카카오내비 측에서 확인한 결과 [카카오 디벨로퍼스](https://developers.kakao.com)에 등록된 안드로이드 키 해시 값과 실제 요청 시 키 해시 값이 달라서 에러가 발생했다고 하네요.

실제로 확인해보니 키 해시가 등록되어있지 않네요. [가이드](https://developers.kakao.com/docs/latest/ko/getting-started/app#platform) 참고해서 키 해시를 등록하시면 정상 동작 할 것 같습니다.

현재 요청 들어오고 있는 값은 hmVj************************** 입니다.

참고하셔서 등록 후 확인 부탁드려요

**Comment by bfnc-hsh** [comment]
확인해주셔서 감사합니다.
가이드 해주신대로 등록하고 다시 테스트 해보겠습니다.
