### ISSUE TITLE
'kakao_flutter_sdk_common/kakao_flutter_sdk_common-Swift.h' file not found

### ISSUE THREAD

**Issue by songyiYu** [kakao/kakao_flutter_sdk#149]
iOS 시뮬레이터 빌드시
'kakao_flutter_sdk_common/kakao_flutter_sdk_common-Swift.h' file not found
오류가 납니다.

Podfile에 use_frameworks! 를 붙이면 되는건가요?
현재 use_frameworks! 를 붙이면 다른 라이브러리에서 오류가 나서 use_modular_headers! 로 대신하고 있는데
use_frameworks! 붙이는 방법 말고 다른 방법이 있을까요?
![스크린샷 2022-09-20 오후 3 15 33](https://user-images.githubusercontent.com/9947963/191181683-6ba096d4-19f0-4b6b-9573-3f8e14288b29.png)

**Comment by mbkim95** [comment]
안녕하세요 kakao_flutter_sdk를 사용하려면 Podfile에 use_frameworks!와 use_modular_headers! 선언이 필요한데요, 이는 플러터 프로젝트를 생성하면 기본적으로 선언되어있는 설정입니다.

use_frameworks! 를 붙였을 때 에러가 발생하는 라이브러리에 대한 정보 알려주시면 관련해서 확인해보겠습니다.

**Comment by mbkim95** [comment]
```c
#if __has_include(<kakao_flutter_sdk_common/kakao_flutter_sdk_common-Swift.h>)
#import <kakao_flutter_sdk_common/kakao_flutter_sdk_common-Swift.h>
#else
// Support project import fallback if the generated compatibility header
// is not copied when this plugin is created as a library.
// https://forums.swift.org/t/swift-static-libraries-dont-copy-generated-objective-c-header/19816
#import "kakao_flutter_sdk_common-Swift.h"
#endif
```

해당 부분에 위의 코드를 추가해서 use_frameworks! 옵션없이도 사용할 수 없도록 수정했고, 다음 버전 배포에 포함시켜서 배포하도록 하겠습니다.

이슈 제보주셔서 감사합니다.

**Comment by mbkim95** [comment]
해당 이슈 수정된 kakao_flutter_sdk 1.3.0-beta.3 버전 배포되었습니다. 제보주셔서 다시 한번 감사합니다.
