### ISSUE TITLE
대체 AuthCodeClient.instance.authorizeWithTalk는 어따 팔아먹고 AuthCodeClient.instance.requestWithTalk 만 남은 거죠?

### ISSUE THREAD

**Issue by PresentFutures9653** [kakao/kakao_flutter_sdk#150]
제목이 곧 내용

**Comment by mbkim95** [comment]
안녕하세요

플러터 웹 지원하는 kakao_flutter_sdk 1.3.0-beta.3 버전이 릴리즈되면서 sdk 내부적으로 사용되던 `AuthCodeClient#requestWithTalk` 이 `AuthCodeClient#authorizeWithTalk` 으로 변경되었습니다. 

플러터 웹에서 [리다이렉트 방식 로그인](https://developers.kakao.com/docs/latest/ko/kakaologin/flutter#before-you-begin-process)을 구현하는 경우가 아니라면 해당 메서드를 직접 호출하는 것은 권장하지 않습니다.

이 점 참고 부탁드리고, 앱 개발을 하시는 경우라면 `UserApi#loginWithKakaoTalk` 혹은 `UserApi#loginWithKakaoAccount`를 사용해서 로그인 구현하시기를 권장드립니다.
