### ISSUE TITLE
Kakao Map 은 지원할 계획이 없는건가요?

### ISSUE THREAD

**Issue by gblue1223** [kakao/kakao_flutter_sdk#154]
navi 는 있지만 map 이 안보여서 질문 남깁니다.

**Comment by gblue1223** [comment]
웁스 안타깝네요 ㅠ

**Comment by hieutv-picon** [comment]
there is still no plan for kakao map?

**Comment by mbkim95** [comment]
@hieutv-picon I'm not in charge of the Kakao Map SDK, so I can't answer your question about plan. 

I suggest you contact to the Kakao Map SDK developers via [DevTalk](https://devtalk.kakao.com/c/map-api/101).
