### ISSUE TITLE
로깅관련해서 질문이 있습니다!!

### ISSUE THREAD

**Issue by yelloze-xyz** [kakao/kakao_flutter_sdk#156]
안녕하세요~! SDK를 만들어주셔서 감사하게 이용하고 있습니다~!

https://github.com/kakao/kakao_flutter_sdk/blob/53b47915140afdc3b28a50764b700b6aecd0a147/packages/kakao_flutter_sdk_common/lib/src/sdk_log.dart#L70-L72

```
  KakaoSdk.init(
    nativeAppKey: "",
    javaScriptAppKey: "",
    loggingEnabled: false,
  );
```

윗 소스를 보면 SDK를 초기화 시킬 때 전달하는 `loggingEnabled`와 관련 없이 `kDebugMode`로 로그를 표시해주고 있는데, 이유가 있을까요? 로그인을 이용하고 있는데 꽤나 많은 로그들이 쌓이더라구요. sdk를 초기화 시킬 때 전달되는 값으로 로깅의 표시 방법을 정해야 하지 않을까요?!

**Comment by mbkim95** [comment]
안녕하세요

우선 kakao_flutter_sdk에 관심 가져주셔서 감사합니다!

`loggingEnabled` 값은 SDK 내부적으로 로그를 저장할지 말지에 대한 옵션으로 해당 옵션이 활성화되어 있다면 `SdkLog.logs`를 통해서 디버그 모드, 릴리즈 모드와 상관없이 로그를 확인할 수 있도록 구현되어있고, 말씀하신 것처럼 `logginEnabled` 값과 별개로 디버그 모드에서 콘솔 로그는 출력되도록 구현되어있습니다.

디버그 모드는 개발 단계의 상태이므로 SDK를 사용하는 개발자들이 로그를 통해 SDK 동작을 쉽게 파악할 수 있게 의도적으로 콘솔 로그가 출력하도록 구현했는데요, 의견주신 것처럼 경우에 따라서는 디버그 모드에서도 로그가 출력되는 것을 원하지 않을 수 있을 것 같습니다.

의견 주셔서  다시 한 번 감사드리고, 주신 의견에 대해서는 내부적으로 긍정적으로 검토해보도록 하겠습니다.

**Comment by yelloze-xyz** [comment]
빠른 답변 감사합니다~! 콘솔에서 찍히는거 말고도 확인하는 방법이 있었군요..! 궁금증이 해결되어 해당 질문은 닫도록 하겠습니다~!

**Comment by mbkim95** [comment]
@yelloze-xyz 안녕하세요 의견 주신 내용 반영해서 디버그 모드이고 loggingEnabled가 true일 때만 콘솔 로그가 찍히도록 수정해서 1.3.0 버전 배포 완료했습니다.
의견 주셔서 감사합니다!
