### ISSUE TITLE
[Question] kakao_flutter_sdk_common 의 dependencies 에 있는 package_info_plus의 버전을 좀 올려주시면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by sundaynamaste** [kakao/kakao_flutter_sdk#158]
### 문의 사항 (Question)

package_info_plus: ^3.0.2 까지 출시되었네요.
버전이 낮아 다른 패키지들과 충돌이 나서요.

**Comment by mbkim95** [comment]
안녕하세요

제안해주신 내용 내부적으로 검토해보고 다음 배포에 반영하도록 하겠습니다.

감사합니다!

**Comment by mbkim95** [comment]
@sundaynamaste 내부적으로 검토 후 package_info_plus 패키지 의존성을 제거한 1.3.0 버전 배포 완료되었습니다.
제보주셔서 감사합니다.
