### ISSUE TITLE
[Question] 카카오 내비 활성화 유무를 알 수 있을까요?

### ISSUE THREAD

**Issue by 217wjs** [kakao/kakao_flutter_sdk#163]
### 문의 사항 (Question)

카카오 내비 활성화 유무를 알 수 있을까요?
카카오 내비 예외처리를 하고싶은데 카카오 내비 인증에 실패했다거나 했을때 예외를 던지지 않아서 활성화 유무를 알 수가 없습니다.

**Comment by mbkim95** [comment]
안녕하세요

아쉽게도 Android, iOS 디바이스에서 카카오 내비 앱 설치 유무 확인은 가능하지만 로그인 유무 상태에 대해서는 SDK에서 확인할 수 없는 점 양해부탁드리겠습니다.
