### ISSUE TITLE
[Question] authroizeWithNewScopes method

### ISSUE THREAD

**Issue by Coaspe** [kakao/kakao_flutter_sdk#165]
### 문의 사항 (Question)

기능적으로는 문제가 없으나, 다른 이유가 있는지 궁금해서 질문드립니다!

[`authroizeWithNewScopes`](https://github.com/kakao/kakao_flutter_sdk/blob/f4ce9f85ff8f3ac74e16d5828fdc3c935432919f/packages/kakao_flutter_sdk_auth/lib/src/auth_code.dart#L135) 메소드가 반환하는 [`authorize`](https://github.com/kakao/kakao_flutter_sdk/blob/f4ce9f85ff8f3ac74e16d5828fdc3c935432919f/packages/kakao_flutter_sdk_auth/lib/src/auth_code.dart#L145) 메소드 호출에 `await` 키워드를 추가하지 않으면,
`authroizeWithNewScopes` 메소드의 `catch` 문이 작동하지 않는데 `await` 키워드를 추가하지 않은 이유가 있나요?

**Comment by mbkim95** [comment]
안녕하세요

`await` 는 코드 리팩토링 과정에서 단순 실수로 인해 빠진 것으로 보이고, `catch` 문에서는 예외를 다시 던져주고만 있었기 때문에 기능상 이슈가 없었습니다.

정상 동작하는 경우에는 큰 차이가 없지만 예외가 발생한 경우를 고려했을 때, `await` 키워드를 붙였을 때 스택 트레이스가 더 명확해지기 때문에 누락된 `await` 키워드는 추가하는 것이 좋을 것으로 보이네요.

kakao_flutter_sdk에 관심가져주셔서 감사드립니다!
