### ISSUE TITLE
[Bug] ios universal 링크를 못 가져오는 이슈

### ISSUE THREAD

**Issue by monolith-kyeonghun** [kakao/kakao_flutter_sdk#169]
### 이슈 설명 (Issue description)

ios 에서 Flutter 카카오 SDK를 추가하면

앱이 완전히 종료된 상태에서 딥 링크를 통하여 앱을 실행했을때

universal link를 가져오지 못하는 이슈가 있습니다.

### 앱 ID (App ID)

231277

### 플랫폼 (Platform)

IOS 16

### 디바이스 (Device)

iPhone 12 mini

### Version

1.4.0

### Flutter SDK

3.7.3

### 재현 방법 (Steps to reproduce)

1. firebase dynamic 링크 추가

2. 앱 완전 종료 후 링크를 통하여 앱 실행 (링크 정보 얻기 성공)

3. Flutter 카카오 SDK 추가

4. 앱 완전 종료 후 링크를 통하여 앱 실행 (링크 정보 얻기 실패)

### 코드 샘플 (Code Sample)

`final PendingDynamicLinkData? initialLink = await FirebaseDynamicLinks.instance.getInitialLink();`

### Logs

```shell
-
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.0 22A380 darwin-arm64, locale ko-KR)
    • Flutter version 3.7.3 on channel stable at /Users/kyeonghun/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (2 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/kyeonghun/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 71.2.6
    • Dart plugin version 223.8214.16

[✓] Connected device (3 available)
    • Kyeonghun’s iPhone (mobile) • 00008101-000870813AF8001E • ios            • iOS 16.1.1 20B101
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by mbkim95** [comment]
안녕하세요

답변이 조금 늦었습니다ㅠㅠ

해당 이슈에 대해서 확인해봤는데 1.4.0 버전에서 [카카오 커스텀 URL 수신 기능](https://developers.kakao.com/docs/latest/ko/getting-started/sdk-flutter#info-scheme-get)이 추가되면서 발생한 이슈인 것으로 파악됩니다.

이슈 원인은 kakao_flutter_sdk 내부에 구현된 application(_:didFinishLaunchingWithOptions:) 메소드에서 카카오 커스텀 URL이 아닌 경우(카카오SDK에서 처리할 수 있는 커스텀 스킴이 아닌 경우) false를 반환함으로써 파이어베이스까지 url이 전달되지 않는 것으로 보입니다.

해당 내용 수정해서 배포하기에 앞서 테스트가 가능하시다면 SwiftKakaoFlutterSdkPlugin.swift 파일의 249번 라인 제거, 251번 라인의 false를 true로 수정했을 때 현재 개발환경에서 정상 동작하는지 테스트 부탁드리겠습니다. (kakao_flutter_sdk 1.4.0 버전 이상)

SwiftKakaoFlutterSdkPlugin.swift 파일은 안드로이드 스튜디오 기준으로 아래의 경로에서 찾을 수 있습니다

<img src="https://devtalk.kakao.com/uploads/default/original/3X/e/f/efddcbf8b03e8f66506833f23871ae59cf98ce73.png" width=50%/>

**Comment by monolith-kyeonghun** [comment]
말씀해주신대로 수정 후 테스트결과 정상 동작함을 확인했습니다.

**Comment by mbkim95** [comment]
@monolith-kyeonghun
안녕하세요

제보주신 내용 수정된 1.4.2 버전 배포되어 해당 이슈는 닫도록 하겠습니다.

이슈 제보주셔서 감사합니다!
