### ISSUE TITLE
[Question] kakao_flutter_sdk_talk 패키지의 dio 의 상위 버전 지원 가능할까요? 

### ISSUE THREAD

**Issue by shings9202** [kakao/kakao_flutter_sdk#171]
### 문의 사항 (Question)

 pretty_dio_logger 패키지 사이에서 dio 버전 충돌이 발생하는데 
 dio : 5.0.1 으로 버전 상승이 가능할까요?

**Comment by mbkim95** [comment]
안녕하세요

kakao_flutter_sdk는 현재 min dart sdk 버전은 2.14으로 유지하고 있습니다. 그런데 dio 5.0.0 버전부터 min dart sdk 버전이 2.15이 되어서 dio 5.0.0 이상 버전을 사용하게 된다면 kakao_flutter_sdk의 min dart sdk 버전을 올려야할 것으로 보입니다. 하지만 아직 kakao_flutter_sdk의 min dart sdk 버전을 올릴 계획이 없기 때문에 추후에 min dart sdk 버전을 2.15 이상으로 올리게된다면 dio 5.0.0 이상 버전의 업데이트를 고려해볼 수 있을 것 같습니다.

또한 kakao_flutter_sdk에서 dio의 최신 버전인 5.0.1 버전을 사용하게 된다면 transitive dependency로 인해 kakao_flutter_sdk를 사용하는 앱들에까지 영향이 갈 수 있기 때문에 아직은 해당 패키지의 최신 버전을 도입할 계획이 없는 점 참고 부탁드립니다.

조금 번거로우시더라도 [dependency_overrides 관련 가이드](https://dart.dev/tools/pub/dependencies#dependency-overrides) 참고하셔서 패키지 충돌을 피해서 사용하시는 것이 좋을 것 같습니다.

**Comment by shings9202** [comment]
추후 sdk 업데이트를 기대하겠습니다.
답변 감사합니다.
