### ISSUE TITLE
[Question] dio 5버전 호환 문의

### ISSUE THREAD

**Issue by ddooyn** [kakao/kakao_flutter_sdk#176]
### 문의 사항 (Question)

안녕하세요. dio 5버전 호환 때문에 문의드립니다.

관련 문의의 [3월 8일 답변](https://github.com/kakao/kakao_flutter_sdk/issues/171#issuecomment-1459652693) 과 [4월 21일 답변](https://devtalk.kakao.com/t/dio-5-0-0/129018)을 통해
transitive dependency 문제로 아직은 dio 5.0.0버전 이상을 지원하지 않는 것임을 이해했습니다.

제 경우, stream-chat-flutter 라이브러리를 최신화하는 과정에서 dio 버전 업그레이드를 하게 되었는데요. (5.1.1입니다)
`kakao_flutter_sdk_user`를 사용해 카카오 로그인 기능을 붙이는 과정에서
앞서 제안해 주신 Dependency overrides 방법으로는 해결이 되지 않아 이슈를 올리게 되었습니다.

![image](https://github.com/kakao/kakao_flutter_sdk/assets/84499458/6b2e7c46-f1b5-4e72-9fd2-ddc0f70a466d)
https://github.com/GetStream/stream-chat-flutter/blob/ee9d35b62d8a25589e0a515ebd16791c2d6fa40d/packages/stream_chat/lib/src/core/http/stream_http_client.dart#L33

혹시 관련해서 아직 업데이트 계획은 없으실까요?

**Comment by mbkim95** [comment]
안녕하세요

dio 5.0.0 버전이 배포된지 어느정도 시간이 지났다고 판단해 최근에 [dio 5.x.x 버전으로 마이그레이션 작업](https://github.com/kakao/kakao_flutter_sdk/commit/220564943ea459d26835118477ce93cbc0c21b3d)을 진행했습니다.

아직 정확한 배포 날짜가 정해지지는 않았지만 다음 배포에 수정 내용 반영될 예정입니다.

이 점 참고 부탁드리고 kakao_flutter_sdk에 관심 가져주셔서 감사합니다

**Comment by ddooyn** [comment]
@mbkim95 답변 감사드립니다! 👍

**Comment by mbkim95** [comment]
@ddooyn dio 5.0.3 버전 적용된 kakao_flutter_sdk 1.4.3 버전 배포되었습니다
