### ISSUE TITLE
안드로이드에서 어플 개발 중 "동의하고 계속하기" 버튼을 클릭하면 다음으로 넘어가지 않습니다.

### ISSUE THREAD

**Issue by alexTw84** [kakao/kakao_flutter_sdk#178]
안녕하세요.
카카오 로그인 구현 중 문제가 생겨 문의 드립니다.
카카오톡 로그인을 사용하지 않는다는 전제 하에 개발 중인데
로그인 시 이메일과 비밀번호 입력 후 나오는 동의하기 화면에서 "동의하고 계속하기" 버튼을 눌러도
다음으로 진행 되지 않습니다.

설정은 아래와 같습니다.

------------------ propertiex
KAKAO_REDIRECTION_SCHEME="kakao66bd~~~~~~~~~~~~~~"

-----------------gradle.build
manifestPlaceholders["KAKAO_REDIRECTION_SCHEME"] = properties.getProperty("KAKAO_REDIRECTION_SCHEME")

implementation "com.kakao.sdk:v2-all:2.13.0"
implementation "com.kakao.sdk:v2-user:2.13.0"

----------------- AndroidManifest.xml

      <activity
          android:name="com.kakao.sdk.auth.AuthCodeHandlerActivity"
          android:exported="true">
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data
                  android:host="oauth"
                  android:scheme="${KAKAO_REDIRECTION_SCHEME}" />
          </intent-filter>
      </activity>

**Comment by mbkim95** [comment]
안녕하세요

말씀하신 내용과 첨부해주신 설정들을 확인했을 때 Android용 카카오SDK를 사용하시는 것 같습니다.

해당 Github은 Flutter용 카카오SDK라서 Android용 카카오SDK에 대한 문의는 [데브톡](https://devtalk.kakao.com/)으로 문의 부탁드립니다.
