### ISSUE TITLE
[Bug] 안드로이드 컴파일시 에러가 발생합니다.

### ISSUE THREAD

**Issue by blueddarker** [kakao/kakao_flutter_sdk#179]
### 이슈 설명 (Issue description)

안드로이드 컴파일시 아래와 같은 에러가 발생합니다.

android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:99: error: package com.kakao.sdk.flutter does not exist
<img width="1130" alt="스크린샷 2023-05-30 오후 5 40 21" src="https://github.com/kakao/kakao_flutter_sdk/assets/7962153/24392974-a6a7-4a8a-8446-4eeb660cd760">

### 앱 ID (App ID)

755326

### 플랫폼 (Platform)

Android SDK version 32.0.0

### 디바이스 (Device)

Galaxy Z Fold3 

### Version

1.4.3

### Flutter SDK

3.10.1

### 재현 방법 (Steps to reproduce)

1. flutter run

### Logs

```shell
android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:99: error: package com.kakao.sdk.flutter does not exist

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
Exception: Gradle task assembleDevDebug failed with exit code 1
Exited
```

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.2.1 22D68 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (4 available)
[✓] Network resources
```

**Comment by mbkim95** [comment]
안녕하세요

프로젝트에서 사용 중인 gradle과 AGP의 버전이 어떻게 되나요?

gradle 버전은 gradle/gradle-wrapper.properties 파일, AGP 버전은 프로젝트의 build.gradle 파일에서 확인할 수 있습니다

**Comment by blueddarker** [comment]
gradle과 AGP 버전 입니다.

<img width="503" alt="스크린샷 2023-05-31 오전 11 04 29" src="https://github.com/kakao/kakao_flutter_sdk/assets/7962153/1950b090-37b3-4cba-8280-4c699c4b6e39">

**Comment by mbkim95** [comment]
이슈 현상과 에러 메시지를 봤을 때는 의존성 추가가 제대로 되지 않은 것으로 보이는데요, pubspec.yaml 파일 첨부가 가능할까요?

그리고 조금 번거로우시더라도 flutter clean, Invalidate Caches 등을 실행해서 캐시를 초기화해보시는 것도 도움이 될 것 같습니다.

**Comment by blueddarker** [comment]
flutter clean, Invalidate Caches는 모두 해보았는데 똑같은 증상입니다.
pubspec.yaml 파일을 공개적으로 전체 공유는 힘들것 같습니다.
저희도 기존에는 크게 문제가 없다가 dio 라이브러리를 업데이트하면서 발생하는 문제로 보고 있는데 어떤 부분과 연관이 되어 있는지 파악이 되지 않고 있습니다.
그래서 dio 라이브러리 업데이트하면서 같이 변경된 플러그인에 답이 있는지 확인 부탁드립니다.
* dio: ^4.0.6 -> dio: ^5.1.2
* retrofit: 3.0.1+1 -> retrofit: ^4.0.1
* retrofit_generator: ^4.0.1 -> retrofit_generator: ^7.0.1
* webview_flutter: ^3.0.0 -> 
     webview_flutter: ^4.2.0
     webview_flutter_android: ^3.7.0
     webview_flutter_wkwebview: ^3.4.3

위 사항을 업데이트하면서 에러가 발생하는 부분입니다. 물론 다시 위 부분만 롤백하면 컴파일은 됩니다.
dio 라이브러리를 5.x대 변경이 필요해서 업데이트를 진행중인데 에러가 발생하네요.
그리고 dio 라이브러리도 kakao에서 5.0.3을 사용해서 해당 버전으로 변경해서 해보아도 동일한 현상입니다.

**Comment by mbkim95** [comment]
첨부해주신 패키지들 의존성을 추가해서 이슈를 재현을 시도했는데 이슈가 재현되지 않아서 정확한 원인 파악이 어려운 상황입니다ㅠㅠ

공개적으로 파일 공유하기가 어려우시다면 혹시 mbkim95@naver.com으로 이슈 재현되는 프로젝트를 압축해서 보내주실 수 있을까요?

현재 개발 중인 프로젝트를 그대로 보내주셔도 좋고, 새로운 프로젝트 하나 만들어서 이슈 상황 재현되도록 구성한 후에 프로젝트 파일을 공유해주셔도 괜찮습니다.

**Comment by blueddarker** [comment]
제가 gradle 버전을 다른 프로젝트 것으로 보냈네요. 혹시 버전이 좀 낮은데 아래 버전 때문에 문제일까요?
<img width="944" alt="스크린샷 2023-05-31 오후 1 54 38" src="https://github.com/kakao/kakao_flutter_sdk/assets/7962153/33994c4d-1cf6-4508-8837-94bf1a6a72d0">

**Comment by blueddarker** [comment]
Gradle 버전 올려서 설정하니 제대로 컴파일이 잘 됩니다. 도움 주셔서 감사합니다. @mbkim95
