### ISSUE TITLE
[Question] dev 브랜치 web build 에러 수정내역 사용

### ISSUE THREAD

**Issue by KangJuO** [kakao/kakao_flutter_sdk#184]
### 문의 사항 (Question)

안녕하세요
web build 에러 부분 수정해서 사용하고 있었는데요, // isNull error
dev 브랜치에 최근에 버그 픽스 커밋 해두신게 보여서 
해당 브랜치 혹은 커밋된버전 사용할수 있는 방법이있을까요~?

**Comment by mbkim95** [comment]
@KangJuO 
안녕하세요 해당 이슈 수정된 1.6.1 버전 배포되었습니다.

kakao_flutter_sdk에 관심가져주셔서 감사합니다
