### ISSUE TITLE
[Bug] `isKakaoTalkInstalled`를 iOS에서 호출 시 항상 `false`로 응답합니다

### ISSUE THREAD

**Issue by TerryJoo** [kakao/kakao_flutter_sdk#186]
### 이슈 설명 (Issue description)

안드로이드, iOS 각각 테스트 했을 때, iOS에서는 `isKakaoTalkInstalled`의 결과가 항상 false 이네요.

### 맥락, 상황
`false` 인 경우 `loginWithKakaoAccount`를, `true`인 경우 `loginWithKakaoTalk`를 호출하려 했습니다.
- 갤럭시에선 의도대로 **카톡설치가 안되어있을 때만** 카카오 계정 로그인로직으로 실행됩니다.
- iPhone15 Pro max(iOS 17.2.x)에선 의도와는 다르게, **항상 false**가 나오고 **카카오 계정 로그인** 로직이 실행됩니다. 이 로직을 무시한 채 `loginWithKakaoTalk` 호출하면, 설치가 되어있는 경우 잘 동작합니다만... DX측면에서 매우 혼란스럽습니다.

### 앱 ID (App ID)

1020877

### 플랫폼 (Platform)

iOS 17

### 디바이스 (Device)

iPhone 15 Pro max

### Version

kakao_flutter_sdk_user: 1.8.0

### Flutter SDK

3.19.0

### 재현 방법 (Steps to reproduce)

1. 카카오톡 설치 후, 아래 로직 시도
    ```dart
    () =>
        isKakaoTalkInstalled().then((b) => b
        ? UserApi.instance.loginWithKakaoTalk(
            serviceTerms: ['privacy-policy_240118', 'service_240119'])
        : UserApi.instance.loginWithKakaoAccount(
        serviceTerms: ['privacy-policy_240118', 'service_240119']));
    ```
2. UserApi.instance.loginWithKakaoAccount 가 호출되길래, 코드를 수정
    ```dart
    () => UserApi.instance.loginWithKakaoTalk(
        serviceTerms: ['privacy-policy_240118', 'service_240119']);
    ```
3. 카카오톡 앱으로 넘어감

### 코드 샘플 (Code Sample)

```dart
Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () => isKakaoTalkInstalled().then((b) => b
              ? UserApi.instance.loginWithKakaoTalk(
                  serviceTerms: ['privacy-policy_240118', 'service_240119'])
              : UserApi.instance.loginWithKakaoAccount(
                  serviceTerms: ['privacy-policy_240118', 'service_240119'])),
          child: Text('kakao login'),
        ),
      ),
    );
```

### Logs

```shell
에러로그는 없습니다. 오히려 `NotImplemented`같은 Exception이 나와야할 거 같습니다.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.2.1 23C71 darwin-arm64, locale ko-KR)
    • Flutter version 3.19.0 on channel stable at /Users/yungikjoo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (5 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/yungikjoo/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/yungikjoo/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/231.9392.1.2311.11255304/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/yungikjoo/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.11090377/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/yungikjoo/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/231.9392.1.2311.11255304/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/yungikjoo/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.10227.8/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Users/yungikjoo/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/233.13135.103/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • yungik joo의 iPhone (mobile) • 00008130-000C605814B8001C            • ios            • iOS 17.2.1 21C66
    • iPhone 15 Pro Max (mobile)  • 1B7B5F02-08E5-45BA-872B-3D26AAF16033 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by mbkim95** [comment]
안녕하세요

말씀하신 내용을 봤을 때 초기 설정이 되어있지 않은 것을 보이는데요, [가이드](https://developers.kakao.com/docs/latest/ko/flutter/getting-started#project)에서 ['앱 실행 허용 목록' 설정](https://developers.kakao.com/docs/latest/ko/ios/getting-started#project-plist)이 제대로 되어있는지 확인 부탁드리겠습니다.

**Comment by TerryJoo** [comment]
> 안녕하세요
> 
> 말씀하신 내용을 봤을 때 초기 설정이 되어있지 않은 것을 보이는데요, [가이드](https://developers.kakao.com/docs/latest/ko/flutter/getting-started#project)에서 ['앱 실행 허용 목록' 설정](https://developers.kakao.com/docs/latest/ko/ios/getting-started#project-plist)이 제대로 되어있는지 확인 부탁드리겠습니다.

@mbkim95 요청사항 관련하여 공유드립니다.

이전 값/상태: 가이드대로 카카오톡 로그인 기능만 제공하기 위해 `kakaokompassauth`만 등록되어 있었습니다.
새로 시도해본 내용/결과: `kakaolink`를 추가하여 재시도했으나, 여전히 `await isKakaoTalkInstalled()`의 결과는 `false`입니다.

---

## 추가 특이사항 공유
### 상황 설명
일단은 iOS쪽 설정문제가 아닌 것 같았어요. 앞서 이슈에서 설명드렸다시피 `isKakaoTalkInstalled` 대신 `loginWithKakaoTalk`만 호출해보기도 했는데, `loginWithKakaoTalk`호출 시, 카카오톡으로 잘 넘어갔기 때문입니다.

### 추가 정보
@mbkim95 님께서 요청 주신 문서를 참고하여 다양하게 테스트 해봤는데, 이해가 잘 안가는 부분이 있어서 추가 정보 공유드립니다.

**기존 info.plist**
`LSApplicationQueriesSchemes`키에 값으로
```xml
	<array>
		<string>kakaokompassauth</string>
	</array>
```
가 있었습니다. 로그인 기능만 쓰려고요.

**추가 시도 내용**
값을 아래처럼 바꿔서 `flutter clean`으로 리빌드했으나, `LSApplicationQueriesSchemes`값과는 무관하게 `loginWithKakaoTalk`는 호출 됩니다.
- `<array><string>kakaokompassauth</string>, <string>kakaokolink</string></array>`
- `<array></array>`

제가 뭔가 놓치고 있는 게 있을까요? 만약 위에 값과 무관하게 잘 동작한다면 위 값은 왜 필요한 건가요? 아니면 개발 환경이라 그런 건가요?

**Comment by mbkim95** [comment]
@TerryJoo 
우선 `kakaokompassauth`를 등록하였음에도 `isKakaoTalkInstalled()` 호출 결과가 `false`가 나온다고 하셔서 이 부분은 조금 더 확인이 필요할 것 같습니다. (제 테스트 환경에서는 재현되지 않고 있어서 이슈 파악에 시간이 좀 걸릴 것 같습니다)

해당 메소드 호출 결과와 무관하게 `loginWithKakaoTalk()`이 정상적으로 동작하는 이유는 1.7.0 버전부터 유니버셜 링크를 적용했기 때문입니다. 유니버셜 링크를 적용하기 전 버전들은 kakaokompassauth 커스텀 스킴을 이용해서 카카오톡을 호출했지만, 유니버셜 링크를 적용하면서부터 내부 동작 방식이 변경되어 kakaokompassauth 설정 없이 정상적으로 카카오톡 로그인이 가능하도록 변경되었습니다.

다만 여전히 `kakaokompassauth` 설정 가이드가 존재하는 이유는 `isKakaoTalkInstalled()` 실행 시 내부적으로 해당 값을 사용하기 때문입니다. 그래서 처음에 말씀주신 내용들을 보았을 때 `kakaokompassauth` 설정이 되어있지 않았을 것으로 판단했었습니다.

**Comment by TerryJoo** [comment]
고생 많으십니다. 저도 시간 날 때 개인적으로 확인해보고 알아내는 게 있으면 공유드리겠습니다.

**Comment by mbkim95** [comment]
@TerryJoo 조금 번거로우시겠지만 이슈 재현되는 간단한 샘플 프로젝트 하나 만들어서 프로젝트 통째로 mbkim95@naver.com 으로 보내주실 수 있을까요?

**Comment by TerryJoo** [comment]
> @TerryJoo 조금 번거로우시겠지만 이슈 재현되는 간단한 샘플 프로젝트 하나 만들어서 프로젝트 통째로 [mbkim95@naver.com](mailto:mbkim95@naver.com) 으로 보내주실 수 있을까요? 이슈가 재현되지 않고 있고 코드상 문제되는 부분이 보이지 않아서 원인 파악이 늦어지고 있네요ㅠㅠ

금일 예제 작성 해봤는데, 예제에선 잘 동작하는 걸 확인 했어요. 초기화 시점 문제로 예상이 가는데, 테스트 해보고 자세한 내용 공유 드리겠습니다.

**Comment by TerryJoo** [comment]
@mbkim95 대응하시느라 고생 많으셨습니다. 잘 해결되었습니다. info plist 쪽 키값에 오타가 껴있었어요..

**Comment by mbkim95** [comment]
@TerryJoo 해결되어서 다행이네요ㅎㅎㅎ 고생하셨습니다!
