### ISSUE TITLE
[Bug] Support web wasm build

### ISSUE THREAD

**Issue by nomad2569** [kakao/kakao_flutter_sdk#189]
### 이슈 설명 (Issue description)

flutter 3.22.0 부터 **web 의 wasm build 가 stable** 해졌습니다.

### [그러나, flutter 의 web wasm build 는 현재 아래와 같은 문제를 갖고 있습니다.](https://docs.flutter.dev/platform-integration/web/wasm#js-interop-wasm)

> Wasm support currently has some limitations. The following list covers some common issues.
> 
> Requires JS-interop to access browser and JS APIs
> 
> To support compilation to Wasm, [Dart has shifted](https://dart.dev/interop/js-interop) how it enables interop with browser and JavaScript APIs. This shift prevents Dart code that uses dart:html or package:js from compiling to Wasm.
> 
> Instead, Dart now provides new, lightweight interop solutions built around static JS interop:
> 
> [package:web](https://pub.dev/packages/web), which replaces dart:html (and other web libraries)
> [dart:js_interop](https://api.dart.dev/stable/dart-js_interop), which replaces package:js and dart:js
> Most packages owned by the Dart and Flutter teams have been migrated to be compatible with Wasm support in Flutter, such as [package:url_launcher](https://pub.dev/packages/url_launcher). To learn how to migrate your packages and applications to the new solutions, check out the [JS interop](https://dart.dev/interop/js-interop) documentation and [package:web migration guide](https://dart.dev/interop/js-interop/package-web).
> 
> To check if a Wasm build failed due to incompatible APIs, review the error output. These often return soon after a build invocation. An API-related error should resemble the following:
> 
> ```
> Target dart2wasm failed: Exception: ../../../../.pub-cache/hosted/pub.dev/url_launcher_web-2.0.16/lib/url_launcher_web.dart:6:8: Error: Dart library 'dart:html' is not available on this platform.
> import 'dart:html' as html;
> ```
> 
> Context: The unavailable library 'dart:html' is imported through these packages:
> 
>     web_plugin_registrant.dart => package:url_launcher_web => dart:html
>     web_plugin_registrant.dart => package:url_launcher_web => package:flutter_web_plugins => dart:html
>     web_plugin_registrant.dart => package:flutter_web_plugins => dart:html)
> 

이에 대응하여

1. dart sdk to 3.4.0
2. `dart:html` -> `package:web`
3. `package:js` and `dart:js` -> `dart:js_interop` 

으로 변경하실 의향이 있으실까요?

다른 issue 에서 dart sdk upgrade 를 꺼려하시는 것을 보았으나, 의향이 있으시다면 contribute 하고자 문의 남깁니다.

감사합니다.

### 앱 ID (App ID)

876578

### 플랫폼 (Platform)

Web

### 디바이스 (Device)

Chorme

### Version

1.5.0

### Flutter SDK

3.22.0

### 재현 방법 (Steps to reproduce)

`flutter build web --wasm`

### 코드 샘플 (Code Sample)

```dart
`flutter build web --wasm`
```

### Logs

```shell
../../../../.pub-cache/hosted/pub.dev/kakao_flutter_sdk_common-1.9.0/lib/src/web/kakao_flutter_sdk_plugin.dart:3:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as html;
       ^
```

### Flutter Doctor

```shell
flutter doctor -v
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.3.1 23D60 darwin-arm64, locale en-KR)
    • Flutter version 3.22.0 on channel stable at /Users/minkyukim/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (2 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/minkyukim/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)            
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 125.0.6422.76

[✓] Network resources
    • All expected network resources are available.
```

**Comment by mbkim95** [comment]
@nomad2569  안녕하세요

이슈에 대해서 상세하게 설명해주셔서 감사합니다! 

제안주신 내용에 대해서는 내부적으로 검토가 필요해 조금 시간이 걸릴 수 있는 점 양해 부탁드리겠습니다.

이슈 확인 및 검토해보고 다시 답변드리도록 하겠습니다.

**Comment by mbkim95** [comment]
@nomad2569 답변이 조금 늦었습니다. 제안주신 내용에 대해서 지원이 가능할지 검토해보았습니다. 
결론부터 말씀드리면 **WebAssembly 빌드가 가능하도록 지원 예정이지만, 일부 기능에 대해서 비정상적으로 동작할 수 있습니다**.

[공식 문서](https://docs.flutter.dev/platform-integration/web/wasm#serve-the-output-with-an-http-server)에도 설명되어있듯이 WebAssembly로 동작하기 위해서는 호스팅하는 서버에서 COEP(Cross-Origin-Embedder-Policy), COOP(Cross-Origin-Opener-Policy) 헤더를 특정 값으로 추가해야합니다. 이 중에서도 COOP 헤더는 same-origin 값으로 고정되어있는데요, 이 경우 부모창과 팝업창의 origin이 다른 경우 서로에게 접근할 수 없게 되어 팝업창을 활용하는 기능들이 정상적으로 동작하지 못하는 것을 확인했습니다. (ex - [피커: 친구 선택하기](https://developers.kakao.com/docs/latest/ko/kakaotalk-social/flutter#picker-friends), [카카오톡 채널 간편 추가하기](https://developers.kakao.com/docs/latest/ko/kakaotalk-channel/flutter#follow-channel), [배송지 선택하기](https://developers.kakao.com/docs/latest/ko/kakaologin/flutter#shipping-address-select))

COOP 헤더에 same-origin 값을 사용하는 경우 팝업을 활용하는데 많은 제약이 걸리기 때문에 [same-origin-allow-popups 값을 허용하려고 검토 중](https://web.dev/articles/cross-origin-isolation-guide?hl=ko)인 것도 확인했습니다. COOP 헤더로 인해 일부 기능을 정상적으로 사용할 수 없지만, 해당 기능들을 사용하지 않으면서 WebAssembly를 사용하고 싶은 경우도 있을 것으로 판단해 WebAssembly 빌드가 가능하도록 지원할 예정입니다. 이 점 참고 부탁드리겠습니다.
