### ISSUE TITLE
로그인 진행중 동의하고 계속하기 이후에 진행이 되지 않습니다.

### ISSUE THREAD

**Issue by rlaeoghks78** [kakao/kakao_flutter_sdk#21]
안녕하세요~

카카오톡 로그인중에 문제가 생겨 문의드립니다.

카카오톡이 깔려있지 않은 안드로이드 에뮬레이터에서 개발중입니다.

로그인을 시도하면 이메일이랑 비밀번호 입력 후 동의하고 계속하기 버튼을 눌러도 진행이 되지 않습니다.

카카오톡이 설치된 핸드폰에선 잘 실행됩니다.

https://devtalk.kakao.com/t/flutter/95645 이 링크와 같은 현상 같습니다.

감사합니다.

**Comment by CoderSpinoza** [comment]
https://github.com/kakao/kakao_flutter_sdk/blob/74fd1553a6b58b3829a1d37e76be83a8438ac101/example/android/app/src/main/AndroidManifest.xml#L38

 요 위 링크의 `AndroidManifest.xml` 처럼 scheme 등록을 하셔야할 것 같아요. activity 전체를 복사해서 붙여넣으시고 data tag의 android:scheme attribute 만 `kakao${native_app_key}` 형태로 사용하시면 됩니다. 
카카오톡으로 로그인 하는 경우에는 `Actvitity#onActivityResult()`를 통하여 값을 받아오지만 default browser로 로그인을 하는 경우에는 custom scheme 을 통하여 로그인 값을 전달받기 때문에 위의 등록 과정이 필요합니다. 중요한 내용인데 README에 빠져있는 것 같네요. 보강하도록 하겠습니다 ㅠ.ㅠ

이렇게 해도 안되실 경우 다시 문의 주세요! 문제가 해결되면 이슈를 닫아주세요 :)

**Comment by rlaeoghks78** [comment]
설명해주신대로 수정하니 잘 됩니다~
감사합니다!
