### ISSUE TITLE
카카오 로그인 웹요청 창 닫기 후 반응이 없습니다.

### ISSUE THREAD

**Issue by lovedise** [kakao/kakao_flutter_sdk#22]
var code = await AuthCodeClient.instance.request();

웹으로 카카오로그인 화면이 뜬 후 그냥 닫았을 경우 위 코드로 result 가 오지 않습니다.

감지 할 수 있는 방법이 있을까요?

**Comment by CoderSpinoza** [comment]
아마 #21 과 동일한 이슈일 것 같아요. `AndroidManifest.xml`에 custom scheme을 등록하시고 다시 시도해보시겠어요?

**Comment by CoderSpinoza** [comment]
요 이슈는 더 이상 답변이 없으셔서 종료하도록 하겠습니다. 다시 이슈가 발생하시면 reopen 하시거나 새 이슈를 만들어주시면 감사하겠습니다!
