### ISSUE TITLE
문서가 API 변경에 맞게 업데이트되어있지 않음

### ISSUE THREAD

**Issue by therne** [kakao/kakao_flutter_sdk#23]
1. `AuthCodeClient.request`는 실제로 `AccessTokenResponse`를 반환하지만, Readme의 문서 예시에는 `AccessToken`을 반환한다고 되어 있습니다.
2. `AccessTokenStore.toCache`는 `toStore`로 리네임되었지만 문서에는 기존 API로 표기되어 있습니다.

이외에도 `isKakaoTalkInstalled` 여부를 통해서 분기하는 부분이나 AndroidManifest / Info.plist에 OAuth Redirect Link Scheme을 등록하는 부분도 카카오 로그인 API 연동 시 필수적인 과정이므로 문서에 추가되면 좋을 것 같습니다. 

혹은 example 코드를 필수적으로 참고하라는 예시라도 있으면 좋을 것 같습니다. 현재는 문서대로 설정 시 카카오 로그인이 되지 않습니다.

**Comment by iruis** [comment]
몇시간동안 안되어서 인내심의 한계가 느껴졌었는데 덕분에 해결되었습니다(...). 원인을 알게되었음에도 현재 개편된 카카오 개발자 페이지에서도 Info.plist에 스키마 등록하는 법이 어디에 있는지 한참 찾았네요. 암튼 감사합니다.

**Comment by CoderSpinoza** [comment]
@therne 자세한 피드백 정말 감사드립니다. 말씀해주신 부분 전부 반영하였습니다. :)
