### ISSUE TITLE
카카오싱크에 대한 질문.

### ISSUE THREAD

**Issue by lovedise** [kakao/kakao_flutter_sdk#24]
안녕하세요~

휴대폰정보가 필요하여 카카오싱크를 사용하려고 하는데.. 라이브러리에서 따로 지원하는게 있는지 궁금합니다.

아니면 그냥 싱크 서비스신청 후 로그인 하는 방식 그대로 사용하면 될지 궁금합니다 ^^

**Comment by CoderSpinoza** [comment]
안녕하세요! 만약 휴대폰 번호만 필요하시다면 싱크 서비스 신청 후 바로 SDK를 사용하시면 될 것 같습니다.

https://github.com/kakao/kakao_flutter_sdk/blob/master/lib/src/user/model/account.dart

위 모델에 보시면 `phoneNumber` 필드를 통해 휴대폰정보를 접근하실 수 있습니다.
싱크 서비스 신청 후 전화번호가 동의항목 중 필수일 경우에는 별도의 처리가 필요없지만, 만약 선택이나 이용중 사용이라면 로그인 이후에 동적동의를 통하여 직접 동의를 받아야하는 경우도 있으니 이 점 참고하시기 바랍니다!

추가 질문이 있으시면 댓글 남겨주세요 :) 만약 추가 질문이 없으시다면 이슈를 닫아주시면 되겠습니다.

**Comment by lovedise** [comment]
네 감사합니다^^
