### ISSUE TITLE
ios에서 앱(간편로그인)으로 로그인이 안됩니다.

### ISSUE THREAD

**Issue by realrnbboy** [kakao/kakao_flutter_sdk#28]
웹으로 로그인은 정상적으로 되는데,
앱으로 로그인을 하면 동의 한 후, 반응이 없습니다.
소스코드상에서는
appdelegate의 KOSession.handleOpen(url)에서 false로 리턴이 되고, 진행이 되지 않습니다.

String authCode = await AuthCodeClient.instance.requestWithTalk();
print(authCode )

를 하면 authCode 가 출력되지 않습니다.

도와주세요 ㅠㅠ

**Comment by CoderSpinoza** [comment]
KOSession 클래스는 `kakao_flutter_sdk`가 아닌 카카오 네이티브 SDK를 사용하실 때 필요한 클래스입니다. `kakao_flutter_sdk`는 `FlutterPlugin`의 기능을 사용하여 로그인 정보가 담긴 custom scheme url를 받아오게 됩니다. 해당 관련 코드는

https://github.com/kakao/kakao_flutter_sdk/blob/398882cd3513043f2deafcbefc1d82bf89e88a2b/ios/Classes/SwiftKakaoFlutterSdkPlugin.swift#L135

위 코드에 구현되어 있습니다. `authCode`를 받아올 수 없다면 아마 카카오톡의 로그인 스킴을 plist에 등록하는 스텝이라던지 등등을 스킵하셨을수도 있을 것 같은데요.

https://github.com/kakao/kakao_flutter_sdk#via-browser

위 링크를 한번 확인해 보시겠어요? 카카오 공식 개발 가이드에도 
https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios-v1#app-key

위 링크에서 해당 내용을 다루고 있습니다.

한번 해보시고 안되시면 다시 댓글 남겨 주세요! 문제가 해결되었다면 이슈를 닫아주시면 감사하겠습니다.

**Comment by realrnbboy** [comment]
답변 감사합니다.
말씀하신것들 다시 살펴 보았는데, 원인은 못찾겠네요..

일단 링크주신 것은, 웹브라우저쪽 이고, 웹브라우저를 통한 로그인은 정상동작 됩니다.

문제는 앱을 통한 로그인 인데,
ios 관련 설정은 그대로 유지한 채, 다른 플러그인을 사용했을 때는 정상적으로 동작하는 것으로 봐서, dart쪽 설정이라든지, 코드가 잘못된 것 같은데.. 그걸 못찾겠네요 ㅠㅠ

**Comment by CoderSpinoza** [comment]
브라우저를 통한 로그인은 ASWebAuthenticationSession 에서 직접 콜백을 등록하기 때문에 보통 콜백 이슈가 생기지 않습니다.

말씀해주신 상황은 전형적으로 ApplicationDelegate의 openURL에서 return true를 하셔서 kakao_flutter_sdk에서 등록한 delegate의 openURL 코드가 불리지 않는 상황이지 않을까 싶은데요. 다른 커스텀 스킴 처리를 하기 위한 ApplicationDelegate 코드가 있으시다면 혹시 첨부해주실 수 있나요?

**Comment by mooneegee** [comment]
저도 동일한 문제가 발생합니다.
example 코드로 실행하여도 마찬가지입니다.

**Comment by kcy336** [comment]
저도 같은 문제가 있습니다 ㅠ.ㅠ
해당 레포를 다운받아 example을 실행해도 똑같이 카카오톡 네이티브 앱을 통한 로그인은 안되네요... 
다시 앱으로 복귀가 안됩니다.

**Comment by kcy336** [comment]
자답합니다.

info.plist에 다음과 같이 추가하시길 바랍니다.

<key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>kakao25f374eebecc6f8a6c8b229ef96e1e17</string>
            </array>
        </dict>
    </array>
    <key>KAKAO_APP_KEY</key>
    <string>25f374eebecc6f8a6c8b229ef96e1e17</string>

**Comment by CoderSpinoza** [comment]
카카오 개발자 사이트에서 참고해야하는 부분이 있는데 사이트 개편으로 다른 곳으로 내용이 옮겨진 것 같아요.

https://github.com/kakao/kakao_flutter_sdk/commit/63d48f046fa27ab63c0c08e02811f750113cb3ce

위 commit 을 통해서 참고해야하는 링크들을 README에 추가하였습니다.
