### ISSUE TITLE
user 클래스 명을 바꾸면 어떨까요??

### ISSUE THREAD

**Issue by ujon** [kakao/kakao_flutter_sdk#30]
앱을 개발하다가 user 클래스에서 충돌이 나길래 이슈 등록합니다.
'package:kakao_flutter_sdk/src/user/model/user.dart' 의 클래스명을 'User'에서  'KakaoUser'로 변경하면 type alias 설정을 안해도 되고 좀 더 직관적일꺼 같아요.

**Comment by CoderSpinoza** [comment]
SDK 사용에 불편을 드려서 죄송합니다. SDK 개발 당시에 좀 급하게 만든 감이 없지 않아 네이밍 등 부분에서 깊은 고민이 되지 않은 것 같기도 합니다.

요 이슈는 당장 변경하기에는 힘들 것 같고, 추후 1.0 정식 버전을 낸다던지 인터페이스 변경이 가능한 시점에 리스트업을 해서 개선하도록 하겠습니다. 좋은 의견 주셔서 감사합니다!
