### ISSUE TITLE
Handshake Exception

### ISSUE THREAD

**Issue by serendipity1004** [kakao/kakao_flutter_sdk#31]
안녕하세요. 저희 유저들 중 한분이 카카오톡을 연동하는 카카오 로그인을 누르면 Handshake Exception이 나온다고 합니다. 안드로이드 유저고 삼성 J7 기종을 사용하신다는데 어떤 문제인지 알수있을까요?

**Comment by CoderSpinoza** [comment]
요 이슈는 카카오톡에 관련된 이슈일 가능성이 커서 https://devtalk.kakao.com 요기에 문의를 주시는게 카카오 쪽에서 더 답변을 드리기가 편할 수 있을 것 같아요. 위 사이트에 제공 가능한 간략한 유저 정보, 발생한 날짜, 에러가 확정적인지 등을 글 또는 메시지로 남겨보세요!
