### ISSUE TITLE
flutter sdk 업데이트

### ISSUE THREAD

**Issue by sewonprk** [kakao/kakao_flutter_sdk#32]
제일 최근 업데이트가 kakao_flutter_sdk 0.4.2 으로 4달 정도 지났는데 혹시 새로 업데이트가 곧 나올 예정인가요?

**Comment by CoderSpinoza** [comment]
@sewonprk 

안녕하세요!

1. flutter 및 라이브러리 버전 업데이트
1. #20 해결

위 두가지를 포함한 버전이 곧 출시될 예정입니다. :) 원하시는 기능이나 개선점이 있으시면 자유롭게 이슈로 남겨주세요!
