### ISSUE TITLE
유저 이메일을 얻는 법 질문드립니다.

### ISSUE THREAD

**Issue by leedh2004** [kakao/kakao_flutter_sdk#34]
안녕하세요, 이제 막 플루터를 배우기 시작한 초보개발자입니다.
다름이 아니라, 현재 만들고자 하는 앱에서 여러가지 OAuth Login을 지원하기 때문에 식별자를 email로 두고 서버에 저장하려 했습니다. 따라서 email이 필요한데 어떻게하면 email을 가져올 수 있는지 문의드립니다.

```dart
void requestMe() {
  try {
    User user = await UserApi.instance.me();
    if (user.kakaoAccount.emailNeedsAgreement || user.kakaoAccount.genderNeedsAgreement) {
      // email and gender can be retrieved after user agreement
      // you can also check for other scopes.
      await retryAfterUserAgrees(["account_email", "gender"]);
      return;
    }
    // do anything you want with user instance
  } on KakaoAuthException catch (e) {
    if (e.code == ApiErrorCause.INVALID_TOKEN) { // access token has expired and cannot be refrsehd. access tokens are already cleared here
      Navigator.of(context).pushReplacementNamed('/login'); // redirect to login page
    }
  } catch (e) {
    // other api or client-side errors
  }
}

void retryAfterUserAgrees(List<String> requiredScopes) async {
    // Getting a new access token with current access token and required scopes.
    String authCode = await AuthCodeClient.instance.requestWithAgt(e.requiredScopes);
    AccessTokenResponse token = await AuthApiClient.instance.issueAccessToken(authCode);
    AccessTokenStore.instance.toCache(token); // Store access token in AccessTokenStore for future API requests.
    await requestMe();
}
```
이 부분이 공식문서에 있는 이메일을 가져오는 부분인데 이해 안되는 부분이 여러가지 있습니다..
코드를 읽어보면, 동의를 얻은 다음에 로그인 후, user.kakaoaccount.email 이런식으로 접근할 수 있는것처럼 보입니다.

``requetMe()``
1. requestMe는 왜 async function이 아닌가요..?
2. retryAfterUserAgress 는 future return type이 아닌데 await을 쓸 수 있나요..?

``retryAfterUserAgrees()``
3. AuthApiClient가 undefined name이라고 나옵니다.
4. AutoCodeClient.instance.requestWithAgt(e.requireScopes)에서 e는 무엇인가요..?
5. AccessTokenStore.instnce.toCache(token)에서 toChace가 undefined method라고 나옵니다..

알려주시면 감사하겠습니다 ㅜㅠ

**Comment by whatamelon** [comment]
해당 예제로 테스트해보고 성공하지 못해서 다른 방식으로 카카오 로그인을 구현한 예제코드입니다.
공유드립니다.

  _loginWithTalk() async{
    print('카톡 깔려있음.');
    try {
      var authCode = await AuthCodeClient.instance.requestWithTalk();
      print('토큰 가져옴? $authCode');
      await _issueAToken(authCode);
    }  catch (e) {
      print('에러 ? $e');
    }
  }

  _issueAToken(authCode) async{

    try {
      var token = await AuthApi.instance.issueAccessToken(authCode);
      AccessTokenStore.instance.toStore(token);
      print('이건 카카오 토근이라구~ $token');

      User user = await UserApi.instance.me();



      print(user.toString());
      print(user.id);
      print(user.kakaoAccount.email);
      var _kakaoEmail = '';

      if(user.kakaoAccount.email == null) {
        _kakaoEmail = '';
      } else{
        _kakaoEmail = user.kakaoAccount.email;
      }
 }
} catch(e) {
  print(e);
}
}

user.kakaoAccount.email을 null check한 이유는 더 이상 카카오톡에서의 email은 필수값이 아니기 때문입니다.
카카오톡의 정책변경으로 인해, email없이도 회원가입을 할 수 있고, 따라서 email이 없는 회원도 있습니다.
email이 아닌 userid를 식별자로 두시는것을 추천드립니다.

**Comment by CoderSpinoza** [comment]
@leedh2004 

README.md 에 오타들이 좀 있었네요 수정하도록 하겠습니다. :( 아래의 코드를 참고하시면 됩니다.

```dart

void requestMe() async {
  try {
    User user = await UserApi.instance.me(); // /v2/user/me API를 호출하여
    if (user.kakaoAccount.emailNeedsAgreement) {
      // 유저 계정에 이메일이 존재하지만 정보제공동의를 하지 않은 경우
      await retryAfterUserAgrees(["account_email"]); // account_email scope 동의를 받기 위한 동의창을 띄운다.
      return;
    }
    // do anything you want with user instance
  } on KakaoAuthException catch (e) {
    if (e.code == ApiErrorCause.INVALID_TOKEN) { // access token has expired and cannot be refrsehd. access tokens are already cleared here
      Navigator.of(context).pushReplacementNamed('/login'); // redirect to login page
    }
  } catch (e) {
    // other api or client-side errors
  }
}

Future<void> retryAfterUserAgrees(List<String> requiredScopes) async {
    // 인자로 넘겨받은 scope 리스트로 유저에게 동의를 받는다.
    String authCode = await AuthCodeClient.instance.requestWithAgt(requiredScopes);
    // 새롭게 동의하면서 발급받은 auth code를 통하여 access token 을 새로 발급받는다.
    AccessTokenResponse token = await AuthApiClient.instance.issueAccessToken(authCode);
    AccessTokenStore.instance.toStore(token); // 발급받은 access token을 저장한다.
    await requestMe(); // /v2/user/me API를 재호출한다.
}
```

@whatamelon 님이 말씀해주신대로 유저 계정에 이메일 값이 없을 수 있으니 이 부분 유저에게 별도 입력을 받으시던지 해야 합니다. 더 궁금한 점이 있으시면 댓글 달아주세요!

p.s. 위 질문 중 3번은 원인을 잘 모르겠네요. 아직도 발생하나요?
