### ISSUE TITLE
Firebase랑 연결하면 credential 필요하는데 credential 어떻게 받을 수 있어요?

### ISSUE THREAD

**Issue by punreachrany** [kakao/kakao_flutter_sdk#36]
저희가 카카오 로그인하고 firebase랑 연결해야 됩니다. 혹시 credential 받을 수 있는 방법이나 연결 방법을 알려 줄 수 있나요?

**Comment by CoderSpinoza** [comment]
카카오는 Firebase auth 의 공식 프로바이더가 아니어서 커스텀 토큰을 통하여 연동을 하셔야 할텐데요.

https://github.com/FirebaseExtended/custom-auth-samples

위 repository 한번 확인해 보시겠어요? 2년 정도 관리는 안된 저장소긴 한데 대충의 개념이 나와있습니다. 서버 쪽에서 Firebase admin SDK 를 사용하여 custom token 을 생성하셔야 하고, 이를 클라이언트로 보낸 후 클라이언트에서 Firebase client SDK 를 통하여 sign in 시키시면 될 것 같아요.

간단하게 설명드렸는데 혹시 이해가지 않는 부분이 있으시다면 다시 코멘트 남겨 주세요!

**Comment by fysoul17** [comment]
https://github.com/fysoul17/firebase_auth_simplify

**Comment by fysoul17** [comment]
@punreachrany  
Firebase로 카카오 외에 여러가지 로그인을 flutter에서 쉽게 연동하실 수 있도록 아래 패키지를 제작하였습니다.
functions 폴더를 참고하시면 @CoderSpinoza  님이 말씀하신 부분이 구현되어있습니다.

https://github.com/fysoul17/firebase_auth_simplify

@CoderSpinoza 
아무래도 플러터는 FIrebase 를 백엔드로 사용하시는 분들이 많아, 혹 폴더를 하나 지정해주시면 
다른 이용자분들이 참고하실 수 있도록 custom auth 로 firebase 로그인하는 cloud functions 코드를 typescript 버전으로도 하나 올려놓겠습니다.

**Comment by fysoul17** [comment]
@CoderSpinoza 

Fork 해서 typescript 용으로 firebase cloud function 연동 부분 샘플 코드 추가해놓았습니다. 

https://github.com/fysoul17/kakao_flutter_sdk

Pull Request를 위해서는 oss@kakaocorp.com 으로 CLA copy를 받아야 하는것 같은데, 어떻게 진행하는게 좋을지 의견 부탁드리겠습니다. 

만약 해당 코드들이 Kakao 플러그인 자체와 무관하기 때문에 Pull request가 적절하지 않다고 판단되시면 다른 유저분들이 참고하실 수 있게 쉽게 공유 될 수 있는 방안에 대한 의견을 주시면 참고하여 반영하도록 하겠습니다.

**Comment by CoderSpinoza** [comment]
@fysoul17 

답변이 좀 늦었네요 ㅠ.ㅠ 다른 개발자분들에게 큰 도움이 될 수 있는 샘플 코드 추가해주셔서 감사합니다. 이게 제 개인 리파지토리 였으면 샘플 코드들을 추가하는데에 큰 문제가 없는데, 카카오 organization 하위의 리파지토리여서 코드를 추가하는데 좀 번거로운 점이 있는 것 같아요. 실제로 이 리파지토리에 있는 모든 소스코드들이 카카오의 오픈소스 담당부서에서 검증해야하는 스텝이 있어서요..

samples 관련 리파지토리를 따로 만들고 이 리파지토리의 README에서 링크를 걸면 어떨까요?

**Comment by fysoul17** [comment]
@CoderSpinoza 
괜찮습니다. ㅎㅎ
그리고 리파지토리에 대한 부분은 충분히 이해하는 바입니다. ^^ 그래서 여쭤본것이구요

어차피 개인적인 이득을 위해 공유한 것이 아니니, @CoderSpinoza 님 께서 결정해 주시면 감사하겠습니다.

Samples를 따로 만드셔도 무방하며, 번거로우시면 이전에 fork 하여 example_firebase 에 ts코드만 올려놓은 [리파지토리](https://github.com/fysoul17/kakao_flutter_sdk)가 있으니 이용하셔도 되고, flutter로 firebase 인증을 조금이나마 쉽게 하기 위해 만든 [패키지](https://github.com/fysoul17/firebase_auth_simplify)가 있는데, 거기는 @CoderSpinoza 님께서 일전에 샘플로 firebase에 올리신 js 코드를 참고하여 샘플로 올려둔거라 js를 이용하시는 분들은 해당 패키지를 참고 하셔도 좋을 것 같습니다.

**Comment by CoderSpinoza** [comment]
@fysoul17 @punreachrany 

README에 샘플 코드가 포함되어있는 리파지토리 및 package 도 링크를 달아놓았습니다. 더 나은 방안이 있으시면 제안해 주시면 감사하겠습니다. 개선을 위해 노력해주신 두분께 감사드립니다.
