### ISSUE TITLE
유저 프로필 정보 얻는 방법

### ISSUE THREAD

**Issue by KwangryeolPark** [kakao/kakao_flutter_sdk#37]
```dart
void requestMe() async {
    try {
      User user = await UserApi.instance.me();
      if (user.kakaoAccount.emailNeedsAgreement) {
        await retryAfterUserAgrees(["account_email"]);
        debugPrint("email");
        debugPrint(user.kakaoAccount.email);
        debugPrint("email");
        return;
      }
    } catch (e) {debugPrint(e.toString());}
  }

  Future<void> retryAfterUserAgrees(List<String> requiredScopes) async {
    String authCode =
        await AuthCodeClient.instance.requestWithAgt(requiredScopes);
    AccessTokenResponse token =
        await AuthApi.instance.issueAccessToken(authCode);
    await requestMe();
  }
```

여기서 user.kakaoAccount.emailNeedsAgrement가 null로 호출되었다는데 어떤 문제가 있는 건가요?

그리고 이메일 뿐만 아니라 다른 정보도 얻고 싶다면 "account_email"말고 또 어떤 방식으로 값을 전달해야할까요?

**Comment by CoderSpinoza** [comment]
emailNeedsAgreement 는 항상 값을 가지고 있어야하는 것으로 알고 있습니다. REST API로 호출하셔도 해당 필드 값이 null 로 내려오는지 확인하면 좋을 것 같습니다. 해당 전체 리스트는 카카오 API플랫폼파트에서 운영하고 있는 내용이어서 아래 링크들에서 검색 혹은 문의 주시면 될 것 같습니다.

https://developers.kakao.com
https://devtalk.kakao.com

null로 내려오는 문제가 계속 있다면 위 https://devtalk.kakao.com 에 문의를 남겨주시면 되겠습니다. 이 이슈는 우선 닫을게요. 또 다른 질문이 있으시면 이슈 남겨주시면 되겠습니다!
