### ISSUE TITLE
Podfile version issues

### ISSUE THREAD

**Issue by heycodingkr** [kakao/kakao_flutter_sdk#39]
I got this issue below.
`[!] CocoaPods could not find compatible versions for pod "kakao_flutter_sdk":`

I resolved this error by this line on 'Podfile'  in '/ios' folder. 

`platform :ios, '11.0'`

I wish you updated README file by mentioning this issue.

**Comment by CoderSpinoza** [comment]
resolved by https://github.com/kakao/kakao_flutter_sdk/commit/653fbb5fa64f31dc291008f0173e141c7d85add0.
