### ISSUE TITLE
Kakao SDK (Android/iOS) v2와 비전,번역 API v2 개발 일정

### ISSUE THREAD

**Issue by whatamelon** [kakao/kakao_flutter_sdk#40]
카카오 api v2는 flutter sdk에 언제쯤 추가될 지 일정을 알 수 있을까요?

**Comment by CoderSpinoza** [comment]
SDK v2는 Android 와 iOS SDK 의 독자적인 버전이어서 flutter sdk 와는 상관이 없습니다.

비전, 번역 API v2 는 8월 내로 작업할 예정입니다. SDK에 대한 관심 감사드립니다!!
