### ISSUE TITLE
flutter pub get 수행시 디펜던시 오류

### ISSUE THREAD

**Issue by Sunggu** [kakao/kakao_flutter_sdk#41]
이번 flutter master branch 로 upgrade 한 이후 pub get 시도시 아래와 같은 오류가 발생합니다.
pubspec.yaml 파일에서 platform 관련된 내용을 주석처리하고 시도하면 정상적으로 수행이 되는 것으로 확인됩니다.
해당 이슈 확인 부탁드립니다.

Running "flutter pub get" in Application...     
Because every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.1 and kakao_flutter_sdk >=0.3.0 depends on platform ^2.2.1, flutter_driver from sdk is incompatible with kakao_flutter_sdk >=0.3.0.

So, because Application depends on both kakao_flutter_sdk ^0.4.2 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because Application depends on both kakao_flutter_sdk ^0.4.2 and flutter_driver any from sdk, version solving failed.)
exit code 1

**Comment by CoderSpinoza** [comment]
[Platform](https://pub.dev/packages/platform/changelog) package 의 경우 가장 최신 버전이 2.2.1 이고 3.0.0-nullsafety.1 버전은 prerelease 상태인데요. Flutter master version이 prerelease 버전을 사용하고 있다고 해서 해당 버전을 사용하기는 어려움이 있을 것 같습니다.

이 부분 혹시 더 나은 해결 방법이 있다면 제안해주시면 감사하겠습니다.

**Comment by Sunggu** [comment]
디펜던시 문제는 platform 에 걸려있습니다.
제가 소스를 모두 확인하진 않았습니다만 해당 라이브러리에 연관된게 큰 문제가 아니라면 라이브러리 버전을 올려주시거나  관련 로직을 수정하면 좋을 것 같습니다.

제가 위에  적었듯 로그인 자체는 저 라이브러리를 참조하는게 없었던 것 같아서요. 

저도 구현하신 소스를 확인해보고 수정 방안이 있다면 PR드리겠습니다.
고맙습니다!

**Comment by CoderSpinoza** [comment]
@Sunggu 

https://pub.dev/packages/kakao_flutter_sdk/versions/0.6.0-beta.1

정식 release 에서는 prerelease 버전의 패키지를 참조할 수 없어서, SDK 또한 `0.6.0-beta.1` 버전으로 배포하였습니다. 해당 버전을 사용해 보시고 문제가 있으면 이슈 등록해 주세요!
