### ISSUE TITLE
README 수정이 필요합니다.

### ISSUE THREAD

**Issue by skkang-arbang** [kakao/kakao_flutter_sdk#45]
README 내용중 Getting Access Token의 내용 일부가 수정이 필요한 것 같습니다.

```dart
String token = await AccessTokenStore.instance.fromStore();
if (token.refreshToken == null) {
  Navigator.of(context).pushReplacementNamed('/login');
} else {
  Navigator.of(context).pushReplacementNamed("/main");
}
```
에서
 
String token = await AccessTokenStore.instance.fromStore(); 을

AccessToken token = await AccessTokenStore.instance.fromStore(); 로

바꾸어야 할 것 같습니다.

**Comment by CoderSpinoza** [comment]
제보 감사드립니다!
