### ISSUE TITLE
1.22 버전에서 dependency 오류

### ISSUE THREAD

**Issue by thruthesky** [kakao/kakao_flutter_sdk#46]
어제 새로운 플러터 stable 버전 1.22 가 발표되어서 flutter upgrade 후 실행을 하면, kakao sdk 의 platform 부분에서 아래와 같이 오류가 발생합니다.

event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in flutterpress...}
Because kakao_flutter_sdk >=0.3.0 depends on platform ^2.2.1 and every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.2, kakao_flutter_sdk >=0.3.0 is incompatible with flutter_driver from sdk.
So, because flutterpress depends on both kakao_flutter_sdk ^0.5.0 and flutter_driver any from sdk, version solving failed.
event sent after app closed: {id: 0, progressId: null, finished: true}
pub get failed (1; So, because flutterpress depends on both kakao_flutter_sdk ^0.5.0 and flutter_driver any from sdk, version solving failed.)

**Comment by CoderSpinoza** [comment]
특정 플러그인의 pre-release 버전에 의존할 경우, 버전 자체를 pre-release 로 설정해야되기 때문에 SDK 또한 prerelease 버전으로 배포하였습니다.

https://pub.dev/packages/kakao_flutter_sdk/versions/0.6.0-beta.1

위 링크를 참조해 주세요. 해당 prerelease 버전을 사용해 보시고 문제가 있으면 또 알려주세요.
