### ISSUE TITLE
iOS 에서 카카오톡 앱 설치 확인을 못하고 있습니다.

### ISSUE THREAD

**Issue by thruthesky** [kakao/kakao_flutter_sdk#48]
플러터 버전: 1.22.2
kakao_flutter_sdk 버전: 0.6.0-beta.1

테스트 디바이스:
iPhone 11 Max Pro, iPhone SE 2

isKakaoTalkInstalled() 가 항상 false 를 리턴합니다.

```
final installed = await isKakaoTalkInstalled(); // 앱이 설치, 실행되고 있어도, installed 의 값은 false.

final authCode = installed
   ? await AuthCodeClient.instance.requestWithTalk()
   : await AuthCodeClient.instance.request();
```

**Comment by serendipity1004** [comment]
저도 같은 현상이네요. 혹시 해결되면 솔루션 부탁드립니다.

**Comment by CoderSpinoza** [comment]
@thruthesky @serendipity1004

안녕하세요! 혹시 카카오톡 설치 확인이 되다가 최근에 안되기 시작한 이슈인가요?

설정하셨을 것 같긴 한데 그래도 확인차 문의드립니다. Info.plist 에 아래와 같이 등록하셨나요?

```xml
<key>LSApplicationQueriesSchemes</key>
  <array>
      <!-- common -->
      <string>kakao${native_app_key_here}</string>

      <!-- KakaoTalk login -->
      <string>kakaokompassauth</string>
      <string>storykompassauth</string>

      <!-- KakaoLink -->
      <string>kakaolink</string>         
      <string>kakaotalk-5.9.7</string>
  </array>
```

**Comment by CoderSpinoza** [comment]
@eunjin3786 https://github.com/kakao/kakao_flutter_sdk/issues/49 도 아마 위와 동일한 이슈일 것 같은데 확인 부탁드립니다!

**Comment by serendipity1004** [comment]
@CoderSpinoza 말씀하신 현상이 맞네요. 저같은경우 kakaokompassauth 를 kakaokompathauth로 스펠링 에러가 있었습니다.

**Comment by thruthesky** [comment]
네. 설정을 제대로 안했었네요.
말씀하신 설정 추가하니, 문제 해결되었습니다.
감사합니다.
