### ISSUE TITLE
알수 없는 에러

### ISSUE THREAD

**Issue by ktw1318** [kakao/kakao_flutter_sdk#50]
먼저 아래와 같은 버젼으로 진행하였으나 같은 에러로 진행이 안되서 문의 드립니다.

테스트 패키지 
-   kakao_flutter_sdk: ^0.5.2
 - kakao_flutter_sdk: ^0.6.0-beta.1

아래 에러 메시지가 뜨는데 내용도 이해가 안가고.. 어디서 문제인지 알수가 없는 상태 입니다. 

`Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
e: /Users/imac/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kakao_flutter_sdk-0.6.0-beta.1/android/src/main/kotlin/com/kakao/sdk/flutter/CustomTabsClient.kt: (61, 54): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ResolveInfo?
e: /Users/imac/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kakao_flutter_sdk-0.6.0-beta.1/android/src/main/kotlin/com/kakao/sdk/flutter/CustomTabsClient.kt: (62, 34): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ResolveInfo?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kakao_flutter_sdk:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1
`

[에러 이미지 ]

![image](https://user-images.githubusercontent.com/65937118/99253807-bd1b9f00-2854-11eb-847d-ede8bdc1402a.png)

[ 미니패스트]
![image](https://user-images.githubusercontent.com/65937118/99254200-521e9800-2855-11eb-914b-ab481c5b704b.png)

[ 저의 개발 환경 ]
![image](https://user-images.githubusercontent.com/65937118/99254288-7bd7bf00-2855-11eb-8f53-c225f3ab66ca.png)

[ 사용한 패키지 버젼 ]

  kakao_flutter_sdk: ^0.6.0-beta.1 #카카오 로그인 아래 까지 쭈욱 카카오톡 로그인 패키쥐
  dio: ^3.0.9
  json_annotation: ^3.1.0
  shared_preferences: ^0.5.7
  platform: ^3.0.0-nullsafety.2
  package_info: ^0.4.3 #빌드 버젼 확인하는 패키쥐

[app/build.gradle ]
![image](https://user-images.githubusercontent.com/65937118/99254637-fef91500-2855-11eb-8169-172e331a3c41.png)

[android/build.gradle]
![image](https://user-images.githubusercontent.com/65937118/99254676-10422180-2856-11eb-8a39-5084bc68ae9b.png)

무엇을 잘못했는지 어디서 수정을 해야 하는지 알수 있을련지요 

부디 도움 부탁드립니다.

**Comment by proghjy** [comment]
원본
```kotlin
val resolveInfo = context.packageManager.resolveActivity(intent, PackageManager.MATCH_DEFAULT_ONLY)
```

변경 후
```kotlin
val resolveInfo = context.packageManager.resolveActivity(intent, PackageManager.MATCH_DEFAULT_ONLY)!!
```

원본 코드에서 resolveInfo를 강제 언랩핑 해서 해결 하였습니다.

**Comment by proghjy** [comment]
@ktw1318  좀더 찾아보니 Android 11(API 30) 부터 패키지 공개 상태로 인해서 resolveActivity(,), resolveActivityInfo(,) 등의 반환이 null 이 될수 있음을 알수 있었습니다.

[stackoverflow](https://stackoverflow.com/a/62856745)
[package-visibility](https://developer.android.com/about/versions/11/privacy/package-visibility)

AndroidManfest.xml 파일에 `queries`를 추가해서 해결 가능하다고 는하는데...

아직 잘안되네요;

**Comment by wooxist** [comment]
PR 올려뒀는데 빨리 반영해줄지 모르겠네요.

**Comment by wooxist** [comment]
혹시나 빌드 안되시는 분들은 아래 코드로 수정하시면 될 겁니다.

`package com.kakao.sdk.flutter

import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.ServiceConnection
import android.content.pm.PackageManager
import android.net.Uri
import android.util.Log
import androidx.browser.customtabs.CustomTabsClient
import androidx.browser.customtabs.CustomTabsIntent
import androidx.browser.customtabs.CustomTabsService
import androidx.browser.customtabs.CustomTabsServiceConnection

/**
 * @author kevin.kang. Created on 2019-06-12..
 */
object CustomTabsCommonClient {
  @Throws(UnsupportedOperationException::class)
  fun openWithDefault(context: Context, uri: Uri): ServiceConnection? {
    val packageName = resolveCustomTabsPackage(context, uri)
        ?: throw UnsupportedOperationException("No browser supports custom tabs protocol on this device.")
    Log.d("CustomTabsCommonClient", "Choosing $packageName as custom tabs browser")
    val connection = object : CustomTabsServiceConnection() {
      override fun onCustomTabsServiceConnected(name: ComponentName, client: CustomTabsClient) {
        val builder = CustomTabsIntent.Builder()
            .enableUrlBarHiding().setShowTitle(true)
        val customTabsIntent = builder.build()
        customTabsIntent.intent.data = uri
        customTabsIntent.intent.setPackage(packageName)
        context.startActivity(customTabsIntent.intent)
      }

      override fun onServiceDisconnected(name: ComponentName?) {
        Log.d("CustomTabsCommonClient", "onServiceDisconnected: $name")
      }
    }
    val bound = CustomTabsClient.bindCustomTabsService(context, packageName, connection)
    return if (bound) connection else null
  }

  fun open(context: Context, uri: Uri) {
    CustomTabsIntent.Builder().enableUrlBarHiding().setShowTitle(true).build()
        .launchUrl(context, uri)
  }

  private fun resolveCustomTabsPackage(context: Context, uri: Uri): String? {
    var packageName: String? = null
    var chromePackage: String? = null
    // get ResolveInfo for default browser
    val intent = Intent(Intent.ACTION_VIEW, uri)
    val resolveInfo = context.packageManager.resolveActivity(intent, PackageManager.MATCH_DEFAULT_ONLY)
    val serviceIntent = Intent().setAction(CustomTabsService.ACTION_CUSTOM_TABS_CONNECTION)
    val serviceInfos = context.packageManager.queryIntentServices(serviceIntent, 0)
    for (info in serviceInfos) {
      // check if chrome is available on this device
      if (chromePackage == null && isPackageNameChrome(info.serviceInfo.packageName)) {
        chromePackage = info.serviceInfo.packageName
      }
      // check if the browser being looped is the default browser
      if (info.serviceInfo.packageName == resolveInfo?.activityInfo?.packageName) {
        packageName = resolveInfo?.activityInfo?.packageName
        break
      }
    }
    if (packageName == null && chromePackage != null) {
      packageName = chromePackage
    }
    return packageName
  }

  private fun isPackageNameChrome(packageName: String): Boolean {
    return chromePackageNames.contains(packageName)
  }

  private val chromePackageNames = arrayOf(
      "com.android.chrome",
      "com.chrome.beta",
      "com.chrome.dev")
}`

**Comment by CoderSpinoza** [comment]
@wooxist PR 머지하였습니다. 오늘 내일 중으로 배포하겠습니다. 더 빠르게 처리하지 못한 점 죄송합니다..!

**Comment by CoderSpinoza** [comment]
@wooxist @ktw1318 @proghjy 0.5.3 버전으로 배포하였습니다! 혹시 0.6.0 prerelease 버전 사용하고 계신 분 있을까요?

**Comment by JYeop** [comment]
@CoderSpinoza 
현재 0.5.3 버전이지만 다른 코드 부분에서 같은 타입문제가 나타납니다.

`/kakao_flutter_sdk-0.5.3/android/src/main/kotlin/com/kakao/sdk/flutter/CustomTabsClient.kt: (61, 68): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ActivityInfo?`

**Comment by ktw1318** [comment]
0.5.3 동일 에러 나네요.. 미치겠네요 정말 ㅠ.ㅠ; ;

아래 부분에서 에러 나서 주석 처리 해놓으니 최신단말기에서 로그인이 또 안되네요.. 어떻게 해야 하나요

      if (info.serviceInfo.packageName == resolveInfo?.activityInfo.packageName) {
        packageName = resolveInfo?.activityInfo?.packageName
        break
      }

**Comment by ktw1318** [comment]
> 원본 코드에서 `resolveInfo`를 강제 언랩핑 해서 해결 하였습니다.

이렇게 해놓으니 최신 안드로이드 기기에서 로그인이 안되는 문제가 발생됩니다.

**Comment by ktw1318** [comment]
> @wooxist @ktw1318 @proghjy 0.5.3 버전으로 배포하였습니다! 혹시 0.6.0 prerelease 버전 사용하고 계신 분 있을까요?

혹시 0.5.4 는 언제쯤 나오는걸까요.. 카카오 로그인, 최신 단말기에서(안드 11.0) 로그인이 안되는 문제 땜에 너무 힘드네요..

**Comment by CoderSpinoza** [comment]
@ktw1318 요 부분 이슈 다 해결되었나요?!

**Comment by proghjy** [comment]
@ktw1318 님...

AndroidManifest.xml 파일 상단에 아래 쿼리 추가 하세요
자세한 내용은 [Android 11의 패키지 공개 상태](https://developer.android.com/about/versions/11/privacy/package-visibility?hl=ko) 문서 참고 하시구요 @CoderSpinoza 님 이슈 클로즈 부탁드려요~
```xml
<queries>
    <package android:name="com.kakao.talk" />
</queries>
```
