### ISSUE TITLE
Implememting Kakao maps

### ISSUE THREAD

**Issue by ericel** [kakao/kakao_flutter_sdk#54]
Coming from google maps, I have to ask, any example of implementing the kakao maps api?
I have a use case where I have coordinates of two places, I want to create a polyline of these two places.
Is this even possible with this SDK?

**Comment by CoderSpinoza** [comment]
@ericel That is not possible with this SDK. Can you look into https://pub.dev/packages/flutter_kakao_map?

This SDK aims to handle only Kakao API and necessary functionalities (OAuth) to use the API. Map SDK requires native libraries and this is not something that this SDK wants to maintain.

If this answer satisfies your question, please close this issue :)
