### ISSUE TITLE
Execution failed for task ':kakao_flutter_sdk:compileDebugKotlin'. 에러가 발생합니다 

### ISSUE THREAD

**Issue by rivery811** [kakao/kakao_flutter_sdk#55]
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\kakao_flutter_sdk-0.5.3\android\src\main\kotlin\com\kakao\sdk\flutter\CustomTabsClient.kt: (61, 68): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ActivityInfo?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kakao_flutter_sdk:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

----------------------------------------------------------------------------------------------------------------------------------------------
에러 메세지는 다음과 같습니다 

CustomTabsClient.kt 의 61-63
//      if (info.serviceInfo.packageName == resolveInfo?.activityInfo.packageName) {
//        packageName = resolveInfo?.activityInfo?.packageName
//        break

을 주석처리하여 실행되나 에러메세지가 무엇때문인지 모르겠습니다

**Comment by neopjm109** [comment]
아래 동일한 이슈가 적혀있어서, 해결 된 줄 알았는데 저도 같은 현상으로 안되서 헤매고 있었어요 ㅠㅠ
정보 감사합니다!

**Comment by wooxist** [comment]
@neopjm109 @rivery811 우선 kakao_flutter_mirror 로 해보겠어요?

**Comment by JYeop** [comment]
https://github.com/kakao/kakao_flutter_sdk/pull/57#issue-559719292
해당부분 PR하였으니 금발 해결될 듯 합니다 ㅎ

**Comment by ktw1318** [comment]
동일 문제 생겨서 힘드네요

**Comment by CoderSpinoza** [comment]
@rivery811 @neopjm109 @JYeop 

이 부분 해결된 버전이 0.5.4 버전으로 배포되었는데요. 한번 확인해 보시고 해결되었으면 이슈 닫아주시겠어요?

**Comment by kinmt1234** [comment]
```
e: /Users/xxxx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kakao_flutter_sdk-0.5.2/android/src/main/kotlin/com/kakao/sdk/flutter/CustomTabsClient.kt: (18, 8): Redeclaration: CustomTabsCommonClient
e: /Users/xxxx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kakao_flutter_sdk-0.5.4/android/src/main/kotlin/com/kakao/sdk/flutter/CustomTabsClient.kt: (18, 8): Redeclaration: CustomTabsCommonClient
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':kakao_flutter_sdk:compileReleaseKotlin'.    
> Compilation error. See log for more details 
```

여전히 위와같은 에러가 발생합니다. 혹시 고쳐진거 맞을까요?

```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kakao_flutter_sdk: ^0.5.4
```

**Comment by neopjm109** [comment]
@CoderSpinoza 저는 확인 결과 문제 수정된 것 확인되었습니다.

**Comment by JYeop** [comment]
@CoderSpinoza 늦게나마 답변 드립니다. 확인 완료했습니다~! 해결 됐네욤
