### ISSUE TITLE
kakao adfit 기능 추가 계획이 있습니까?

### ISSUE THREAD

**Issue by BillyoDev** [kakao/kakao_flutter_sdk#58]
kakao adfit은 android, ios, web만 지원하고 있는데
flutter에서 바로 적용 가능한 sdk도 추가 할 계획이 있나요?

**Comment by CoderSpinoza** [comment]
@BillyoDev 안녕하세요, 해당 SDK는 https://developers.kakao.com 에서 제공하는 오픈 API를 제공하는 것이 목표입니다. 제가 해당 팀에 재직 중에 만든 SDK이기 때문에 카카오맵, adfit 등등은 포함되지 않습니다 ㅠ.ㅠ

당분간은 계획에 없지만, 한번 카카오 쪽이랑 소통을 해보도록 할게요..!
