### ISSUE TITLE
integration test를 위한 platform version 문제

### ISSUE THREAD

**Issue by proghjy** [kakao/kakao_flutter_sdk#59]
kakao_flutter_sdk 패키지는 현재 platform ^2.2.1을 사용하고 있습니다.

플러터에서 제공하는 [integration_test](https://pub.dev/packages/integration_test) 패키지는 `platform: ^3.0.0-nullsafety.2` 의존성을 가지기 때문에

두 패키지간의 의존성 충돌이 발생하네요 통합 테스트를 진행하는데 integration_test 패키지 사용이 필요한 상황이라  관련해서 검토 부탁드립니다.

이게 CI/CD 배포 하고 물려있어서 반영해주시면 정말 감사하겠습니다.

**Comment by CoderSpinoza** [comment]
@proghjy 

https://pub.dev/packages/kakao_flutter_sdk/versions/0.6.0-beta.2

해당 platform 버전은 prerelease 버전이어서 stable 버전에서는 서포트할 수 없고 kakao_flutter_sdk prerelease 버전에서 사용 가능합니다.

위 버전으로 사용해 보시겠어요?

**Comment by proghjy** [comment]
@CoderSpinoza 넵! 지금 바로 한번 테스트해볼게요 감사합니다~
