### ISSUE TITLE
Flutter 2 버전 대응 관련

### ISSUE THREAD

**Issue by fysoul17** [kakao/kakao_flutter_sdk#62]
안녕하세요,

금번 Flutter 2.0.0 버전이 stable로 출시 되면서 많은 패키지들이 nullsafety를 비롯하여 여러 업데이트들을 진행해 왔습니다.
특히 dio를 쓰는 몇몇 패키지들에서 nullsafety가 적용된 dio: '4.0.0-beta4' 버전을 쓰면서 카카오 패키지와 버전 충돌이 나고 있습니다.

dependency_overrides: 로 dio의 버전을 강제로 적용하면 아래와 같은 오류 때문에 적용하기 힘든 점이 있습니다.
(dio에서 이제 RequestOptions를 Option으로 변경)

```/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/kakao_flutter_sdk-0.6.0-beta.1/lib/src/auth/access_token_interceptor.dart:45:52: Error: The argument type 'RequestOptions' can't be assigned to the parameter type 'Options'.
 - 'RequestOptions' is from 'package:dio/src/options.dart' ('/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/dio-4.0.0-beta4/lib/src/options.dart').
 - 'Options' is from 'package:dio/src/options.dart' ('/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/dio-4.0.0-beta4/lib/src/options.dart').

        return _dio.request(options.path, options: options);
```

카카오 beta 버전을 dio의 nullsafety 가 적용된 버전으로 업데이트 하실 예정은 없으신가요?

아래 다른분들을 위해 소개해주신 패키지중에 [firebase_auth_simplify](https://pub.dev/packages/firebase_auth_simplify)를 Flutter 2버전과 nullsafety를 위해 사용자분들께 업데이트를 해드려야하는데, 해당 이슈 때문에 지연이 되고 있습니다~ 꼭 좀 부탁드리겠습니다~

**Comment by eugenejeonme** [comment]
작성자분도 좋은일 하시는 것 같네요.
제가 임시로 Flutter 2.x 버전에서 사용하려고 포크한 코드다. "로그인" 과 "검색" 기능을 사용하기위해 수작업했습니다. 
임시방편으로 사용이 가능하시리라 생각되어 주소 남깁니다.

https://github.com/eugenejeonme/kakao_flutter_sdk

**Comment by fysoul17** [comment]
@eugenejeonme 

공유 감사드립니다. 다만 publishable package, 즉 package에 들어가는 dependency다 보니 일반 git url 은 적용되지 못합니다 ㅠㅠ...
결국 카카오 패키지를 업데이트 해주셔야 새 패키지에 디펜던시를 적용해서 제가 업그레이드 된 버전을 올려드릴 수 있거든요..

**Comment by eugenejeonme** [comment]
> @fysoul17
> 
> [https://github.com/kakao/kakao_flutter_sdk/tree/feature/null-safety](https://github.com/kakao/kakao_flutter_sdk/tree/feature/null-safety?rgh-link-date=2021-03-10T01%3A09%3A06Z)
> 
> 위 브랜치에서 대응을 하고 있고, 최소한의 테스트 후 금요일 전까지 배포할 수 있도록 하겠습니다. 카카오 퇴사 후에 다른 일을 하고 있어서 더 빨리 대응하기가 쉽지 않네요 ㅠ.ㅠ 불편을 드려 죄송합니다.
> 
> API를 wrapping한 SDK의 경우에는 API의 정책이 언제든 바뀔 수 있기 때문에 (필드의 존재 유무) null safety를 도입하기 애매한 부분이 있긴 합니다. 그렇다고 전체를 nullable로 지정하기 싫은 마음도 있구요. 이 부분은 계속 고민 후에 우선 beta 버전들에서 조금씩 고민해서 개선하도록 하겠습니다.
> 
> @eugenejeonme
> 
> 임시방편을 마련해 주셔서 감사합니다. 추후에는 PR 만들어주셔서 이 저장소에 contribute 해주시는것도 좋을 것 같아요 :)

네! 감사합니다.
혹시 Contributing 가이드라인 따라야 하는거지요? 이메일 보내야 하는 것 말입니다. ^^;;

**Comment by eugenejeonme** [comment]
> 성자분도 좋은일 하시는 것 같네요.
> 제가 임시로 Flutter 2.x 버전에서 사용하려고 포크한 코드입니다. "로그인" 과 "검색" 기능을 사용하기위해 수작업했습니다.
> 임시방편으로 사용이 가능하시리라 생각되어 주소 남깁니다.

Flutter 2.x 대응 티켓을 팔로우업하시는 분들이 많은 것 같아서, 카카오팀이 만든 브랜치에서 다시 포크한 코드로 주소 남겨드립니다.

[eugenejeonme/kakao_flutter_sdk@feature/null-safety](https://github.com/kakao/kakao_flutter_sdk/tree/feature/null-safety)

([feature/null-safety](https://github.com/kakao/kakao_flutter_sdk/tree/feature/null-safety) branch 에 기반해서 다시 빌드 가능한 코드로 변경했습니다.)

변경한 주요내용은 아래와 같습니다.
- Coord 클래스의 x, y 값에 대한 JsonSerializer 변환 타입 변경
  - 다른 Model 들의 베이스로 사용되는 Coord 의 x, y 값은 nullable 할 수 없다고 판단하여, Json 파싱할 때 null 이면 0 값이 들어올 수 있도록 JsonSerializer 변환 함수를 변경하였습니다.
  - 기존: stringToNullableDouble
  - 변경: stringToDouble

**Comment by fysoul17** [comment]
@CoderSpinoza
 혹시 아직 업데이트 예정이 없으신지요ㅠㅠ

**Comment by fysoul17** [comment]
@CoderSpinoza 
업데이트 감사드립니다~

덕분에 [firebase_auth_simplify](https://pub.dev/packages/firebase_auth_simplify/versions/3.0.0-nullsafety.0) 패키지를 업데이트 할 수 있었습니다 :)
