### ISSUE TITLE
플러터 2.0 버전에서 작동하지 않습니다.

### ISSUE THREAD

**Issue by kim-mini6** [kakao/kakao_flutter_sdk#64]
최대한 빨리 업데이트 해주시면 감사하겠습니다!

**Comment by CoderSpinoza** [comment]
@kim-mini6 

https://pub.dev/packages/kakao_flutter_sdk/versions/0.6.0-beta.2

위 베타버전을 사용하셔도 작동하지 않나요?

**Comment by kim-mini6** [comment]
베타버전으로 사용하면 잘 되는데 여러 패키지들이 충돌이 나서 사용을 못합니다 ㅠㅠ

**Comment by CoderSpinoza** [comment]
@kim-mini6 에러 로그를 올려주시면 도움이 될 것 같아요. 베타버전은 아마 베타버전끼리만 사용하셔야 될거에요.. 사용하시는 패키지들에서 null-safety 적용된 베타 버전들이 배포가 안된 상태라면 2.0을 아직 안올라가시는게 어떨까 싶어요 ㅠ.ㅠ

**Comment by cas-beom** [comment]
사용하기 지~짜 어렵네요 ..
`* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.kakao.sdk:v2-user:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/v2-user/2.4.2/v2-user-2.4.2.pom
       - https://jcenter.bintray.com/com/kakao/sdk/v2-user/2.4.2/v2-user-2.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/kakao/sdk/v2-user/2.4.2/v2-user-2.4.2.pom
     Required by:
         project :app
   > Could not find com.kakao.sdk:v2-talk:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/v2-talk/2.4.2/v2-talk-2.4.2.pom
       - https://jcenter.bintray.com/com/kakao/sdk/v2-talk/2.4.2/v2-talk-2.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/kakao/sdk/v2-talk/2.4.2/v2-talk-2.4.2.pom
     Required by:
         project :app
   > Could not find com.kakao.sdk:v2-story:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/v2-story/2.4.2/v2-story-2.4.2.pom
       - https://jcenter.bintray.com/com/kakao/sdk/v2-story/2.4.2/v2-story-2.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/kakao/sdk/v2-story/2.4.2/v2-story-2.4.2.pom
     Required by:
         project :app
   > Could not find com.kakao.sdk:v2-link:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/v2-link/2.4.2/v2-link-2.4.2.pom
       - https://jcenter.bintray.com/com/kakao/sdk/v2-link/2.4.2/v2-link-2.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/kakao/sdk/v2-link/2.4.2/v2-link-2.4.2.pom
     Required by:
         project :app
   > Could not find com.kakao.sdk:v2-navi:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/v2-navi/2.4.2/v2-navi-2.4.2.pom
       - https://jcenter.bintray.com/com/kakao/sdk/v2-navi/2.4.2/v2-navi-2.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/kakao/sdk/v2-navi/2.4.2/v2-navi-2.4.2.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Exception: Gradle task assembleDebug failed with exit code 1`


`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "kr.co.cassystem"
        minSdkVersion 26
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            proguardFiles 'proguard-kakao.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation "com.kakao.sdk:v2-user:2.4.2" // 카카오 로그인
    implementation "com.kakao.sdk:v2-talk:2.4.2" // 친구, 메시지(카카오톡)
    implementation "com.kakao.sdk:v2-story:2.4.2" // 카카오스토리
    implementation "com.kakao.sdk:v2-link:2.4.2" // 메시지(카카오링크)
    implementation "com.kakao.sdk:v2-navi:2.4.2" // 카카오내비
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
}
`

**Comment by cas-beom** [comment]
flutter에서 SDK 사용하기 진심 어려움 ~~~~~ 하~ 
번거롭더라도 REST api 로 구현 하는게 편합니다.
'* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.kakao.sdk:v2-user:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/v2-user/2.4.2/v2-user-2.4.2.pom
       - https://jcenter.bintray.com/com/kakao/sdk/v2-user/2.4.2/v2-user-2.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/kakao/sdk/v2-user/2.4.2/v2-user-2.4.2.pom
     Required by:
         project :app
   > Could not find com.kakao.sdk:v2-talk:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/v2-talk/2.4.2/v2-talk-2.4.2.pom
       - https://jcenter.bintray.com/com/kakao/sdk/v2-talk/2.4.2/v2-talk-2.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/kakao/sdk/v2-talk/2.4.2/v2-talk-2.4.2.pom
     Required by:
         project :app
   > Could not find com.kakao.sdk:v2-story:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/v2-story/2.4.2/v2-story-2.4.2.pom
       - https://jcenter.bintray.com/com/kakao/sdk/v2-story/2.4.2/v2-story-2.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/kakao/sdk/v2-story/2.4.2/v2-story-2.4.2.pom
     Required by:
         project :app
   > Could not find com.kakao.sdk:v2-link:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/v2-link/2.4.2/v2-link-2.4.2.pom
       - https://jcenter.bintray.com/com/kakao/sdk/v2-link/2.4.2/v2-link-2.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/kakao/sdk/v2-link/2.4.2/v2-link-2.4.2.pom
     Required by:
         project :app
   > Could not find com.kakao.sdk:v2-navi:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kakao/sdk/v2-navi/2.4.2/v2-navi-2.4.2.pom
       - https://jcenter.bintray.com/com/kakao/sdk/v2-navi/2.4.2/v2-navi-2.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/kakao/sdk/v2-navi/2.4.2/v2-navi-2.4.2.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Exception: Gradle task assembleDebug failed with exit code 1'


`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "kr.co.cassystem"
        minSdkVersion 26
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            proguardFiles 'proguard-kakao.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation "com.kakao.sdk:v2-user:2.4.2" // 카카오 로그인
    implementation "com.kakao.sdk:v2-talk:2.4.2" // 친구, 메시지(카카오톡)
    implementation "com.kakao.sdk:v2-story:2.4.2" // 카카오스토리
    implementation "com.kakao.sdk:v2-link:2.4.2" // 메시지(카카오링크)
    implementation "com.kakao.sdk:v2-navi:2.4.2" // 카카오내비
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
}
`

**Comment by cas-beom** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.867], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.1)
[√] Connected device (3 available)

**Comment by mbkim95** [comment]
@kim-mini6  flutter 2.0 대응한 `kakao_flutter_sdk 0.6.1`이 배포했습니다. 해당 버전 적용 후에도 이슈가 발생하면 다시 제보 부탁드리겠습니다

**Comment by kim-mini6** [comment]
네 알겠습니다 감사합니다!!
