### ISSUE TITLE
AuthApiClient.instance.hasToken() 함수가 없나요?

### ISSUE THREAD

**Issue by JihyeJung-Work** [kakao/kakao_flutter_sdk#67]
안녕하세요, 카카오 로그인을 할 때 이 사용자가 처음 가입하는 사용자인지 아니면 이미 가입되어 로그인만 하면 되는 사용자인지 구분하기 위해 안드로이드에서는 hasToken()함수를 쓰는 것으로 알고 있는데 이 플러터 라이브러리에서는 찾아볼 수가 없습니다. 플러터에서는 어떻게 해야하나요?

**Comment by 2jeje** [comment]
안녕하세요? 기존 SDK 기능을 Flutter SDK에 Migration 작업 진행 중이며 hasToken() 도 포함 될 예정 입니다.
감사합니다.

**Comment by JihyeJung-Work** [comment]
@2jeje  혹시 대충이라도 언제쯤 완료될지 알 수 있을까요?

**Comment by mbkim95** [comment]
@JihyeJung-Work 
안녕하세요~ 현재 `hasToken()` 함수 추가 작업은 완료했고, 해당 버전은 늦어도 다다음주 전에는 배포할 계획입니다.  감사합니다 :)

**Comment by JihyeJung-Work** [comment]
@mbkim95  감사합니다~
