### ISSUE TITLE
shared_preferences is too old.

### ISSUE THREAD

**Issue by Jay-flow** [kakao/kakao_flutter_sdk#68]
I understand that this package is dependent on shared_preferences.
However, the shared_preferences package is too old and results in an installation error.

```
[flow_chat] flutter pub get
Running "flutter pub get" in flow_chat...                       
Because kakao_flutter_sdk >=0.5.0 <0.6.0-beta.2 depends on shared_preferences ^0.5.7 and flow_chat depends on shared_preferences ^2.0.5, kakao_flutter_sdk >=0.5.0 <0.6.0-beta.2 is forbidden.

So, because flow_chat depends on kakao_flutter_sdk ^0.5.4, version solving failed.
pub get failed (1; So, because flow_chat depends on kakao_flutter_sdk ^0.5.4, version solving failed.)
exit code 1
```

The current version of the shared_preferences package is 2.0.5.
I don't think recent projects will use version 0.5.7 😭

**Comment by mbkim95** [comment]
Hello. [kakao_flutter_sdk 0.6.0-beta.2](https://pub.dev/packages/kakao_flutter_sdk/versions/0.6.0-beta.2) applied null safety is in deployment. This version uses shared_preferences 2.0.3, so please note that.

**Comment by Jay-flow** [comment]
Thx :)

**Comment by mbkim95** [comment]
@Jay-flow `kakao_flutter_sdk 0.6.0-beta.2` had some issues, so i fixed it. Now, `kakao_flutter_sdk 0.6.1` is in deployment. So you can use `0.6.1` instead.

**Comment by Jay-flow** [comment]
@mbkim95 Okay, I'll do that. Thaks :)
