### ISSUE TITLE
안드로이드에서 isKakaoTalkInstalled가 제대로 동작하지 않습니다.

### ISSUE THREAD

**Issue by ooni0921** [kakao/kakao_flutter_sdk#69]
Android 11인 실제 디바이스에서 테스트 했을 때, 분명 카카오톡이 설치되었음에도 설치 여부를 체크하지 못하는 현상이 발생합니다.

저랑 비슷한 사례가 있어 참고링크 보내드립니다.
https://it-banlim.tistory.com/31

compileSdkVersion과 targetSdkVersion의 값을 29로 변경하면 정상작동하긴 하지만
현재 개발중인 앱에서는 compileSdkVersion과 targetSdkVersion의 값을 30으로 사용해야 하는 상황입니다.

**Comment by 2jeje** [comment]
안녕하세요?  
Android 11 부터 외부 package 호출 시 manifest 에 package 명 적용 해야 되는 사항이 생겨서요. 반영 하도록 하겠습니다

참고) https://developer.android.com/training/basics/intents/package-visibility?hl=ko

**Comment by mbkim95** [comment]
@ooni0921 안녕하세요~ 현재 제보주신 이슈 대응했고, 늦어도 다다음주 전에는 배포할 계획입니다. 감사합니다

**Comment by mbkim95** [comment]
@ooni0921 `kakao_flutter_sdk 0.6.1` 배포되었고, 해당 이슈 수정했습니다~
