### ISSUE TITLE
카카오톡 계정 미연동 상태의 로그인 취소 감지

### ISSUE THREAD

**Issue by jeiea** [kakao/kakao_flutter_sdk#72]
`AuthCodeClient.instance.requestWithTalk()`으로 로그인을 요청했을 때 카카오톡에 로그인되지 않은 상태면 로그인 화면이 나오고 바로 인증할 수 없습니다. 이 상태에서 백 버튼으로 돌아가면 플러터에선 받아온 Future가 종료되지 않습니다.
구버전 카카오톡에선 NotSupportError를 반환할 때 웹 로그인 화면을 띄워줄 수 있을 것 같지만 현재는 정석이 보이지 않습니다. 이 부분 개선가능할까요?

**Comment by mbkim95** [comment]
안녕하세요. 

현재 `kakao_flutter_sdk` 에서는 말씀하신 경우에 `PlatformException`이 발생하도록 구현되어있습니다.

```dart
  _loginWithTalk() async {
    try {
      var code = await AuthCodeClient.instance.requestWithTalk();
      await _issueAccessToken(code);
    } on PlatformException {
      _loginWithKakao();
    } catch (e) {
      print(e);
    }
  }

_loginWithKakao() async {
    try {
      var code = await AuthCodeClient.instance.request();
      await _issueAccessToken(code);
    } catch (e) {
      print(e);
    }
  }
```
위와 같은 방식으로 구현하시면 카카오톡이 로그인되어 있지 않은 경우에 카카오 계정으로 로그인하도록 구현이 가능합니다.

감사합니다.

**Comment by jeiea** [comment]
iOS 환경에서 로그인이 안 된 상황에서 `PlatformException`이 발생하는지 확인 부탁드립니다. 제 기억으론 안드로이드와 iOS 둘 다 예외가 나진 않았던 것 같은데 일단 지금 재현 가능했던 iOS 기기 영상을 첨부합니다. 예제 만들기 귀찮아서 실제 프로젝트 영상을 쓴 점 양해부탁드립니다. 확인하시면 영상은 제거하겠습니다.
[영상 링크](https://www.dropbox.com/s/2riu7prc5dn49xr/kakao_login_demo.mp4?dl=0)
버전은 0.6.1을 사용했습니다. 코드는 제시해주신 것과 비슷합니다.

**Comment by mbkim95** [comment]
@jeiea 영상은 확인했고, 해당 이슈는 빠른 시일 내에 확인해보겠습니다.

**Comment by mbkim95** [comment]
@jeiea 안녕하세요 

현재 ios 카카오톡 스펙상 로그인 여부를 파악할 수 없는 것 확인했습니다.
```
_loginWithKakao() async {
    try {
      var code = await AuthCodeClient.instance.request();
      await _issueAccessToken(code);
    } catch (e) {
      print(e);
    }
  }

  _loginWithTalk() async {
    try {
      var code = await AuthCodeClient.instance
          .requestWithTalk()
          .timeout(Duration(seconds: 5));
      await _issueAccessToken(code);
    } on TimeoutException {
      _loginWithKakao();
    } catch (e) {
      print(e);
    }
  }
```
따라서 다음과 같은 방식으로 임의의 시간을 설정해 카카오 계정 로그인으로 전환하는 방식으로 구현해야할 것 같습니다.

이슈 제보 감사합니다

**Comment by jeiea** [comment]
여기선 어쩔 수 없는 거군요. 일단 닫겠습니다.
