### ISSUE TITLE
[ios] kakao_flutter_sdk: 0.6.1 에서 카카오앱을 이용한 로그인 이슈

### ISSUE THREAD

**Issue by Heewookji** [kakao/kakao_flutter_sdk#73]
안녕하세요, 플러그인을 만들어주신 덕분에 카카오톡 관련 기능을 쉽게 구현하고 있습니다. 감사합니다.
다만 로그인 구현 도중 한 가지 이슈가 발생하여 질문드립니다.

ios에서 `await isKakaoTalkInstalled()`를 통해 앱 설치 여부까지 잘 확인하고
`await AuthCodeClient.instance.requestWithTalk()`를 호출하여 authCode를 받아오는데
여기에서 먹통이 됩니다. 
제 앱에서 카카오 앱으로 전환하고, 로그인 기능을 수행한 뒤 다시 자동으로 저의 앱으로 돌아오는 것까진 잘 되는데
돌아온 이후, 어떤 Exception이나 error 없이 멈춰있습니다.
하지만 앱이 아닌, 브라우저(`await AuthCodeClient.instance.request()`)를 이용한 로그인을 수행하면 정상적으로 잘 작동됩니다.
혹시 제가 잘못 적용한 부분이 있을까요? 확인부탁드립니다!

- 코드

```dart
  Future<Either<AuthFailure, String>> kakaoLogin() async {
    try {
      final installed = await isKakaoTalkInstalled();
      final authCode = installed
          ? await AuthCodeClient.instance.requestWithTalk()
          : await AuthCodeClient.instance.request();
      final accessToken = await AuthApi.instance.issueAccessToken(authCode);
      unawaited(AccessTokenStore.instance.toStore(accessToken));
      return right(
        await _authApiClient.getAuthTokenByProviderToken(
            accessToken.accessToken, AuthProvider.kakao),
      );
    } on KakaoException catch (e) {
      return left(const AuthFailure.providerError());
    } on DioError catch (e) {
      return left(const AuthFailure.serverError());
    } on PlatformException catch (e) {
      return left(const AuthFailure.cancelledByUser());
    }
  }
```

info.plist 입니다. [ios setting](https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios-v1#plist)에서
명시된 설정은 다 적용한 것 같습니다.

```
	<key>CFBundleURLTypes</key>
	<array>
            <dict>
	        <key>CFBundleTypeRole</key>
	        <string>Editor</string>
	        <key>CFBundleURLSchemes</key>
	        <array>
                    <string>$(KAKAO_APP_URL_SCHEME)</string>
	        </array>
            </dict>
	</array>
	<key>LSApplicationQueriesSchemes</key>
	    <array>
	        <string>$(KAKAO_APP_URL_SCHEME)</string>
                <string>kakaokompassauth</string>
                <string>storykompassauth</string>
                <string>kakaolink</string>
                <string>kakaotalk-5.9.7</string>
                <string>storylink</string>
	        <string>kakaotalk</string>
	    </array>
```

**Comment by mbkim95** [comment]
안녕하세요 [kakao developers](https://developers.kakao.com/)에 들어가셔서 로그인 구현하려고 하는 앱의 앱id 알려주시면 서버 로그 확인해보겠습니다.

**Comment by mbkim95** [comment]
@Heewookji 안녕하세요! [Kakao Developers](http://developers.kakao.com/)에서 '내 어플리케이션' 들어가셔서 현재 로그인 구현 중인 앱ID 알려주시면 로그 확인해보겠습니다.

**Comment by Heewookji** [comment]
@mbkim95 안녕하세요! `ID 65790`이라고 나와 있습니다. 확인 감사드립니다.

**Comment by mbkim95** [comment]
@Heewookji 서버 로그를 확인해봤는데 `AuthApi.issueAccessToken()` 요청이 서버로 들어오지 않는 것 같아요. 서버 상에서는 `authCode`를 정상적으로 발급하는 것 확인했는데, 카카오톡으로 로그인을 시도했을 때 서버로부터 `authCode` 를 제대로 받아오는지 확인 부탁드리겠습니다.

**Comment by Heewookji** [comment]
@mbkim95 authCode 받아올 때, 설정 상 문제가 있었나보네요. 확인해보겠습니다.
감사합니다.

**Comment by TykanN** [comment]
@Heewookji 혹시 해결되셨나요?
기존에 서비스 중인 버전에서 모두 정상적으로 작동했었는데, 새로운 빌드를 개발 중에 requestWithTalk()만 먹통이 됐네요.
증상은 적어주신 이슈와 동일합니다. 어떠한 error, exception 없이 해당 라인에서 코드가 멈춥니다.

**Comment by Heewookji** [comment]
@TykanN 브라우저 기능은 작동되고 있어서 일단 다른 기능으로 넘어갔습니다. (해결 아직 못했습니다)
말씀하신 내용과 마찬가지로, 기존 프로젝트에서는 잘 됐었는데 nullsafety로 dart 버전 업데이트 한 프로젝트는 해당 이슈가 발생했습니다.
똑같은 증상이 발견되는 것을 보니 ios 설정 관련해서는 아닌 것 같습니다.
제가 마지막으로 살펴봤을 때, 
```dart
Future<String> _openKakaoTalk(String clientId, String redirectUri) async {
    final redirectUriWithParams = await _channel.invokeMethod<String>("authorizeWithTalk",
        {"client_id": clientId, "redirect_uri": redirectUri});
        if (redirectUriWithParams != null) return redirectUriWithParams;
        throw KakaoClientException("OAuth 2.0 redirect uri was null, which should not happen.");
  }
```
`_channel.invokeMethod` 메서드를 호출하고 리턴하며 아무 결과값(error, exception 포함)도 가져오지 못했습니다.

**Comment by mbkim95** [comment]
@TykanN 안녕하세요. 현재 저희쪽 테스트 환경에서는 해당 이슈가 재현되지 않아 정확한 원인을 파악하지 못했는데요, 
이슈 발생하신 앱 ID 알려주시면 다시 한번 원인을 확인해보겠습니다.

**Comment by beomjo** [comment]
동일한 현상이 발생합니다.
iOS에서 `requestWithTalk()`를 호출하였을때 authCode를 얻어오지 못하고 있습니다.
앱 ID는 `490713`입니다

**Comment by mbkim95** [comment]
@beomjo 안녕하세요~ 댓글에 남겨주신 앱 ID로 서버 로그를 조회해봤는데요, 로그를 보고 판단하기로는 스킴이 제대로 설정되어있지 않은 것 같습니다. [Info.plist 설정](https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios#set-plist) 페이지를 참고하셔서 스킴 설정 후 로그인 시도 부탁드립니다.

**Comment by TykanN** [comment]
제 환경에서 해당 이슈가 생긴 원인을 찾았습니다.
저는 null-safety 버전이 아니라 flutter v1 호환 최신 버전을 이용 중이라 다른 분들과는 원인이 상이할 수 있습니다.

딥링크를 통한 라우팅을 위해 iOS의 AppDelegate.swift 파일에서 application function을 override 한 부분이 원인이였습니다.
카카오톡 로그인 시 카카오톡으로 이동했다가 다시 본 앱을 돌아오면서 카카오 플러그인의 _channel.invokedMethod 에서 핸들링 되지 않고
override한 부분에서 콜백된 파라미터를 핸들링하는 것으로 확인됩니다.

- 카카오 플러그인에서 native function
`UIApplication.shared.open(url, options: [:]) { (openResult) in
            if (!openResult) {
                result(FlutterError(code: "OPEN_URL_ERROR", message: "Failed to open KakaoTalk.", details: nil))
            }
        }`
 
- 원인이 된 AppDelegate.swift 부분
 `override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    AppsFlyerAttribution.shared()!.handleOpenUrl(url, options: options)
    return true
  }`

**Comment by Heewookji** [comment]
> 제 환경에서 해당 이슈가 생긴 원인을 찾았습니다.
> 저는 null-safety 버전이 아니라 flutter v1 호환 최신 버전을 이용 중이라 다른 분들과는 원인이 상이할 수 있습니다.
> 
> 딥링크를 통한 라우팅을 위해 iOS의 AppDelegate.swift 파일에서 application function을 override 한 부분이 원인이였습니다.
> 카카오톡 로그인 시 카카오톡으로 이동했다가 다시 본 앱을 돌아오면서 카카오 플러그인의 _channel.invokedMethod 에서 핸들링 되지 않고
> override한 부분에서 콜백된 파라미터를 핸들링하는 것으로 확인됩니다.
> 
> * 카카오 플러그인에서 native function
> 
> ```
>        UIApplication.shared.open(url, options: [:]) { (openResult) in
>             if (!openResult) {
>                 result(FlutterError(code: "OPEN_URL_ERROR", message: "Failed to open KakaoTalk.", details: nil))
>             }
>         }
> ```
> 
> * 원인이 된 AppDelegate.swift 부분
> 
> ```
> override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
>     AppsFlyerAttribution.shared()!.handleOpenUrl(url, options: options)
>     return true
>   }
> ```

해결 방법 공유 감사합니다! null safety도 동일한 듯 합니다.
저도 AppDelegate.swift에서 application function을 override했었고, 해당 코드 없이 카톡앱을 이용한 로그인이 성공합니다.
이슈 닫겠습니다.

**Comment by TykanN** [comment]
@Heewookji 동일하다니 다행입니다!
저 같은 경우에는 override된 코드를 지우지 않고 해당 부분에 super.application 을 호출해서 기존 + 카카오 플러그인 모두 정상적으로
작동되는 것을 확인했습니다.

``` swift
  override func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
    AppsFlyerAttribution.shared()!.handleOpenUrl(url, sourceApplication: sourceApplication, annotation: annotation);
  
    return super.application(application, open: url, sourceApplication: sourceApplication, annotation: annotation)
  }
```
iOS 네이티브 쪽은 잘 몰라서 이 방법이 완벽한 해결책인지는 모르겠습니다.
혹시 더 나은 해결책을 아신다면 공유 부탁드리겠습니다. 🙏

**Comment by beomjo** [comment]
> 제 환경에서 해당 이슈가 생긴 원인을 찾았습니다.
> 저는 null-safety 버전이 아니라 flutter v1 호환 최신 버전을 이용 중이라 다른 분들과는 원인이 상이할 수 있습니다.
> 
> 딥링크를 통한 라우팅을 위해 iOS의 AppDelegate.swift 파일에서 application function을 override 한 부분이 원인이였습니다.
> 카카오톡 로그인 시 카카오톡으로 이동했다가 다시 본 앱을 돌아오면서 카카오 플러그인의 _channel.invokedMethod 에서 핸들링 되지 않고
> override한 부분에서 콜백된 파라미터를 핸들링하는 것으로 확인됩니다.
> 
> * 카카오 플러그인에서 native function
> 
> ```
>        UIApplication.shared.open(url, options: [:]) { (openResult) in
>             if (!openResult) {
>                 result(FlutterError(code: "OPEN_URL_ERROR", message: "Failed to open KakaoTalk.", details: nil))
>             }
>         }
> ```
> 
> * 원인이 된 AppDelegate.swift 부분
> 
> ```
> override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
>     AppsFlyerAttribution.shared()!.handleOpenUrl(url, options: options)
>     return true
>   }
> ```

저도 공유해주신 해결 방법으로 잘 동작하네요 !
감사합니다  👍 👍 👍 👍
