### ISSUE TITLE
AuthCodeClient.instance.requestWithTalk() 호출 시 오류

### ISSUE THREAD

**Issue by gracegyu** [kakao/kakao_flutter_sdk#74]
카카오톡이 설치 되어 있는 경우 AuthCodeClient.instance.requestWithTalk()를 호출하여 로그인을 시도해 보고 있습니다.
이때 카카오톡이 열리면서 로그인 창이 열리는 것처럼 보이다가 바로 로그인 창이 닫히면서 로그인을 할 수 없습니다. 
테스트 환경은 아이폰11(iOS 14.4.2)입니다.
동영상을 첨부합니다.

https://user-images.githubusercontent.com/797082/116957564-1d06e480-acd3-11eb-9fed-89cd5d245659.mp4

flutter doctor -v 

[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-KR)
    • Flutter version 1.26.0-1.0.pre at /Users/gracegyu/dev/flutter
    • Framework revision 63062a6443 (5 months ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gracegyu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio 4.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Raymond’s iPhone11 (mobile) • 00008030-001555220CE9802E            • ios        • iOS 14.4.2
    • iPhone 8 (mobile)           • 107E5E03-EBE2-4648-B684-0A61E21D92FE • ios        • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)             • macos                                • darwin-x64 • macOS 11.2.3 20D91 darwin-x64

• No issues found!

**Comment by mbkim95** [comment]
안녕하세요~

사용 중이신 카카오 sdk 버전과 카카오톡 로그인 구현 부분 코드 첨부 부탁드려요.

**Comment by gracegyu** [comment]
dependencies:
  kakao_flutter_sdk: ^0.5.4
------------------------------------------------
```
....
import 'package:kakao_flutter_sdk/auth.dart';
import 'package:kakao_flutter_sdk/user.dart';


class LoginPage extends StatefulWidget {
  LoginPage({
    Key key,
    this.logout = false
  }) : super(key: key);
  final bool logout;

  @override
  _LoginPage createState() => _LoginPage();
}

class _LoginPage extends State<LoginPage> {
  ...
  bool _isKakaoTalkInstalled = false;
  int kakaoId;
  int i=0;
  bool bLogined = false;

  @override
  void initState() {
    super.initState();

    KakaoContext.clientId = 'af151fe68194fd3fbd408286ea70b9fd';
    KakaoContext.javascriptClientId = '8d8dc3711774ac698f64592efc46c01c';
    _initKakaoTalkInstalled();
    ...
  }

  @override
  void dispose() {
    super.dispose();
  }

  _initKakaoTalkInstalled() async {
    final installed = await isKakaoTalkInstalled();
    setState(() {
      _isKakaoTalkInstalled = installed;
    });
  }

  _loginWithKakao() async {
    try {
      var code = await AuthCodeClient.instance.request();
      await _signInKakao(code);
    } catch (e) {
      print("AuthCodeClient.instance.request Error => $e");
    }
  }

  _loginWithTalk() async {
    try {
      var code = await AuthCodeClient.instance.requestWithTalk();
      await _signInKakao(code);
    } on KakaoAuthException catch (e) {
      print("KakaoAuthException $e");
    } on KakaoClientException catch (e) {
      print("KakaoClientException $e");
    } catch (e) {
      print("catch Exception $e");
    }
  }

  _singInProcess({String type, String idToken}) async {
    // my login code using REST API
    ......
  }

  Future<bool> _signInKakao(String authCode) async {
    try {
      var token = await AuthApi.instance.issueAccessToken(authCode);
      AccessTokenStore.instance.toStore(token);
      var tokenInfo = await UserApi.instance.accessTokenInfo();
      kakaoId = tokenInfo.id;

      bool bRet = await _singInProcess(type:"kakao", idToken: kakaoId.toString());
      return bRet;

    } catch (e) {
      print("error on issuing access token: $e");
    }
    return false;
  }


  @override
  Widget build(BuildContext context) {
    KakaoContext.clientId = 'my Kakao client Id';

    return Scaffold(
    body: Center(
      child: Container(
        constraints: const BoxConstraints.expand(),
        child: Stack(
          children: [
            Align(
                alignment: Alignment.center,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    ....
                    Container(
                      child: ImageTextRowButton(
                          width: 300,
                          height: 36,
                          radius: 4,
                          padding: 16,
                          innerPadding: 7,
                          imageWidget : svgIcon('kakao'),
                          text : "Kakao 간편 로그인",
                          buttonColor: Colors.orange,
                          textColor: Colors.white,
                          callback :
                            _isKakaoTalkInstalled ? _loginWithTalk : _loginWithKakao
                      ),
                    ),
                  ],
                )
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

**Comment by mbkim95** [comment]
혹시 디벨로퍼스 앱 id와 사용 중인 flutter sdk 버전은 어떻게 되시나요?

**Comment by gracegyu** [comment]
앱id : af151fe68194fd3fbd408286ea70b9fd
flutter sdk 버전 : 1.26.0-1.0.pre

**Comment by mbkim95** [comment]
첨부해주신 키 값은 앱 id가 아닌 앱 키로 보안 상 문제가 될 수 있어서 삭제한 것 양해 부탁드립니다.

앱 id는 [카카오 디벨로퍼스](https://developers.kakao.com/)에서 내 어플리케이션에 들어가시면 보이는 5~6자리 숫자입니다.

확인 후 앱 id와 flutter sdk 버전 재첨부 부탁드립니다.

**Comment by gracegyu** [comment]
app id :  542720
flutter sdk version : 1.26.0-1.0.pre

**Comment by 2jeje** [comment]
아래 iOS 가이드 대로 하셨을 까요??

- info.plist 설정
https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios

- AppDelegate 설정
https://developers.kakao.com/docs/latest/ko/kakaologin/ios
