### ISSUE TITLE
Android에서 AuthCodeClient.instance.request() 호출시 에러가 납니다.

### ISSUE THREAD

**Issue by gracegyu** [kakao/kakao_flutter_sdk#76]
카카오톡이 설치되지 않은 환경에서 아래 함수를 호출하게 되어 있습니다.
```dart
  _loginWithKakao() async {
    print("_loginWithKakao");
    try {
      var code = await AuthCodeClient.instance.request();
      print("code = $code");
      await _signInKakao(code);
    } catch (e) {
      print("AuthCodeClient.instance.request Error => $e");
    }
  }
```

이걸 호출하면 아래 에러가 발생합니다.

```
AuthCodeClient.instance.request Error => PlatformException(EUNKNOWN, No browser supports custom tabs protocol on this device., null, null)
```

얼마전에는 정상적으로 카카오톡 로그인 화면이 떠서 로그인이 되었는데, 관련 코드 바뀐 것도 없는데, 오늘 보니 갑자기 이런 에러가 뜹니다. 해당 에러를 인터넷에서 아무리 찾아봐도 원인을 모르겠습니다. 어떻게 해야 하나요?

감사합니다.

**Comment by gracegyu** [comment]
다음과 같습니다.
kakao_flutter_sdk: ^0.5.4
앱 id: 542720

**Comment by mbkim95** [comment]
해당 이슈가 발생한 디바이스의 os버전은 어떻게 되나요?

**Comment by gracegyu** [comment]
Android Emulator(Pixel 2 API 30)입니다. OS는 Android 11.0 입니다.

**Comment by gracegyu** [comment]
Real device에서는 아래와 같은 에러가 발생합니다.
카카오 로그인 창이 정상적으로 떴고, 로그인 정보를 입력하면 창이 닫히면서 아래 에러가 발생합니다.

```
error on issuing access token: {error: misconfigured, error_description: invalid android_key_hash or ios_bundle_id or web_site_url}
```

**Comment by mbkim95** [comment]
@gracegyu 안녕하세요 혹시 실제 디바이스에서도 이슈가 발생하시나요? 테스트 결과 공유해주시면 감사하겠습니다.

**Comment by gracegyu** [comment]
기본 브라우져로 Chrome이 설정되어 있습니다. 현재로선 정확한 원인은 알 수 없고, Emulator에서는 테스트가 불가능한 거네요.

**Comment by gracegyu** [comment]
감사합니다.
