### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.xxxx/com.kakao.sdk.flutter.AuthCodeCustomTabsActivity}: 

### ISSUE THREAD

**Issue by wonjae-codecabin** [kakao/kakao_flutter_sdk#77]
안녕하세요. 카카오 개발자 에다가 등록한 패키지명이 `com.example.xxxx` 였는데 나중에 패키지명을 변경하게되었고, 변경된 패키지명을 카카오개발자에서 수정 하였지만 여전히 에러가 나타납니다. 혹시 프로젝트 내에서 수정을 해줘야하는 부분이 따로있나요?

**Comment by 2jeje** [comment]
안녕하세요?  사용하신 sdk 버전이 어떻게 되시나요??

**Comment by wonjae-codecabin** [comment]
`pubspec.yaml`에서 `kakao_flutter_sdk: ^0.5.2` 이렇게 사용하고있어요. 아래는 `flutter doctor` 실행 했을때 입니다.

`[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-KR) 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 3.6)`

**Comment by 2jeje** [comment]
start Activity 할 때 수정 전 패키지 명이 나오는거 봐서는 (com.example.xxxx)
패키지 명이 정확히 수정이 안된 것으로 보여요.  확인 부탁 드립니다.

com.example.xxxx/com.kakao.sdk.flutter.AuthCodeCustomTabsActivity

**Comment by wonjae-codecabin** [comment]
답변감사드립니다. `AndroidManifest.xml` 파일들 확인후 `manifest package="com.new.new"`로 수정 된 부분들 확인하였는데 혹시 다른곳 변경해야할 곳도 있을까요?

**Comment by wonjae-codecabin** [comment]
https://stackoverflow.com/a/58729067 이 답변을 따라서 `app/src/main/kotlin` 폴더안의 폴더들을 패키지 명과 맞게 변경해주고 `flutter clean`을 실행후 다시 build하니 잘 작동 됩니다. 감사합니다.
