### ISSUE TITLE
iOS에서 requestWithTalk()

### ISSUE THREAD

**Issue by shawn-vp** [kakao/kakao_flutter_sdk#79]
제목대로 iOS에서 카카오톡이 깔려있을 때 requestWithTalk()를 호출하면 카카오톡이 실행되고 다시 앱으로 돌아오는데 그 이후의 결과를 반환하지 않습니다. String값을 반환하지 않고 에러또한 발생하지 않아서 어떤게 문제인지 모르겠습니다.

flutter 1.22.6, 
kakao_flutter_sdk 0.5.4

**Comment by mbkim95** [comment]
안녕하세요~

혹시 `AppDelegate.swift` 에서 application 메소드를 override 하셨나요?

**Comment by shawn-vp** [comment]
@mbkim95 넵 맞습니다

**Comment by mbkim95** [comment]
```
 override func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
    /*
    기타 코드들
    */
    return super.application(application, open: url, sourceApplication: sourceApplication, annotation: annotation)
  }
```

위와 같은 형태로 application 메소드를 수정하시고 다시 실행해보시겠어요?

**Comment by shawn-vp** [comment]
@mbkim95 
`flutter: runZonedGuarded: Caught error in my root zone.
flutter: error: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()`
이런 오류가 뜨고 시작을 안하네요..
최근에 딥링크 기능을 추가한다고 app_links란 패키지를 추가하고나서부터 생긴 문제라 app_links패키지를 제외하고 캐시 다 지우고 해보니까 정상 작동이 됐는데 혹시 집히는게 있을까요?

**Comment by mbkim95** [comment]
`app_links` 패키지는 저희가 관리하는 패키지가 아니라서 정확한 이유는 잘 모르겠습니다.ㅠㅠ

application 메소드 구현하신 코드 첨부 가능하실까요?

**Comment by shawn-vp** [comment]
`import Flutter
import GoogleMaps

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GMSServices.provideAPIKey("google map api key")
    GeneratedPluginRegistrant.register(with: self)
    
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
`
이렇게 되어있습니다!

**Comment by mbkim95** [comment]
@shawn-vp 첨부해주신 코드는 정상 동작하지 않는 코드인가요?

**Comment by shawn-vp** [comment]
requestWithTalk()가 호출되고 카톡이 켜지고 나서 받는 url을 딥링크 라이브러리가 훔쳐가서 requestWithTalk()가 반환도 안하고 에러도 안던지는거였습니다..
답변중에
override func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) 이 부분이 힌트가 돼서 문제 해결했습니다.
빠른 답변 감사합니다!

**Comment by gentlejo** [comment]
동일한 증상을 겪고 있습니다. @shawn-vp 님 어떻게 해결하셨는지 코드로 공유 해주시면 문제를 해결하는데 도움 될 것 같습니다.

**Comment by ska2519** [comment]
> requestWithTalk()가 호출되고 카톡이 켜지고 나서 받는 url을 딥링크 라이브러리가 훔쳐가서 requestWithTalk()가 반환도 안하고 에러도 안던지는거였습니다.. 답변중에 override func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) 이 부분이 힌트가 돼서 문제 해결했습니다. 빠른 답변 감사합니다!

안녕하세요.
저도 딥링크가 적용된 후 동일한 에러가 발생했습니다 😂
AppDelegate.swift을 어떻게 하셔서 해결하셨는지 알려주실 수 있을까요?
swift 코드를 잘 몰라서 감을 못잡겠네요;
