### ISSUE TITLE
안드로이드 카카오 로그인 진행 시 앱 크래쉬 현상

### ISSUE THREAD

**Issue by hyunbogi** [kakao/kakao_flutter_sdk#80]
아래 화면에서 '계속하기' 버튼 클릭 시에 아래와 같은 로그와 함께 앱이 크래쉬합니다.

[이슈 발생 환경]
Flutter 버전 : 2.2.1
kakao_flutter_sdk 버전 : 0.6.3
Platform : Android (sdk-ver. 30)
App ID : net.kmalloc.flutter_social_login

![Screenshot_1623485740](https://user-images.githubusercontent.com/4627670/121770674-a993a500-cba5-11eb-9455-5fff410065ff.png)

[크래쉬 로그]
D/AndroidRuntime(13559): Shutting down VM
E/AndroidRuntime(13559): FATAL EXCEPTION: main
E/AndroidRuntime(13559): Process: net.kmalloc.flutter_social_login, PID: 13559
E/AndroidRuntime(13559): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(13559): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:696)
E/AndroidRuntime(13559): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
E/AndroidRuntime(13559): 	at androidx.appcompat.app.AppCompatDelegateImpl.onPostCreate(AppCompatDelegateImpl.java:376)
E/AndroidRuntime(13559): 	at androidx.appcompat.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:118)
E/AndroidRuntime(13559): 	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1383)
E/AndroidRuntime(13559): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3502)
E/AndroidRuntime(13559): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/AndroidRuntime(13559): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/AndroidRuntime(13559): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/AndroidRuntime(13559): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(13559): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(13559): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13559): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(13559): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(13559): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13559): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(13559): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (13559): Sending signal. PID: 13559 SIG: 9
Lost connection to device.

**Comment by 2jeje** [comment]
안녕하세요? 

AndroidManifest에 등록 하신 AuthCodeHandlerActivity 부분 공유 가능 하실까요??
AuthCodeHandlerActivity 선언 시 Theme를 함께 등록 하셨을까요?

**Comment by hyunbogi** [comment]
요청하신 AndroidManifest 입니다. 따로 Theme를 지정하지는 않았습니다.
https://github.com/hyunbogi/flutter-social-login/blob/main/android/app/src/main/AndroidManifest.xml

`Full source code` : https://github.com/hyunbogi/flutter-social-login.git

**Comment by mbkim95** [comment]
혹시 앱 id가 어떻게 되시나요?

**Comment by 2jeje** [comment]
봐서는 flutter sdk의 Activity 관련 에러는 아닌 것 같은데요.

구현 하신 AppCompatActivity를 상속 받는 Acitivty 중에 Theme.AppCompat를 사용 안하는 부분이 있는지 확인 부탁 드려요

**Comment by hyunbogi** [comment]
@mbkim95 net.kmalloc.flutter_social_login 입니다.
@2jeje 따로 사용하는 액티비티는 없으며 FlutterActivity를 상속하는 MainActivity만 사용합니다.

**Comment by mbkim95** [comment]
@hyunbogi 앱 id는 [디벨로퍼스 사이트](https://developers.kakao.com/) 에서 내 어플리케이션에서 확인할 수 있는 6자리 숫자입니다. 

확인 후 댓글로 남겨주세요

**Comment by hyunbogi** [comment]
@mbkim95 595414 입니다

**Comment by hyunbogi** [comment]
> @hyunbogi 앱 id는 [디벨로퍼스 사이트](https://developers.kakao.com/) 에서 내 어플리케이션에서 확인할 수 있는 6자리 숫자입니다.
> 
> 확인 후 댓글로 남겨주세요

**Comment by mbkim95** [comment]
서버 로그 확인 결과 로그인은 정상적으로 동작하고 있고, SDK의 이슈는 아닌 것으로 판단됩니다. 

구현을 어떻게 하셨는지 정확히 몰라서 정확한 답변은 드릴 수 없지만, 로그인 후에 이동하는 Activity에서 크래시가 발생하는 것 같습니다.

**Comment by hyunbogi** [comment]
다른 플러그인(flutter_kakao_login) 사용하여 구현하였을 때에는 발생하지 않는 현상입니다. 다른 플러그인을 사용하거나 직접 구현하여 사용하도록 하겠습니다.
감사합니다.

**Comment by hyunbogi** [comment]
이슈 원인 파악하였습니다.
제가 AuthCodeHandlerActivity를 잘못 사용하였네요.
`com.kakao.sdk.flutter.AuthCodeCustomTabsActivity` 를 사용하였어야 했는데, `com.kakao.sdk.auth.AuthCodeHandlerActivity` 를 사용하여 발생하는 문제였습니다.
감사합니다.
