### ISSUE TITLE
iOS에서 uni_links 플러그인과 함께 사용 시 uni_links 플러그인이 동작하지 않는 현상

### ISSUE THREAD

**Issue by jeiea** [kakao/kakao_flutter_sdk#86]
정확한 재현방법은 샘플 프로젝트를 만들어야겠지만 그러지 못한 점 먼저 양해 구합니다. 반드시 필요하다면 코멘트 부탁드립니다.

증상은 [uni_links의 이 이슈](https://github.com/avioli/uni_links/issues/63)와 동일합니다. 기존에 kakao_flutter_sdk에서 카카오 로그인 기능을 사용하고 있었습니다. 이번에 앱 자체적으로 custom URL scheme을 사용하려 uni_links 플러그인을 추가해 사용했는데 정확히 저 이슈의 증상, uni_links가 URL 변경을 감지하지 못하는 것을 확인했습니다.

[uni_links](https://github.com/avioli/uni_links/blob/49d05691a8f55e6eeaa0e178e4464b10332370de/uni_links/ios/Classes/UniLinksPlugin.m#L58)와 [kakao_flutter_sdk](https://github.com/kakao/kakao_flutter_sdk/blob/7d95e1f6b30e497b9e24d9c9f9904d72e97fcc1b/ios/Classes/SwiftKakaoFlutterSdkPlugin.swift#L154)가 동시에 URL 입력을 받으려 하고 kakao_flutter_sdk가 먼저 url을 받은 후 무조건 true를 반환해 uni_links가 URL을 처리할 기회가 없는 것으로 보입니다.

[이 부분](https://github.com/kakao/kakao_flutter_sdk/blob/7d95e1f6b30e497b9e24d9c9f9904d72e97fcc1b/ios/Classes/SwiftKakaoFlutterSdkPlugin.swift#L157)을 `return false`로 바꾸니 기대대로 동작했습니다.

그럼에도 따로 AppDelegate.swift에서 application 메소드를 오버라이드하지 않을 경우 플러그인 간 핸들러 우선순위가 명확하진 않아보이지만 일단 이러지 않으면 플러그인 간 충돌은 피할 수 없어보입니다.

이 부분 개선이 가능할까요?

**Comment by 2jeje** [comment]
안녕하세요? 
kakao sdk가 처리 할 수 없는 스킴 같은 경우는 return false 로 변경  검토 하도록 하겠습니다.
검토 후 노티 드리겠습니다.

**Comment by mbkim95** [comment]
@jeiea 안녕하세요
제보주신 이슈 재현 후 테스트 해봤고, 코드는 수정했습니다.

수정 내역은 다음 버전에 포함해서 배포할 예정입니다.

이슈 제보 감사합니다!
