### ISSUE TITLE
swift error when issuing access token

### ISSUE THREAD

**Issue by ilyosbekibrohimov** [kakao/kakao_flutter_sdk#88]
I was trying to implement a Kakao login in my flutter app. It works fine until I get auth code from the Kakao app but when I tried to get the access token via auth code, the app [ios version] suddenly had a crash. Here is the error message I got when the crash happened:
****
kakao_flutter_sdk/Utility.swift:36: Fatal error: Unexpectedly found nil while unwrapping an Optional value
****
kakao_flutter_sdk  version:^0.7.0
my Info.plist file:
<key>CFBundleURLSchemes</key>
			<array>
				<string>${my url scheme}</string>
			</array>
<key>KAKAO_APP_KEY</key>
	<string>my client id</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>kakao${my client id}</string>
		<string>kakaokompassauth</string>
		<string>storykompassauth</string>
		<string>kakaolink</string>
		<string>kakaotalk-5.9.7</string>
	</array>

kakao login:
```dart
  Future<String> signInWithKakao() async {
    final installed = await isKakaoTalkInstalled();
    print(installed);
    String credentials ="";
    KakaoContext.clientId = ${my client id};

    if (installed) {
      try {
        var code = await AuthCodeClient.instance.requestWithTalk();
         print("code $code");

         // the line where the crash happened
         var token = await AuthApi.instance.issueAccessToken(code);
         print("token $token");
         AccessTokenStore.instance.toStore(token);
         credentials = "access_token:${token.accessToken}";
         print("credentials=>>>>$credentials");
         return credentials;
       }

      on KakaoAuthException catch (e) {
        showToast("Unexpected error occured, please try again!");
        print(e);
        credentials = e.toString();
      } on KakaoClientException catch (e) {
        showToast("Unexpected error occured, please try again!");
        print(e);
        credentials = e.toString();
      }
    } else {
      showToast("Kakao talk is not installed");
      credentials = "?";
    }
    return credentials;
  }
```

**Comment by mbkim95** [comment]
Hi @ilyosbekibrohimov

What is your application id?

Application Id is the value found in the My Application menu of [Kakao Developers](https://developers.kakao.com).

**Comment by ilyosbekibrohimov** [comment]
Hello,
Thank you for your response!
My application ID is  591973
Thank you.

**Comment by mbkim95** [comment]
I didn't know the exact cause just by the information you gave me.

Can you show me the log when the crash occurs in your app?

And if possible, I would appreciate it if you could let me know the device information that causes the issue, OS version, and whether it does not occur on other devices.

Additionally, `UserApi.loginWithKakaoTalk` is added from version 0.7, making it easier to implement logins. Please refer to README.
