### ISSUE TITLE
kakaolink - Default browsers only supports URL of http or https scheme. 

### ISSUE THREAD

**Issue by jungsangeun** [kakao/kakao_flutter_sdk#89]
안녕하세요. 카카오링크 공유하기 관련 문의 드립니다.
가이드 문서를 토대로

LinkClient.instance.customWithTalk() 을 사용하여 uri를 생성하면 scheme이 kakaolink인 Uri 생성되는데요.
이 Uri를 사용하여 launchBrowserTab을 호출하면 함수 내부에서 'Default browsers only supports URL of http or https scheme.' 오류를 발생시키고 있습니다.

확인 부탁드립니다.

**Comment by mbkim95** [comment]
안녕하세요~

에러 발생하는 코드와 앱 id를 알려주시면 감사하겠습니다.

**Comment by jungsangeun** [comment]
앱ID 526691
코드
final uri = await LinkClient.instance.customWithTalk(58140, templateArgs: {...});
await launchBrowserTab(uri);

**Comment by mbkim95** [comment]
@jungsangeun 현재 카카오링크 API 는 `xxxxWithWeb` 메서드들과 `xxxxWithTalk` 메서드들로 크게 2종류의 메서드들을 제공하고 있는데요,

이 중에서 `xxxxWithWeb` 메서드들은 웹을 통해 공유하는 기능이므로 해당 메서드를 통해 전달받은 uri를 `launchBrowserTab` 메서드에 전달해주는 방식으로 카카오링크 API를 사용할 수 있습니다.

문의주신 `xxxxWithTalk` 메서드들은 카카오톡을 통해 공유하는 기능이므로 해당 메서드를 통해 전달받은 uri는 `LinkClient.launchKakaoTalk`메서드에 전달해야 카카오톡으로 카카오링크 API를 사용할 수 있습니다.

따라서 문의주신 코드에서 `launchBrowserTab` 부분을 `LinkClient.instance.launchKakaoTalk(uri)` 로 수정하시면 정상적으로 동작할 것으로 보입니다.

감사합니다
