### ISSUE TITLE
Legacy?

### ISSUE THREAD

**Issue by jjangga0214** [kakao/kakao_flutter_sdk#90]
안녕하세요?

README 에서 다음 부분의 링크를 보니 Legacy iOS SDK 와 Legacy Android SDK 에 연결되는 것을 확인했습니다.
 
![Screenshot from 2021-07-31 09-57-50](https://user-images.githubusercontent.com/28584151/127723738-9a1e6f37-63ef-4470-8328-a13592d522f7.png)

그런데 README 의 서두에는 본 package 가 Kakao SDK 의 dart version 이라고 소개하지, Kakao Legacy SDK 의 dart 구현체라고 소개하고 있지 않습니다.

![Screenshot from 2021-07-31 10-00-35](https://user-images.githubusercontent.com/28584151/127723774-0b816fd1-2282-4690-8b00-2be72b3ee0cb.png)

어째서 Kakao SDK 의 dart port 를 사용하는데 Legacy 의 방법을 따라야 할까요?

감사합니다.

**Comment by mbkim95** [comment]
안녕하세요

문의 주신 부분은 최신 버전 SDK(Android / iOS v2 SDK)와 Legacy SDK의 설정방법이 동일하기 때문에 현재 문제되는 부분은 없을 것으로 보입니다.

하지만 유지보수의 차원에서 최신 버전 문서에 링크가 연결되는 것이 좋을 것으로 판단되어 수정 후 다음 버전에 반영하도록 하겠습니다.

제보 감사합니다!
