### ISSUE TITLE
'isKakaoStoryInstalled' 와 'launchKakaoStory' 는 MethodChannel 지원 않되나요 ? (Template 지원하나요 ?)

### ISSUE THREAD

**Issue by dizang2** [kakao/kakao_flutter_sdk#95]
MethodChannel 을 통해  KakaoStory 를 KakaoTalk 처럼 구현하고 싶은데 

'isKakaoStoryInstalled' 와 'launchKakaoStory' 는 MethodChannel 지원 않되나요 ?

어떻게 kakaoTalk 처럼 사용 할 수 있을가요 ?

**Comment by mbkim95** [comment]
안녕하세요

현재 카카오 스토리 관련 API로 `isKakaoStoryInstalled` 와 `launchKakaoStory` 기능은 제공하고 있지 않고 있습니다.

기능 추가에 대해서 검토는 해보겠지만, 해당 기능들이 추가되기는 조금 어려울 것으로 보여서 이 점 양해 부탁드리겠습니다ㅠㅠ

**Comment by dizang2** [comment]
kakaoStory로 메세지를 공유할 수 있는 샘플 예제가 있었음 하는데 제공 부탁드립니다.

**Comment by mbkim95** [comment]
카카오 스토리로 메시지를 공유한다는게 정확히 어떤 말씀이신지 이해하지 못했네요

직접 개발하신 앱 내의 정보를 카카오 스토리에 포스팅하고 싶다는 말씀이신가요?

구체적으로 '카카오톡처럼' 이라고 말씀하신 부분의 캡처본 혹은 동영상 녹화본을 첨부해주시면 정확하게 이해하는데 도움이 될 것 같습니다. 

가능하시다면 캡처 이미지 혹은 동영상 첨부 부탁드려요.

**Comment by dizang2** [comment]
본앱에서 아래 코드를 이용하여 kakaoStory app을 연동시키려는 목적입니다.
근데 않되서요... TT  

      var linkInfo =
          LinkInfo(url, null, null, message, [imageUrl], message, null, null);

      var json = <String, dynamic>{
        'url': url,
        'title': message,
        'images': [imageUrl],
        'description': message,
        //'requestedUrl': 'requestedUrl',
        //'host': '',
        //'section': '',
        //'type': '',
      };

      //var linkInfo = LinkInfo.fromJson(json);
      var id = await StoryApi.instance.postLink(linkInfo, enableShare: true);

      print(id);

**Comment by mbkim95** [comment]
아쉽지만 현재 카카오스토리 앱을 실행시키는 기능은 제공하지 않고 있고, 추가되기는 어려울 것 같아요ㅠㅠ

올려주신 코드처럼 카카오스토리에 포스팅 작성해주는 기능을 통해 간접적으로라도 구현하셔야 할 것 같습니다.

만족스럽지 못한 답변을 남겨드려 죄송합니다
