### ISSUE TITLE
error: misconfigured, error_description: invalid android_key_hash or ios_bundle_id or web_site_url

### ISSUE THREAD

**Issue by sgruhier** [kakao/kakao_flutter_sdk#97]
Hi,
Sorry I'm not Korea so I'll write in English (I'm French BTW)
I'm trying to use kakao login in a iOS app. I think I did all steps but after `UserApi.instance.loginWithKakaoTalk()` call, I got that error

```
flutter: {error: misconfigured, error_description: invalid android_key_hash or ios_bundle_id or web_site_url}
``` 

Did I miss something? 
Thank you very much

**Comment by mbkim95** [comment]
Hi @sgruhier 

What is your app id in [developers site](https://developers.kakao.com)?

**Comment by sgruhier** [comment]
Hi
It's epikepok / 624998
Thanks!

**Comment by mbkim95** [comment]
I checked, but there is no app platform setting in [developers site](https://developers.kakao.com/).

If you set it up with reference to this [document](https://developers.kakao.com/docs/latest/en/getting-started/app#platform), it will work correctly.

**Comment by sgruhier** [comment]
Thanks! I'm gonna check right now.
It's harder for me because that part of the documentation is only in Korean. With google traduction and the help of my daughter who lives in Seoul, I should be able to do it :)
I'll let you know

**Comment by mbkim95** [comment]
If you are using developers site in English, the relevant settings page will also appear in English. 

Please refer to this point and set it up. 

Thank you.

**Comment by sgruhier** [comment]
Thanks a lot!
It works now.
Thanks for that great plugin. I really like flutter and like even more the community
Can't wait to be able to use it in web application too
감사합니다

**Comment by sgruhier** [comment]
Sorry to bother again, I still have an issue.
It works perfectly fine using ios simulator. It uses that HTML popup to login because there is no kakao talk app on simulator.
If I test on my device. It doesn't work. It opens kakao. Then in kakao, I see a modal opening to accept connection. But that popup is blank and closes immediately without going back to my app. If I go back by myself to my app, I'm not logged in

Nothing happens after that call

```dart
await UserApi.instance.loginWithKakaoTalk()
``` 

Any idea?

**Comment by mbkim95** [comment]
Can you show me the video when the issue occurs? I didn't quite understand what you were explaining.

**Comment by sgruhier** [comment]
Sure, thanks! 
As you can see on the video
- I tap on "login button"
- It opens kakao and you see that bottom modal opening , blank, and gos away after 1 second
- Then I return to my app and I'm still on login page.

here is login code
```dart 
  _login() async {
    try {
      final installed = await isKakaoTalkInstalled();
      installed ? await UserApi.instance.loginWithKakaoTalk() : await UserApi.instance.loginWithKakaoAccount();
      Navigator.of(context).pushReplacementNamed("/main");
    } catch (e) {
      print(e.toString());
    }
  }
```

Is it more clear?

https://user-images.githubusercontent.com/3385/130040072-69b13d02-2ed5-4e92-a517-dd63e217cb2b.mp4

**Comment by mbkim95** [comment]
Hi @sgruhier

I understood your issue. you need to set up additional settings in the native file.

 Please refer to [the document](https://developers.kakao.com/docs/latest/en/getting-started/sdk-ios#set-plist) for details.

**Comment by sgruhier** [comment]
Thanks a lot! You rocks
Everything is fine on iOS. Now 
I'm trying to set up Android. I think I did everything I read here https://developers.kakao.com/docs/latest/en/getting-started/sdk-android

but on android emulateur after login by html I have this message again :(

`I/flutter ( 3301): {error: misconfigured, error_description: invalid android_key_hash or ios_bundle_id or web_site_url}
`

**Comment by mbkim95** [comment]
If you read and set up the Android platform settings in [this document](https://developers.kakao.com/docs/latest/en/getting-started/sdk-android#add-key-hash), it will work normally.

Keep in mind that if you launch the app on the PlayStore, you will also need to register the release keyhash value.

**Comment by mbkim95** [comment]
@sgruhier Are all the problems solved? 

If so, I will close this issue. 

Please reply to this comment.
