### ISSUE TITLE
PlatformException(EUNKNOWN, No browser supports custom tabs protocol on this device., null, null)  오류가 발생합니다.

### ISSUE THREAD

**Issue by gracegyu** [kakao/kakao_flutter_sdk#98]
Flutter v1 을 쓰고 있어서 kakao_flutter_sdk v0.5.4를 사용하고 있습니다.

Android에서 AuthCodeClient.instance.request() 함수를 실행하면 제목과 같은 Exception이 발생합니다.
Simulator, 실제Device 모두 오류가 발생하고 있습니다.
iOS에서는 잘 되고 있습니다.

혹시 제가 설정을 잘못한 것이 있을까요?

어떻게 해결 해야 하나요?

$flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
[✓] Android Studio
[✓] VS Code (version 1.59.0)
[✓] Connected device (4 available)

• No issues found!

**Comment by mbkim95** [comment]
안녕하세요

해당 에러는 디바이스 내에 크롬 브라우저가 사용 안함 상태이고, 디바이스에 기본 브라우저가 설정되지 않은 상태일 때 발생하는 에러입니다.

디바이스 내에 크롬 브라우저가 '사용 안함' 상태인지 확인 후 사용으로 변경하시거나, 다른 인터넷 브라우저를 디바이스의 기본 브라우저로 설정하시면 정상적으로 동작할 것으로 보입니다.

감사합니다.

**Comment by gracegyu** [comment]
크롬브라우저가 정상 설치되었고, 기본 브라우저로 설정되어 있는 상태입니다.

**Comment by mbkim95** [comment]
혹시 앱 id와 구현하신 코드 첨부 가능하실까요? 코드를 확인해봐야할 것 같습니다

**Comment by gracegyu** [comment]
카카오톡이 설치된 경우, 설치되지 않은 경우 모두 동일한 에러가 발생합니다.

앱id: af151fe68194fd3fbd408286ea70b9fd

AndroidManifest.xml
`
    <application ... >
      ....
        <activity android:name="com.kakao.sdk.flutter.AuthCodeCustomTabsActivity">
            <intent-filter android:label="flutter_web_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="kakaoaf151fe68194fd3fbd408286ea70b9fd" android:host="oauth"/>
            </intent-filter>
        </activity>
        <activity android:name="com.kakao.sdk.auth.AuthCodeHandlerActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                
                <data android:host="oauth"
                    android:scheme="kakaoaf151fe68194fd3fbd408286ea70b9fd" />
            </intent-filter>
        </activity>
`

카카오톡이 설치 되지 않은 경우
`
  _getKakaoAuthCodeWithKakao() async {
    try {
      var code = await AuthCodeClient.instance.request();
      debugPrint("code = $code");
      return code;
    } on KakaoAuthException catch (e) {
      debugPrint("KakaoAuthException $e");
    } on KakaoClientException catch (e) {
      debugPrint("KakaoAuthException $e");
    } catch (e) {
      debugPrint("AuthCodeClient.instance.request catch Exception => $e");
      // => PlatformException(EUNKNOWN, No browser supports custom tabs protocol on this device, null, null)
    }
    return null;
  }
`

카카오톡이 설치된 경우
`
  _getKakaoAuthCodeWithTalk() async {
    try {
      var code = await AuthCodeClient.instance.requestWithTalk();
      debugPrint("code = $code");
      return code;
    } on KakaoAuthException catch (e) {
      debugPrint("KakaoAuthException $e");
      return _getKakaoAuthCodeWithKakao();
    } on KakaoClientException catch (e) {
      debugPrint("KakaoClientException $e");
      return _getKakaoAuthCodeWithKakao();
    } catch (e) {
      debugPrint("AuthCodeClient.instance.requestWithTalk catch Exception => $e");
      // => PlatformException(EUNKNOWN, No browser supports custom tabs protocol on this device, null, null)
      return _getKakaoAuthCodeWithKakao();
    }
  }
`

**Comment by mbkim95** [comment]
@gracegyu  안녕하세요~ 답변이 조금 늦었네요ㅠㅠ

해당 이슈는 안드로이드11(API 30)이 되면서 패키지 관련해서 정책이 바뀌어서 SDK에서 Google Chrome 브라우저, 카카오톡을 찾지 못해서 발생한 이슈로 보입니다. 자세한 내용은 [안드로이드 공식 문서](https://developer.android.com/training/basics/intents/package-visibility?hl=ko#declare-other-apps) 참고바랍니다.

kakao_flutter_sdk 0.5.4에는 해당 내용이 반영되어있지 않아서 이슈가 발생했는데, sdk 버전을 올리는 것이 힘든 상황이라고 하셔서 아래의 방법들을 참고해서 수정하시면 해결 될 것 같습니다.

### 1. 개발 중인 앱과 상호작용할 수 있는 앱들의 패키지 이름을 등록해주는 방법
현재 kakao_flutter_sdk는 카카오톡으로 로그인할 때 카카오톡 앱, 카카오 계정으로 로그인할 때 chrome 브라우저를 사용하고 있습니다. 따라서 개발 중인 앱에서 카카오톡과 chrome 브라우저와 상호작용할 수 있도록 `AndroidManifest.xml` 파일에 `<query>` 태그를 열고 그 안에 상호작용할 패키지 이름을 명시해주면 됩니다.

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.flutter_app_test">

    <queries>
        <package android:name="com.kakao.talk" />
        <package android:name="com.kakao.onetalk" />
        <package android:name="com.android.chrome" />
        <package android:name="com.chrome.beta" />
        <package android:name="com.chrome.dev" />
    </queries>

    <application
        android:icon="@mipmap/ic_launcher"
        android:label="flutter_app_test">

        <activity
            android:name=".MainActivity"
            ...
    </application>
</manifest>

```

### 2. 모든 앱들의 패키지 목록을 사용할 수 있도록 권한을 주는 방법
1번의 방법처럼 특정 패키지 명을 명시하지 않고 디바이스에 설치된 모든 패키지에 접근할 수 있는 권한을 주는 방법이 있습니다. 이 방법은 `AndroidManifest.xml` 파일에 해당 권한을 추가하면 됩니다.
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.flutter_app_test">

    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>

    <application
        android:icon="@mipmap/ic_launcher"
        android:label="flutter_app_test">

        <activity
            android:name=".MainActivity"
            ...
    </application>
</manifest>
```

**Comment by gracegyu** [comment]
해결되었습니다. 대단히 감사합니다.
👍
